### ISSUE TITLE
Sidekiq service suddenly stopped / not running

### ISSUE THREAD

**Issue by auzty** [gitlabhq/gitlabhq#10038]
my gitlab was upgraded a few month ago from 7.0 to 8.3.4 , everything is fine, but somehow my sidekiq stopped and there are the error log from sidekiq
```
(<unknown>): mapping values are not allowed in this context at line 2 column 13
/usr/local/lib/ruby/2.1.0/psych.rb:370:in `parse'
/usr/local/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
/usr/local/lib/ruby/2.1.0/psych.rb:318:in `parse'
/usr/local/lib/ruby/2.1.0/psych.rb:245:in `load'
/home/git/vendor/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:364:in `parse_config'
/home/git/vendor/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:207:in `setup_options'
/home/git/vendor/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:38:in `parse'
/home/git/vendor/ruby/2.1.0/gems/sidekiq-4.0.1/bin/sidekiq:12:in `<top (required)>'
/home/git/vendor/ruby/2.1.0/bin/sidekiq:23:in `load'
/home/git/vendor/ruby/2.1.0/bin/sidekiq:23:in `<main>'
```
thanks you...

**Comment by stanhu** [comment]
That sounds like a typo somewhere in a YAML config file:

http://stackoverflow.com/questions/18685702/rails-4-mapping-values-are-not-allowed-in-this-context-at-line-2-column-11-psy
