### ISSUE TITLE
Rugged::OdbError (Failed to inflate loose object.) after upgrading to 8.6.5-ce.0

### ISSUE THREAD

**Issue by Quintasan** [gitlabhq/gitlabhq#10133]
Hi,

I have just upgraded to 8.6.5-ce.0 from the repository and I'm getting 500 on every page right now

```
Processing by RootController#index as HTML
Completed 500 Internal Server Error in 168ms (ActiveRecord: 50.6ms)

ActionView::Template::Error (Failed to inflate loose object.):
     6: - css_class = '' unless local_assigns[:css_class]
     7: - show_last_commit_as_description = false unless local_assigns[:show_last_commit_as_description] == true && project.commit
     8: - css_class += " no-description" if project.description.blank? && !show_last_commit_as_description
     9: - ci_commit = project.ci_commit(project.commit.sha) if ci && !project.empty_repo? && project.commit
    10: - cache_key = [project.namespace, project, controller.controller_name, controller.action_name, current_application_settings, 'v2.2']
    11: - cache_key.push(ci_commit.status) if ci_commit
    12: 
  app/models/repository.rb:75:in `block in has_visible_content?'
  lib/repository_cache.rb:19:in `fetch'
  app/models/repository.rb:74:in `has_visible_content?'
  app/models/project.rb:679:in `empty_repo?'
  app/views/shared/projects/_project.html.haml:9:in `_app_views_shared_projects__project_html_haml__1284523364662887717_59438820'
  app/views/shared/projects/_list.html.haml:16:in `block in _app_views_shared_projects__list_html_haml___1527116287911117281_59150900'
  app/views/shared/projects/_list.html.haml:14:in `_app_views_shared_projects__list_html_haml___1527116287911117281_59150900'
  app/views/dashboard/projects/_projects.html.haml:1:in `_app_views_dashboard_projects__projects_html_haml___4220564257073278983_59086100'
  app/views/dashboard/projects/index.html.haml:14:in `_app_views_dashboard_projects_index_html_haml___1223634626011492756_57358700'
  app/controllers/dashboard/projects_controller.rb:15:in `index'
  app/controllers/root_controller.rb:13:in `index'
  lib/gitlab/middleware/go.rb:16:in `call'
```

Trying to access any particular project yields:

```
Processing by ProjectsController#show as HTML
  Parameters: {"namespace_id"=>"iNeoSyte", "id"=>"backend"}
Completed 500 Internal Server Error in 47ms (ActiveRecord: 4.7ms)

Rugged::OdbError (Failed to inflate loose object.):
  app/models/repository.rb:75:in `block in has_visible_content?'
  lib/repository_cache.rb:19:in `fetch'
  app/models/repository.rb:74:in `has_visible_content?'
  app/models/project.rb:679:in `empty_repo?'
  app/controllers/projects_controller.rb:250:in `repo_exists?'
  lib/gitlab/middleware/go.rb:16:in `call'
```

sudo gitlab-rake gitlab:check yields
```
admin@serwer-1:~$ sudo gitlab-rake gitlab:check --trace
** Invoke gitlab:check (first_time)
** Invoke gitlab:gitlab_shell:check (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute gitlab:gitlab_shell:check
Checking GitLab Shell ...

GitLab Shell version >= 2.6.12 ? ... OK (2.6.12)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
hooks directories in repos are links: ... 
iNeoSyte / backend ... rake aborted!
Rugged::OdbError: Failed to inflate loose object.
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:71:in `target'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:71:in `block in branch_count'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:69:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:69:in `count'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/gitlab_git-10.0.0/lib/gitlab_git/repository.rb:69:in `branch_count'
/opt/gitlab/embedded/service/gitlab-rails/app/models/repository.rb:75:in `block in has_visible_content?'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:299:in `block in fetch'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:547:in `block in instrument'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:547:in `instrument'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/cache.rb:299:in `fetch'
/opt/gitlab/embedded/service/gitlab-rails/lib/repository_cache.rb:19:in `fetch'
/opt/gitlab/embedded/service/gitlab-rails/app/models/repository.rb:74:in `has_visible_content?'
/opt/gitlab/embedded/service/gitlab-rails/app/models/project.rb:679:in `empty_repo?'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:468:in `block in check_repos_hooks_directory_is_link'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:51:in `block in find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/relation/batches.rb:50:in `find_each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:9:in `find_each'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:464:in `check_repos_hooks_directory_is_link'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/check.rake:348:in `block (3 levels) in <top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `load'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:check => gitlab:gitlab_shell:check
```

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
