### ISSUE TITLE
Error on restoring backup for 8.7 

### ISSUE THREAD

**Issue by Gomez** [gitlabhq/gitlabhq#10316]
I have done a backup on my old server (old debian - see versions below) and wanna import it into my new server (new debian - see versions below). Got this error:

```
~/gitlab$ bundle exec rake gitlab:backup:restore RAILS_ENV=production BACKUP=1461925884 --trace
** Invoke gitlab:backup:restore (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute gitlab:backup:restore
Unpacking backup ... done
Do you want to continue (yes/no)? yes
Removing all tables. Press `Ctrl-C` within 5 seconds to abort
Cleaning the database ... 
** Invoke gitlab:db:drop_tables (first_time)
** Invoke environment 
** Execute gitlab:db:drop_tables
rake aborted!
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'keys' at line 1
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/var/local/gitlab/gitlab/config/initializers/connection_fix.rb:20:in `execute'
/var/local/gitlab/gitlab/lib/tasks/gitlab/db.rake:32:in `block (4 levels) in <top (required)>'
/var/local/gitlab/gitlab/lib/tasks/gitlab/db.rake:32:in `each'
/var/local/gitlab/gitlab/lib/tasks/gitlab/db.rake:32:in `block (3 levels) in <top (required)>'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/local/gitlab/gitlab/lib/tasks/gitlab/backup.rake:48:in `block (3 levels) in <top (required)>'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/var/local/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:db:drop_tables
gitlab@glenn:~/gitlab$ 
```

New server:
```
~/gitlab$ bundle exec rake gitlab:env:info RAILS_ENV=production 

System information
System:         Debian 8.4
Current User:   gitlab
Using RVM:      no
Ruby Version:   2.1.5p273
Gem Version:    2.2.2
Bundler Version:1.11.2
Rake Version:   10.5.0
Sidekiq Version:4.0.1

GitLab information
Version:        8.7.0
Revision:       a1db135
Directory:      /var/local/gitlab/gitlab
DB Adapter:     mysql2
URL:            https://git.starzel.de
HTTP Clone URL: https://git.starzel.de/some-group/some-project.git
SSH Clone URL:  gitlab@git.starzel.de:some-group/some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        2.7.2
Repositories:   /var/local/gitlab/repositories/
Hooks:          /var/local/gitlab/gitlab-shell/hooks/
Git:            /usr/bin/git
```

old server:
```
gitlab@glenn:~/gitlab$ bundle exec rake gitlab:env:info RAILS_ENV=production 

System information
System:         Debian 7.9
Current User:   gitlab
Using RVM:      no
Ruby Version:   2.1.5p273
Gem Version:    2.2.2
Bundler Version:1.8.0
Rake Version:   10.5.0
Sidekiq Version:4.0.1

GitLab information
Version:        8.7.0
Revision:       81dafb7
Directory:      /var/local/gitlab/gitlab
DB Adapter:     mysql2
URL:            https://git.starzel.de
HTTP Clone URL: https://git.starzel.de/some-group/some-project.git
SSH Clone URL:  gitlab@git.starzel.de:some-group/some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        2.7.2
Repositories:   /var/local/gitlab/repositories/
Hooks:          /var/local/gitlab/gitlab-shell/hooks/
Git:            /usr/bin/git
gitlab@glenn:~/gitlab$
```

**Comment by Gomez** [comment]
I noticed this difference

old server (mysql --version):
```
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.2
```

New server (mysql --version):
```
mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Some1 an advice on how to get the restore working?

**Comment by Gomez** [comment]
Solved it by comment out the drop_table:
https://github.com/gitlabhq/gitlabhq/blob/master/lib/tasks/gitlab/backup.rake#L49

And finished the restore on a complete empty database.
