### ISSUE TITLE
500 error with gitlab 8.7 when saving wikis

### ISSUE THREAD

**Issue by ahunigel** [gitlabhq/gitlabhq#10319]
I am trying to edit the home page, 500 error occured.

```
Started POST "/pet/oxygen/wikis" for 127.0.0.1 at 2016-05-03 15:29:33 +0800
Processing by Projects::WikisController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "wiki"=>{"title"=>"home", "format"=>"markdown", "content"=>"testnigel", "message"=>"add wiki "}, "namespace_id"=>"pet", "project_id"=>"oxygen"}
Completed 500 Internal Server Error in 70ms (ActiveRecord: 6.0ms)

NoMethodError (undefined method `username' for #<Group:0x0000000a083dd8>):
  app/models/project_wiki.rb:158:in `default_message'
  app/models/project_wiki.rb:152:in `commit_details'
  app/models/project_wiki.rb:91:in `create_page'
  app/models/wiki_page.rb:183:in `save'
  app/models/wiki_page.rb:143:in `create'
  app/services/wiki_pages/create_service.rb:6:in `execute'
  app/controllers/projects/wikis_controller.rb:58:in `create'
  lib/gitlab/middleware/go.rb:16:in `call'


==> /var/log/gitlab/gitlab-workhorse/current <==
2016-05-03_07:29:34.00274 2016/05/03 15:29:34 ErrorPage: serving predefined error page: 500
2016-05-03_07:29:34.00293 10.161.78.54 @ - - [2016-05-03 15:29:33.707783034 +0800 HKT] "POST /pet/oxygen/wikis HTTP/1.1" 500 2205 "http://10.161.78.54/pet/oxygen/wikis/home" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2716.0 Safari/537.36" 0.295113

```

**Comment by rymai** [comment]
Thanks for the report @ahunigel. This is fixed by https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3924 and will be released in GitLab 8.7.2.
