### ISSUE TITLE
Gitlab::Git::Repository::NoRepository (no repository for such path):

### ISSUE THREAD

**Issue by matheusbona** [gitlabhq/gitlabhq#10395]
After update Gitlab via Omnibus package my screen of projects (dashboard/projects) returns error 500

Started GET "/dashboard/projects" for 10.40.42.151 at 2016-10-24 17:33:29 -0200
Processing by Dashboard::ProjectsController#index as HTML
Completed 500 Internal Server Error in 120ms (ActiveRecord: 39.2ms)

Gitlab::Git::Repository::NoRepository (no repository for such path):
  app/models/repository.rb:756:in `local_branches'
  app/models/repository.rb:209:in `block in branch_names'
  lib/repository_cache.rb:20:in `fetch'
  app/models/repository.rb:209:in `branch_names'
  app/models/repository.rb:213:in `branch_exists?'
  app/models/user.rb:503:in `block in recent_push'
  app/models/user.rb:499:in `recent_push'
  app/controllers/dashboard/projects_controller.rb:13:in `index'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'

VERSION
Unpacking gitlab-ce (8.13.0-ce.0) over (8.12.7-ce.0) ...
Setting up gitlab-ce (8.13.0-ce.0) ...

**Comment by matheusbona** [comment]
Resolved! 

I mount a NFS and edit the gitlab.yml inside of /var/opt/gitlab/gitlab-rails/etc/ (using ubuntu)

I`ve change my configuration to /etc/gitlab/gitlab.rb and gitlab-ctl reconfigure

Working again

Thanks! Closing the issue
