### ISSUE TITLE
rake aborted! TypeError: compared with non class/module

### ISSUE THREAD

**Issue by cabinwj** [gitlabhq/gitlabhq#10445]
>  /usr/local/bin/bundle exec /usr/local/bin/rake db:migrate RAILS_ENV=production

rake aborted!
TypeError: compared with non class/module
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `<='
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `block in matches?'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `any?'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations/base.rb:27:in `matches?'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations.rb:76:in `block in match'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations.rb:76:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations.rb:76:in `detect'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/integrations.rb:76:in `match'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/machine.rb:511:in `initialize'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/machine.rb:439:in `new'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/machine.rb:439:in `find_or_create'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/state_machines-0.5.0/lib/state_machines/macro_methods.rb:518:in `state_machine'
/Users/git/gitlab/app/models/merge_request.rb:44:in `<class:MergeRequest>'
/Users/git/gitlab/app/models/merge_request.rb:1:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/Users/git/gitlab/lib/github/import.rb:7:in `<class:Import>'
/Users/git/gitlab/lib/github/import.rb:4:in `<module:Github>'
/Users/git/gitlab/lib/github/import.rb:3:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/Users/git/gitlab/lib/gitlab/import_sources.rb:11:in `<module:ImportSources>'
/Users/git/gitlab/lib/gitlab/import_sources.rb:7:in `<module:Gitlab>'
/Users/git/gitlab/lib/gitlab/import_sources.rb:6:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:184:in `const_missing'
/Users/git/gitlab/app/models/application_setting.rb:235:in `defaults'
/Users/git/gitlab/lib/gitlab/current_settings.rb:13:in `fake_application_settings'
/Users/git/gitlab/lib/gitlab/current_settings.rb:34:in `uncached_application_settings'
/Users/git/gitlab/lib/gitlab/current_settings.rb:22:in `ensure_application_settings!'
/Users/git/gitlab/lib/gitlab/current_settings.rb:7:in `current_application_settings'
/Users/git/gitlab/lib/gitlab/metrics/influx_db.rb:20:in `settings'
/Users/git/gitlab/lib/gitlab/metrics/influx_db.rb:11:in `influx_metrics_enabled?'
/Users/git/gitlab/lib/gitlab/metrics.rb:7:in `enabled?'
/Users/git/gitlab/config/initializers/8_metrics.rb:132:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:353:in `initialize!'
/Users/git/gitlab/config/environment.rb:7:in `<top (required)>'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:329:in `require_environment!'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:458:in `block in run_tasks_blocks'
/Users/git/gitlab/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

**Comment by cabinwj** [comment]
/usr/local/bin/bundle install --deployment --without development test postgres aws kerberos
Fetching gem metadata from https://gems.ruby-china.org/.........
Fetching version metadata from https://gems.ruby-china.org/..
Using rake 12.0.0
Using RedCloth 4.3.2
Using ace-rails-ap 4.1.3
Using i18n 0.8.6
Using minitest 5.7.0
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.8
Using mime-types 2.99.3
Using arel 6.0.4
Using addressable 2.3.8
Using akismet 2.0.0
Using allocations 1.0.5
Using multipart-post 2.0.0
Using multi_json 1.12.1
Using jwt 1.5.6
Using multi_xml 0.6.0
Using asciidoctor 1.5.6.1
Using ast 2.3.0
Using atomic 1.1.99
Using encryptor 3.0.0
Using attr_required 1.0.1
Using extlib 0.9.16
Using execjs 2.7.0
Using ice_nine 0.11.2
Using babosa 1.0.2
Using base32 0.3.2
Using bcrypt 3.1.11
Using bcrypt_pbkdf 1.0.0
Using bindata 2.4.0
Using sass 3.4.25
Using bootstrap_form 2.7.0
Using browser 2.5.0
Using bundler 1.15.4
Using charlock_holmes 0.7.5
Using chronic 0.10.2
Using numerizer 0.1.1
Using chunky_png 1.3.8
Using citrus 3.0.2
Using concurrent-ruby 1.0.5
Using connection_pool 2.2.1
Using safe_yaml 1.0.4
Using creole 0.5.0
Using thor 0.19.4
Using debugger-ruby_core_source 1.3.8
Using orm_adapter 0.5.0
Using rotp 2.1.2
Using diff-lcs 1.3
Using diffy 3.1.0
Using unf_ext 0.0.7.4
Using securecompare 1.0.0
Using url_safe_base64 0.2.2
Using email_reply_trimmer 0.1.7
Using equalizer 0.0.11
Using escape_utils 1.1.1
Using excon 0.58.0
Using expression_parser 0.9.0
Using fast_gettext 1.5.1
Using ffi 1.9.18
Using flipper 0.10.2
Using json 1.8.6
Using formatador 0.2.5
Using ipaddress 0.8.3
Using xml-simple 1.1.5
Using rugged 0.26.0
Using get_process_mem 0.2.1
Using locale 2.1.2
Using text 1.3.1
Using google-protobuf 3.4.0.2 (universal-darwin)
Using little-plugger 1.1.4
Using memoist 0.16.0
Using os 0.9.6
Using github-markup 1.6.1
Using posix-spawn 0.3.13
Using gitlab-markup 1.5.1
Using net-ldap 0.16.0
Using hashie 3.5.6
Using pyu-ruby-sasl 0.0.3.3
Using rubyntlm 0.6.2
Using rouge 2.2.1
Using stringex 2.7.1
Using request_store 1.3.2
Using retriable 1.4.1
Using mustermann 1.0.0
Using tilt 2.0.8
Using parallel 1.12.0
Using powerpack 0.1.1
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.3.0
Using sysexits 1.2.0
Using temple 0.7.7
Using mimemagic 0.3.2
Using htmlentities 4.3.4
Using http-form_data 1.0.3
Using http_parser.rb 0.6.0
Using httpclient 2.8.3
Using influxdb 0.4.0
Using oauth 0.5.3
Using jquery-atwho-rails 1.3.2
Using kaminari-core 1.0.1
Using kgio 2.11.0
Using recursive-open-struct 1.0.0
Using netrc 0.11.0
Using mail_room 0.9.1
Using method_source 0.8.2
Using mmap2 2.2.7
Using mousetrap-rails 1.4.6
Using mysql2 0.4.9
Using net-ssh 4.1.0
Using oj 2.17.5
Using rubypants 0.6.0
Using redis 3.3.3
Using rack-cors 0.4.1
Using raindrops 0.19.0
Using rdoc 4.3.0
Using re2 1.1.1
Using redcarpet 3.4.0
Using rinku 2.0.2
Using ruby-prof 0.16.2
Using sexp_processor 4.10.0
Using settingslogic 2.0.9
Using slack-notifier 1.5.1
Using state_machines 0.5.0
Using u2f 0.2.1
Using underscore-rails 1.8.3
Using version_sorter 2.1.0
Using vmstat 2.3.0
Using rainbow 2.2.2
Using tzinfo 1.2.3
Using descendants_tracker 0.0.4
Using nokogiri 1.6.8.1
Using gpgme 2.0.13
Using rack-test 0.6.3
Using warden 1.2.7
Using rack-accept 0.4.5
Using rack-protection 2.0.0
Using rack-attack 4.4.1
Using rack-proxy 0.6.2
Using mail 2.6.6
Using css_parser 1.5.0
Using launchy 2.4.3
Using faraday 0.12.2
Using asciidoctor-plantuml 0.0.7
Using parser 2.4.0.0
Using attr_encrypted 3.0.3
Using autoparse 0.3.3
Using autoprefixer-rails 7.1.2.6
Using chronic_duration 0.10.6
Using rqrcode 0.10.1
Using toml-rb 0.3.15
Using concurrent-ruby-ext 1.0.5
Using sprockets 3.7.1
Using crack 0.4.3
Using select2-rails 3.5.10
Using rblineprof 0.3.7
Using unf 0.1.4
Using gettext_i18n_rails 1.8.0
Using rbnacl 3.4.0
Using sys-filesystem 1.1.7
Using httparty 0.13.7
Using gemojione 3.3.0
Using po_to_json 1.0.1
Using recaptcha 3.4.0
Using uglifier 2.7.2
Using fog-core 1.45.0
Using gemnasium-gitlab-service 0.2.6
Using github-linguist 4.7.6
Using gollum-rugged_adapter 0.4.4
Using licensee 8.7.0
Using gettext 3.2.4
Using logging 2.2.2
Using gitlab-grit 2.8.1
Using omniauth 1.4.2
Using hashie-forbidden_attributes 0.1.1
Using mustermann-grape 1.0.0
Using haml 4.0.7
Using hamlit 2.6.2
Using prometheus-client-mmap 0.7.0.beta13
Using org-ruby 0.9.12
Using redis-store 1.3.0
Using redis-namespace 1.5.3
Using unicorn 5.1.0
Using wikicloth 0.8.1
Using ruby_parser 3.10.1
Using activesupport 4.2.8
Using et-orbi 1.0.5
Using axiom-types 0.1.1
Using coercible 1.0.0
Using loofah 2.0.3
Using sanitize 2.1.0
Using html2text 0.2.0
Using ruby-saml 1.4.3
Using truncato 0.7.8
Using sidekiq 5.0.4
Using premailer 1.10.4
Using faraday_middleware 0.12.2
Using oauth2 1.4.0
Using signet 0.7.3
Using sawyer 0.8.1
Using sentry-raven 2.5.3
Using rubocop 0.49.1
Using bootstrap-sass 3.3.7
Using rqrcode-rails3 0.1.7
Using ruby-fogbugz 0.2.1
Using domain_name 0.5.20170404
Using rbnacl-libsodium 1.0.13
Using flowdock 0.7.1
Using hipchat 1.5.4
Using fog-json 1.0.2
Using fog-xml 0.1.3
Using fog-local 0.3.1
Using gollum-grit_adapter 1.0.1
Using gitlab_omniauth-ldap 2.0.4
Using omniauth-cas3 1.1.3
Using omniauth-oauth 1.1.0
Using omniauth-shibboleth 1.2.1
Using redis-rack 2.0.2
Using unicorn-worker-killer 0.4.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.4.0
Using activemodel 4.2.8
Using html-pipeline 1.11.0
Using json-jwt 1.7.2
Using grape-entity 0.6.0
Using jira-ruby 1.1.3
Using omniauth_crowd 2.2.3
Using rack-oauth2 1.2.3
Using redis-activesupport 5.0.3
Using rufus-scheduler 3.4.2
Using virtus 1.0.5
Using rails-html-sanitizer 1.0.3
Using omniauth-saml 1.7.0
Using sidekiq-limit_fetch 3.4.0
Using faraday_middleware-multi_json 0.0.6
Using omniauth-oauth2 1.4.0
Using googleauth 0.5.3
Using octokit 4.6.2
Using haml_lint 0.26.0
Using http-cookie 1.0.3
Using gitlab-flowdock-git-hook 1.0.1
Using fog-aliyun 0.1.0
Using fog-openstack 0.1.21
Using fog-aws 1.4.0
Using fog-google 0.5.3
Using fog-rackspace 0.1.5
Using gollum-lib 4.2.7
Using omniauth-twitter 1.2.1
Using rails-dom-testing 1.0.8
Using activejob 4.2.8
Using activerecord 4.2.8
Using carrierwave 1.1.0
Using state_machines-activemodel 0.5.0
Using deckar01-task_list 2.0.0
Using sidekiq-cron 0.6.3
Using grape 0.19.2
Using asana 0.6.0
Using omniauth-auth0 1.4.2
Using omniauth-authentiq 0.3.1
Using omniauth-azure-oauth2 0.0.8
Using omniauth-facebook 4.0.0
Using omniauth-github 1.1.2
Using omniauth-gitlab 1.0.2
Using omniauth-google-oauth2 0.4.1
Using omniauth-oauth2-generic 0.2.2
Using grpc 1.4.5 (universal-darwin)
Using google-api-client 0.8.7
Using http 0.9.8
Using rest-client 2.0.2
Using actionview 4.2.8
Using acts-as-taggable-on 4.0.0
Using after_commit_queue 1.3.0
Using default_value_for 3.0.2
Using flipper-active_record 0.10.2
Using kaminari-activerecord 1.0.1
Using paranoia 2.3.1
Using seed-fu 2.3.6
Using validates_hostname 1.0.7
Using state_machines-activerecord 0.4.1
Using grape-route-helpers 2.0.0
Using gitaly 0.26.0
Using kubeclient 2.2.0
Using actionpack 4.2.8
Using kaminari-actionview 1.0.1
Using actionmailer 4.2.8
Using railties 4.2.8
Using sprockets-rails 3.2.0
Using gon 6.1.0
Using redis-actionpack 5.0.1
Using kaminari 1.0.1
Using premailer-rails 1.9.7
Using d3_rails 3.5.17
Using responders 2.4.0
Using doorkeeper 4.2.6
Using font-awesome-rails 4.7.0.2
Using jquery-rails 4.1.1
Using lograge 0.6.0
Using peek 1.0.1
Using rails-i18n 4.0.9
Using webpack-rails 0.9.11
Using rails 4.2.8
Using sass-rails 5.0.6
Using redis-rails 5.0.2
Using devise 4.3.0
Using doorkeeper-openid_connect 1.1.2
Using peek-gc 0.0.2
Using peek-host 1.0.0
Using peek-mysql2 1.1.0
Using peek-performance_bar 1.3.0
Using peek-rblineprof 0.2.0
Using peek-redis 1.2.0
Using peek-sidekiq 1.0.3
Using dropzonejs-rails 0.7.4
Using gettext_i18n_rails_js 1.2.0
Using health_check 2.6.0
Using devise-two-factor 3.0.0
Bundle complete! 221 Gemfile dependencies, 317 gems now installed.
Gems in the groups development, test, postgres, aws and kerberos were not installed.
Bundled gems are installed into ./vendor/bundle.

**Comment by cabinwj** [comment]
why can not import <class:MergeRequest>?
