### ISSUE TITLE
Cannot login as "Standard signin"

### ISSUE THREAD

**Issue by mini13i** [gitlabhq/gitlabhq#10448]
I'm using LDAP auth. I found it was failed to login as administrator using _Standard_ authentication in 9.4.5. So I upgraded to 9.5.4, but still in vain.

I read https://gitlab.com/gitlab-org/gitlab-ce/issues/35447  and disabled ldap auth, tryed to login as administrator again. Then I got 422 response.
```
Started POST "/users/sign_in" for 192.168.13.41 at 2017-09-17 09:56:34 +0900
Processing by SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"login"=>"xxx", "password"=>"[FILTERED]", "remember_me"=>"0"}}
Redirected to http://192.168.0.100/
Completed 302 Found in 211ms (ActiveRecord: 28.9ms)
Started GET "/" for 192.168.0.41 at 2017-09-17 09:56:35 +0900
Processing by RootController#index as HTML
Completed 500 Internal Server Error in 33ms (ActiveRecord: 10.0ms)

ActiveRecord::RecordInvalid (Validation failed: Route path has already been taken, Route is invalid, Name has already been taken):
  app/models/user.rb:834:in `ensure_namespace_correct'
  app/models/concerns/token_authenticatable.rb:53:in `block in add_authentication_token_field'
  app/models/concerns/token_authenticatable.rb:47:in `block in add_authentication_token_field'
  app/models/user.rb:1045:in `rss_token'
  app/helpers/rss_helper.rb:3:in `rss_url_options'
  app/views/dashboard/projects/index.html.haml:5:in `block in _app_views_dashboard_projects_index_html_haml__628667762588527469_70057392817780'
  app/views/dashboard/projects/index.html.haml:4:in `_app_views_dashboard_projects_index_html_haml__628667762588527469_70057392817780'
  app/controllers/dashboard/projects_controller.rb:10:in `index'
  app/controllers/root_controller.rb:16:in `index'
  lib/gitlab/i18n.rb:46:in `with_locale'
  lib/gitlab/i18n.rb:52:in `with_user_locale'
  app/controllers/application_controller.rb:326:in `set_locale'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
```

environment
```
root@bbt-gitlab01:~# gitlab-rake gitlab:env:info

System information
System:		Ubuntu 14.04
Current User:	git
Using RVM:	no
Ruby Version:	2.3.3p222
Gem Version:	2.6.6
Bundler Version:1.13.7
Rake Version:	12.0.0
Redis Version:	3.2.5
Git Version:	2.13.5
Sidekiq Version:5.0.4
Go Version:	unknown

GitLab information
Version:	9.5.4
Revision:	fbffc27
Directory:	/opt/gitlab/embedded/service/gitlab-rails
DB Adapter:	postgresql
URL:		http://192.168.0.100
HTTP Clone URL:	http://192.168.0.100/some-group/some-project.git
SSH Clone URL:	git@192.168.0.100:some-group/some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	5.8.0
Repository storage paths:
- default: 	/var/opt/gitlab/git-data/repositories
Hooks:		/opt/gitlab/embedded/service/gitlab-shell/hooks
Git:		/opt/gitlab/embedded/bin/git
```

I also tried rebuilding authorized_keys file and clearing redis cache, but it didn't succeed too.

**Comment by axilleas** [comment]
@mini13i please open an issue at https://gitlab.com/gitlab-org/gitlab-ce/issues, this tracker is not monitored. Thanks!

**Comment by mini13i** [comment]
Sorry, I mistook the product.
