### ISSUE TITLE
500 Error when submitting Merge Request to upstream repo

### ISSUE THREAD

**Issue by alexdiliberto** [gitlabhq/gitlabhq#6124]
It seems that everytime any of our project members makes a Merge Request to the upstream repo, we keep getting this ```500 Internal Server Error: NoMethodError (undefined method `any?' for false:FalseClass)```
I tried to Submit a merge request from a feature branch on my own Repo into my develop branch on my own repo and that works...but the upstream repo merge request keeps failing.

This issue started for me yesterday afternoon while I had `Gitlab 6.4.3`. I tried some troubleshooting but not luck. I updated to `Gitlab 6.5.0` today and I'm still having the issue and now I'm running out of ideas.

Here' some information from creating the failing Merge Request

production.log

```
Started POST "/ravi/jefferson/merge_requests" for 127.0.0.1 at 2014-01-22 13:49:19 -0500
Processing by Projects::MergeRequestsController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"092TcFuz/qBlqb/wZXVR2hHStXvxNh/mJNEr3Wbrw7Q=", "merge_request"=>{"source_project_id"=>"7", "source_branch"=>"feature/cit-fixes", "target_project_id"=>"1", "target_branch"=>"develop", "title"=>"Feature/Cit Fixes", "description"=>"Minor issue fix in OBSA. \r\nModified forms url so that IDP loads it. \r\nMinor fix with SSO Re-authentication when user refreshes page.\r\nRemoved get session call as we will no longer use it as CSRF challenge token comes along with user-app-status call.\r\nurl chnages for transfer edit,limits. Esign reject popup implemnetation. Wdith added for modal box.\r\nissue fix with limits call not happening.", "assignee_id"=>"", "milestone_id"=>""}, "project_id"=>"ravi/jefferson"}
Completed 500 Internal Server Error in 108ms
NoMethodError (undefined method `any?' for false:FalseClass):
app/models/merge_request.rb:189:in `reloaded_commits'
app/models/merge_request.rb:123:in `reload_code'
app/controllers/projects/merge_requests_controller.rb:79:in `create'
app/controllers/application_controller.rb:57:in `set_current_user_for_thread'
```

ENV Info

```
System information
System:		Mac OS X 10.9
Current User:	git
Using RVM:	no
Ruby Version:	2.0.0p247
Gem Version:	2.2.1
Bundler Version:1.5.2
Rake Version:	10.1.0

GitLab information
Version:	6.5.0
Revision:	51f06ba
Directory:	/Users/git/gitlab
DB Adapter:	mysql2
URL:		http://tux.na.gmacfs.com
HTTP Clone URL:	http://tux.na.gmacfs.com/some-project.git
SSH Clone URL:	git@tux.na.gmacfs.com:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	1.8.0
Repositories:	/Users/git/repositories/
Hooks:		/Users/git/gitlab-shell/hooks/
Git:		/usr/local/bin/git
```

Gitlab Check

```
Checking Environment ...

Git configured for git user? ... yes
Has python2? ... yes
python2 is supported version? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.7.9 ? ... OK (1.8.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
TUX / jefferson ... ok
Rajeev Natarajan / jefferson ... ok
Nathan Hammond / jefferson ... ok
Alex DiLiberto / jefferson ... ok
Sai Senthilnathan / jefferson ... ok
Krishnakumar Natarajan / jefferson ... ok
Ravi Amajala / jefferson ... ok
Srikrishna Dasu / WorkingBase-SKD ... repository is empty
Srikrishna Dasu / jefferson ... ok
Vijay Dhandapani / jefferson ... ok
Deepa Swaminathan / jefferson ... ok
Chidambaram Thirukumara Shunmuganathan / jefferson ... ok
Anand Sakthivel / jefferson ... ok
Mohammed Farook R / jefferson ... ok
Manjunath / jefferson ... ok
Baskaran / jefferson ... ok
Running /Users/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/Users/git/repositories: OK
	/Users/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.4
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... no
  Try fixing it:
  Redownload the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
projects have namespace: ... 
TUX / jefferson ... yes
Rajeev Natarajan / jefferson ... yes
Nathan Hammond / jefferson ... yes
Alex DiLiberto / jefferson ... yes
Sai Senthilnathan / jefferson ... yes
Krishnakumar Natarajan / jefferson ... yes
Ravi Amajala / jefferson ... yes
Srikrishna Dasu / WorkingBase-SKD ... yes
Srikrishna Dasu / jefferson ... yes
Vijay Dhandapani / jefferson ... yes
Deepa Swaminathan / jefferson ... yes
Chidambaram Thirukumara Shunmuganathan / jefferson ... yes
Anand Sakthivel / jefferson ... yes
Mohammed Farook R / jefferson ... yes
Manjunath / jefferson ... yes
Baskaran / jefferson ... yes
Projects have satellites? ... 
TUX / jefferson ... yes
Rajeev Natarajan / jefferson ... yes
Nathan Hammond / jefferson ... yes
Alex DiLiberto / jefferson ... yes
Sai Senthilnathan / jefferson ... yes
Krishnakumar Natarajan / jefferson ... yes
Ravi Amajala / jefferson ... yes
Srikrishna Dasu / WorkingBase-SKD ... can't create, repository is empty
Srikrishna Dasu / jefferson ... yes
Vijay Dhandapani / jefferson ... yes
Deepa Swaminathan / jefferson ... yes
Chidambaram Thirukumara Shunmuganathan / jefferson ... yes
Anand Sakthivel / jefferson ... yes
Mohammed Farook R / jefferson ... yes
Manjunath / jefferson ... yes
Baskaran / jefferson ... yes
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/local/bin/git"
Git version >= 1.7.10 ? ... yes (1.8.5)

Checking GitLab ... Finished
```

Everything here looks normal, like it always does.

Any ideas?

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by brauliobo** [comment]
This problem is happening again: https://gitlab.com/brauliobo/noosfero/merge_requests/new?utf8=%E2%9C%93&merge_request%5Bsource_project_id%5D=14811&merge_request%5Bsource_branch%5D=live-comments&merge_request%5Btarget_project_id%5D=14155&merge_request%5Btarget_branch%5D=master
