### ISSUE TITLE
dashboard/issues 500 error

### ISSUE THREAD

**Issue by topdown** [gitlabhq/gitlabhq#6135]
This page has not worked since the first version I installed.
The last 3 versions give a 500 error. including the latest 6.5.1

--- System information
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
System:		Ubuntu 12.04
Current User:	git
Using RVM:	no
Ruby Version:	2.0.0p247
Gem Version:	2.0.3
Bundler Version:1.3.5
Rake Version:	10.1.0

--- GitLab information
Version:	6.5.1
Revision:	6f6f158
Directory:	/home/git/gitlab
DB Adapter:	mysql2
Using LDAP:	no
Using Omniauth:	no

--- GitLab Shell
Version:	1.8.0
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git

The only issue that comes up with the check rake is git version
``` Git version >= 1.7.10 ? ... no
  Try fixing it:
  Update your git to a version >= 1.7.10 from 1.7.9```

**Comment by psi-4ward** [comment]
Same here on GitLab 7.9.4

```
Started GET "/dashboard/issues?assignee_id=2" for 62.156.51.150 at 2015-04-30 21:44:40 +0200
Processing by DashboardController#issues as HTML
Parameters: {"assignee_id"=>"2"}
Completed 500 Internal Server Error in 309ms
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"projects/issues", :format=>nil, :id=>#<Issue id: 2, title: "tstamp=0 bei create-Abbruch", assignee_id: 2, author_id: 2, project_id: 4, created_at: "2013-04-17 22:14:05", updated_at: "2013-04-17 22:14:05", position: 0, branch_name: nil, description: "Wird einer neuer Datensatz erstellt bekommt er `ts...", milestone_id: nil, state: "opened", iid: nil>, :namespace_id=>#<Group id: 5, name: "MyLocation", path: "mylocation", owner_id: 2, created_at: "2013-01-09 19:29:36", updated_at: "2014-03-14 19:56:15", type: "Group", description: "", avatar: "logo.jpg">, :project_id=>#<Project id: 4, name: "core", path: "core", description: nil, created_at: "2013-01-09 19:30:38", updated_at: "2015-01-15 10:13:46", creator_id: 2, issues_enabled: true, wall_enabled: true, merge_requests_enabled: true, wiki_enabled: true, namespace_id: 5, issues_tracker: "gitlab", issues_tracker_id: nil, snippets_enabled: true, last_activity_at: "2015-01-15 10:13:47", import_url: nil, visibility_level: 0, archived: false, import_status: "none", repository_size: 84.43, star_count: 0, import_type: nil, import_source: nil, avatar: nil>} missing required keys: [:id]):
1: %li{ id: dom_id(issue), class: issue_css_classes(issue), url: issue_path(issue) }
2: - if controller.controller_name == 'issues'
3: .issue-check
4: = check_box_tag dom_id(issue,"selected"), nil, false, 'data-id' => issue.id, class: "selected_issue", disabled: !can?(current_user, :modify_issue, issue)
app/helpers/gitlab_routing_helper.rb:25:in `issue_path'
app/views/projects/issues/_issue.html.haml:1:in `_app_views_projects_issues__issue_html_haml___321207839587622835_96344900'
app/views/shared/_issues.html.haml:11:in `block (2 levels) in _app_views_shared__issues_html_haml__4092443913383353169_94062180'
app/views/shared/_issues.html.haml:10:in `each'
app/views/shared/_issues.html.haml:10:in `block in _app_views_shared__issues_html_haml__4092443913383353169_94062180'
app/views/shared/_issues.html.haml:2:in `each'
app/views/shared/_issues.html.haml:2:in `_app_views_shared__issues_html_haml__4092443913383353169_94062180'
app/views/dashboard/issues.html.haml:10:in `_app_views_dashboard_issues_html_haml__2859425395294946399_112964640'
app/controllers/dashboard_controller.rb:37:in `issues'
```

**Comment by topdown** [comment]
I updated to  7.10.0 and it fixed it. But had a missing migration during update, there is a issue here for that with a fix.

**Comment by Razer6** [comment]
then we clsoe this here

**Comment by agj32mrgibbits** [comment]
How do you fix this without deleting all your history of issues and milestones?
