### ISSUE TITLE
[6.6] Pushes don't show up on project home and dashboard

### ISSUE THREAD

**Issue by moenoel** [gitlabhq/gitlabhq#6561]
Since updating to 6.6, pushes don't show up on project homes and the dashboard for repositories that are lacking a `packed-refs` file. They do, however, appear on the "Commits" tab.

Manually running `git pack-refs` in a repository on the server fixes this for subsequent pushes, but new repositories are not initialized with it.

`sidekiq.log` says the following:

```
2014-03-19T08:42:41Z 56687 TID-r1ls8 PostReceive JID- INFO: start
2014-03-19T08:42:41Z 56687 TID-r1ls8 PostReceive JID- INFO: fail: 0.011 sec
2014-03-19T08:42:41Z 56687 TID-r1ls8 WARN: {"class"=>"PostReceive", "args"=>["/home/git/repositories/moenoel/footest.git", "0000000000000000000000000000000000000000", "2e7fa1f0b367ddaa35321c20632c05615d639216", "refs/heads/master", "key-1"]}
2014-03-19T08:42:41Z 56687 TID-r1ls8 WARN: Failed to open '/home/git/repositories/moenoel/footest.git/packed-refs'
2014-03-19T08:42:41Z 56687 TID-r1ls8 WARN: /home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:57:in `each'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:57:in `each'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:57:in `select'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:57:in `branches'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:52:in `branch_names'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:106:in `discover_default_branch'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/gitlab_git-5.4.0/lib/gitlab_git/repository.rb:29:in `initialize'
/home/git/gitlab/app/models/repository.rb:8:in `new'
/home/git/gitlab/app/models/repository.rb:8:in `initialize'
/home/git/gitlab/app/models/project.rb:177:in `new'
/home/git/gitlab/app/models/project.rb:177:in `repository'
/home/git/gitlab/app/services/git_push_service.rb:21:in `execute'
/home/git/gitlab/app/workers/post_receive.rb:32:in `perform'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/future.rb:14:in `block in new'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/home/git/gitlab/vendor/bundle/ruby/1.9.3/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'
```

Here's my environment (the system is a [SmartOS](http://smartos.org/) zone, i.e. Illumos based):

```
System information
System:         unknown
Current User:   git
Using RVM:      no
Ruby Version:   1.9.3p448
Gem Version:    1.8.23
Bundler Version:1.3.4
Rake Version:   10.1.1

GitLab information
Version:        6.6.5
Revision:       83eb5f3
Directory:      /home/git/gitlab
DB Adapter:     postgresql
URL:            https://gitlab.example.com
HTTP Clone URL: https://gitlab.example.com/some-project.git
SSH Clone URL:  git@gitlab.example.com:some-project.git
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        1.8.5
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /opt/local/bin/git
```

Here's my check output (sidekiq is running, but the rake task doesn't pick that up on SmartOS):

```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.7.9 ? ... OK (1.8.5)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ...

<snip>

Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
  /home/git/repositories: OK
  /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.6.13
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... no
  Try fixing it:
  sudo -u git -H RAILS_ENV=production script/background_jobs start
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  see log/sidekiq.log for possible errors
  Please fix the error above and rerun the checks.

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)

<snip>

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...

<snip>

Redis version >= 2.0.0? ... yes
Your git bin path is "/opt/local/bin/git"
Git version >= 1.7.10 ? ... yes (1.8.3)

Checking GitLab ... Finished
```

**Comment by jvanbaarsen** [comment]
Thanks for the issue report but we only support issues for the latest stable version of GitLab. I'm closing this issue but if you still experience this problem in the latest stable version, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
