### ISSUE TITLE
Error 500 on repo page after git push -tags

### ISSUE THREAD

**Issue by RaD** [gitlabhq/gitlabhq#6730]
```
Started GET "/stm32/fw-can-button" for 188.65.11.244 at 2014-04-09 08:32:30 +0400                                
Processing by ProjectsController#show as HTML                                                                    
  Parameters: {"id"=>"stm32/fw-can-button"}                                                                      
  Rendered projects/_dropdown.html.haml (2.6ms)                                                                  
  Rendered shared/_clone_panel.html.haml (0.4ms)                                                                 
  Rendered projects/_home_panel.html.haml (7.2ms)                                                                
  Rendered projects/show.html.haml within layouts/projects (7.5ms)                                               
Completed 500 Internal Server Error in 43ms                                                                      
                                                                                                                 
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"projects/commits", :id=>nil, :proje
ct_id=>#<Project id: 12, name: "fw-can-button", path: "fw-can-button", description: "�.�.о�.ивка дл�. CAN        
кнопки.", created_at: "2014-04-07 06:30:07", updated_at: "2014-04-07 06:30:07", creator_id: 2, issues_enabl      
ed: true, wall_enabled: false, merge_requests_enabled: true, wiki_enabled: true, namespace_id: 2, issues_tracker:
 "gitlab", issues_tracker_id: nil, snippets_enabled: false, last_activity_at: "2014-04-07 06:30:56", import_url: 
"", visibility_level: 10, archived: false, import_status: "none">, :format=>nil} missing required keys: [:id]):  
    25:     - unless empty_repo                                                                                  
    26:       .col-md-4                                                                                          
    27:         .project-home-links                                                                              
    28:           = link_to pluralize(@repository.round_commit_count, 'commit'), project_commits_path(@project, @
ref || @repository.root_ref)                                                                                     
    29:           = link_to pluralize(@repository.branch_names.count, 'branch'), project_branches_path(@project) 
    30:           = link_to pluralize(@repository.tag_names.count, 'tag'), project_tags_path(@project)           
    31:           %span.light.prepend-left-20= repository_size                                                   
  app/views/projects/_home_panel.html.haml:28:in `_app_views_projects__home_panel_html_haml__3106913531589346741_
46340880'                                                                                                        
  app/views/projects/show.html.haml:1:in `_app_views_projects_show_html_haml___1613902615247756740_46025340'
  app/controllers/projects_controller.rb:69:in `block (2 levels) in show'
  app/controllers/projects_controller.rb:63:in `show'
  app/controllers/application_controller.rb:58:in `set_current_user_for_thread'
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
