### ISSUE TITLE
Mass of email notifications in push service when using invalid email adress

### ISSUE THREAD

**Issue by jorinkl** [gitlabhq/gitlabhq#6977]
When adding some email adresses to Email On Push Service, and one is invalid and gives no response, gitlab is sending the notification email over and over again to all recipients.

sidekiq.log:

```
2014-05-14T20:57:28Z 2478 TID-1dg8h0 EmailsOnPushWorker JID-080087567dda6bcdcd1116b5 INFO: start
2014-05-14T20:57:29Z 2478 TID-1dg8h0 EmailsOnPushWorker JID-080087567dda6bcdcd1116b5 INFO: fail: 1.313 sec
2014-05-14T20:57:29Z 2478 TID-1dg8h0 WARN: {"retry"=>true, "queue"=>"default", "class"=>"EmailsOnPushWorker" [EmailAdressesCensored], "args"=> "jid"=>"080087567dda6bcdcd1116b5", "enqueued_at"=>1399970527.2419593, "error_message"=>"550 5.2.1 user disabled; cannot receive new mail: invalidmail@invaild.com\n", "error_class"=>"Net::SMTPFatalError", "failed_at"=>"2014-05-13T08:42:08Z", "retry_count"=>15, "retried_at"=>2014-05-14 20:57:29 UTC}
2014-05-14T20:57:29Z 2478 TID-1dg8h0 WARN: 550 5.2.1 user disabled; cannot receive new mail: u.kadelka@ostfalia.de
2014-05-14T20:57:29Z 2478 TID-1dg8h0 WARN: /opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:949:in `check_response'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:918:in `getok'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:861:in `rcptto'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:842:in `block in rcptto_list'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:840:in `each'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:840:in `rcptto_list'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:661:in `send_message'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:113:in `block in deliver!'
/opt/bitnami/ruby/lib/ruby/1.9.1/net/smtp.rb:521:in `start'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/mail-2.5.4/lib/mail/message.rb:232:in `block in deliver'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/actionmailer-4.0.3/lib/action_mailer/base.rb:456:in `block in deliver_mail'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.3/lib/active_support/notifications.rb:159:in `block in instrument'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/activesupport-4.0.3/lib/active_support/notifications.rb:159:in `instrument'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/actionmailer-4.0.3/lib/action_mailer/base.rb:454:in `deliver_mail'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/mail-2.5.4/lib/mail/message.rb:232:in `deliver'
/opt/bitnami/apps/gitlab/htdocs/app/workers/emails_on_push_worker.rb:22:in `block in perform'
/opt/bitnami/apps/gitlab/htdocs/app/workers/emails_on_push_worker.rb:21:in `each'
/opt/bitnami/apps/gitlab/htdocs/app/workers/emails_on_push_worker.rb:21:in `perform'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/future.rb:14:in `block in new'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/opt/bitnami/apps/gitlab/htdocs/vendor/bundle/ruby/1.9.1/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create' 
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
