### ISSUE TITLE
Push webhook expired with some errors.

### ISSUE THREAD

**Issue by crocket** [gitlabhq/gitlabhq#6997]
* Environment
    * Gitlab 6.6.5
    * Gitlab Shell 1.8.5
    * Gitlab API v3
    * Ruby 2.0.0p353
    * Rails 4.0.3
    * Git 1.8.4.1

push webhook failed with the errors below.

```
2014-05-19T07:09:48Z 1596 TID-oxrflw3sw WARN: {"retry"=>true, "queue"=>"project_web_hook", "class"=>"ProjectWebHookWorker", "args"=>[1, {"before"=>"ee89bc62c8d303d352c5a41877f31c0cd790896a", "after"=>"6920e185d41631c97f48eea57bb4e759eaff4660", "ref"=>"refs/heads/master", "user_id"=>4, "user_name"=>"XXXX", "project_id"=>1, "repository"=>{"name"=>"webmail", "url"=>"git@gitlab.synap.co.kr:webmail/webmail.git", "description"=>"XXXXXX", "homepage"=>"https://gitlab.synap.co.kr/webmail/webmail"}, "commits"=>[{"id"=>"f0ae9073502ba62a15877376af693daaf78edbf9", "message"=>"WEBMAIL-426: Contact auto updated when firstname is not the id part of email", "timestamp"=>"2014-05-16T16:58:47+09:00", "url"=>"https://gitlab.synap.co.kr/webmail/webmail/commit/f0ae9073502ba62a15877376af693daaf78edbf9", "author"=>{"name"=>"가나다", "email"=>"XXX@XXX.co.kr"}}, {"id"=>"c0f98db126990be0a68aacb703029c332dafccd8", "message"=>"WEBMAIL-426: Contact name not added if first name is the id part of email", "timestamp"=>"2014-05-16T18:56:35+09:00", "url"=>"https://gitlab.synap.co.kr/webmail/webmail/commit/c0f98db126990be0a68aacb703029c332dafccd8", "author"=>{"name"=>"가나다", "email"=>"XXX@XXX.co.kr"}}, {"id"=>"6920e185d41631c97f48eea57bb4e759eaff4660", "message"=>" Merge branch 'WEBMAIL-426' into 'master'\n\nWEBMAIL-426: Contact name when first name is the id part of email\n\n주소록 자동 저장/수정시에 이름이 없거나 이름이 id와 같은 경우 처리.\n수신자 자동완성에 영향을 줌.", "timestamp"=>"2014-05-19T11:32:21+09:00", "url"=>"https://gitlab.synap.co.kr/webmail/webmail/commit/6920e185d41631c97f48eea57bb4e759eaff4660", "author"=>{"name"=>"XXX", "email"=>"XXX@XXX.co.kr"}}], "total_commits_count"=>3}], "jid"=>"db99f838813a79ac5494d2c4", "enqueued_at"=>1400466742.2531354, "error_message"=>"execution expired", "error_class"=>"Net::OpenTimeout", "failed_at"=>"2014-05-19T02:32:37Z", "retry_count"=>10, "retried_at"=>2014-05-19 07:09:48 UTC}

2014-05-19T07:09:48Z 1596 TID-oxrflw3sw WARN: execution expired

2014-05-19T07:09:48Z 1596 TID-oxrflw3sw WARN: /usr/local/lib/ruby/2.0.0/net/http.rb:878:in `initialize'

/usr/local/lib/ruby/2.0.0/net/http.rb:878:in `open'

/usr/local/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'

/usr/local/lib/ruby/2.0.0/net/http.rb:877:in `connect'

/usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'

/usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'

/usr/local/lib/ruby/2.0.0/net/http.rb:1367:in `request'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/httparty-0.12.0/lib/httparty/request.rb:93:in `perform'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/httparty-0.12.0/lib/httparty.rb:486:in `perform_request'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/httparty-0.12.0/lib/httparty.rb:439:in `post'

/data/gitlab/gitlab/app/models/web_hook.rb:31:in `execute'

/data/gitlab/gitlab/app/workers/project_web_hook_worker.rb:7:in `perform'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:86:in `do_defer'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:37:in `process'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'

/data/gitlab/gitlab/vendor/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
