### ISSUE TITLE
500 Error on repo page.

### ISSUE THREAD

**Issue by jackyyf** [gitlabhq/gitlabhq#7133]
I have recently upgrade gitlab 6.6 to 6.9, after upgrade, all page works fine except repo page, which generates 500 error. Also empty repo is not affected.

production.log:

    Started GET "/jackyyf/paste-py" for 2604:4300:a:6f:dead:beef:bad:cafe at 2014-06-14 21:07:19 +0800
    Processing by ProjectsController#show as HTML
      Parameters: {"id"=>"jackyyf/paste-py"}
    Completed 500 Internal Server Error in 247ms
    
    ActionView::Template::Error (undefined method `split' for nil:NilClass):
        39:         = link_to project_compare_index_path(@project, from: @repository.root_ref, to: @ref || @repository.root_ref), class: 'btn btn-block' do
        40:           Compare code
        41: 
        42:         - if @repository.readme
        43:           - readme = @repository.readme
        44:           = link_to project_blob_path(@project, tree_join(@repository.root_ref, readme.name)), class: 'btn btn-block' do
        45:             = readme.name
      app/models/repository.rb:27:in `commit'
      app/models/repository.rb:178:in `head_commit'
      app/models/repository.rb:183:in `tree'
      app/models/repository.rb:167:in `block in readme'
      app/models/repository.rb:166:in `readme'
      app/views/projects/show.html.haml:42:in `_app_views_projects_show_html_haml___1466467763242360028_42905500'
      app/controllers/projects_controller.rb:69:in `block (2 levels) in show'
      app/controllers/projects_controller.rb:63:in `show'
      app/controllers/application_controller.rb:59:in `set_current_user_for_thread'

rake gitlab:env:info
```
System information
System:
Current User:   git
Using RVM:      no
Ruby Version:   1.9.3p194
Gem Version:    1.8.23
Bundler Version:1.5.3
Rake Version:   10.3.1
Sidekiq Version:2.17.0

GitLab information
Version:        6.9.2
Revision:       e46b644
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            https://git.orzserver.org
HTTP Clone URL: https://git.orzserver.org/some-project.git
SSH Clone URL:  git@git.orzserver.org:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.4
Repositories:   /home/git/repo/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

rake gitlab:check
```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 1.9.4 ? ... OK (1.9.4)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
update hook up-to-date? ... yes
update hooks in repos are links: ... 
Yifu Yu / RenRenRP ... ok
Wine Mirror / WineGecko ... ok
kernel panic / TATClient ... ok
htc550605125 / RealmOfMusic ... ok
Fudan STU / InfoFudan ... ok
Fudan STU / AuthGW ... ok
陈钧衍 / AuthGW ... ok
Fudan STU / Weixin ... ok
jxzhang / Weixin ... ok
Fudan STU / Sandbox ... ok
dingshu / wordpress_php ... ok
Quill Qian / AuthGW ... ok
Fudan STU / Dandu ... ok
Yifu Yu / NoBooM ... ok
johnson-li / Dandu ... ok
PTDev / pt-next ... repository is empty
Quill Qian / Zizhao ... ok
jxzhang / AuthGW ... ok
Quill Qian / csv2json Temp ... ok
Yifu Yu / Someone Project ... ok
OrzDev / Osu Mirror ... repository is empty
Indeed / osu Beatmaps Mirror Site ... ok
单昱 / EventsCrawlers ... ok
Neo Zhang / EventsCrawlers ... ok
Yifu Yu / CE-Pre ... ok
Yifu Yu / Weixin ... ok
Fudan STU / Hongtan2014 ... ok
illusate / Dandu ... ok
OrzDev / pdnsd-orznet ... ok
htc550605125 / scripts ... ok
htc550605125 / pogs ... ok
Fudan STU / ShidaVote ... ok
PTDev / PT Tracker ... ok
rapidhere / blog ... ok
Zhenbo Li / pdfium ... ok
Yifu Yu / cibic ... ok
Yifu Yu / STU-Pre ... ok
yuealves / sweepRobot ... repository is empty
Yifu Yu / paste.py ... ok
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
        /home/git/repo/: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.10
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... no
  Try fixing it:
  Redownload the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
projects have namespace: ... 
Yifu Yu / RenRenRP ... yes
Wine Mirror / WineGecko ... yes
kernel panic / TATClient ... yes
htc550605125 / RealmOfMusic ... yes
Fudan STU / InfoFudan ... yes
Fudan STU / AuthGW ... yes
陈钧衍 / AuthGW ... yes
Fudan STU / Weixin ... yes
jxzhang / Weixin ... yes
Fudan STU / Sandbox ... yes
dingshu / wordpress_php ... yes
Quill Qian / AuthGW ... yes
Fudan STU / Dandu ... yes
Yifu Yu / NoBooM ... yes
johnson-li / Dandu ... yes
PTDev / pt-next ... yes
Quill Qian / Zizhao ... yes
jxzhang / AuthGW ... yes
Quill Qian / csv2json Temp ... yes
Yifu Yu / Someone Project ... yes
OrzDev / Osu Mirror ... yes
Indeed / osu Beatmaps Mirror Site ... yes
单昱 / EventsCrawlers ... yes
Neo Zhang / EventsCrawlers ... yes
Yifu Yu / CE-Pre ... yes
Yifu Yu / Weixin ... yes
Fudan STU / Hongtan2014 ... yes
illusate / Dandu ... yes
OrzDev / pdnsd-orznet ... yes
htc550605125 / scripts ... yes
htc550605125 / pogs ... yes
Fudan STU / ShidaVote ... yes
PTDev / PT Tracker ... yes
rapidhere / blog ... yes
Zhenbo Li / pdfium ... yes
Yifu Yu / cibic ... yes
Yifu Yu / STU-Pre ... yes
yuealves / sweepRobot ... yes
Yifu Yu / paste.py ... yes
Projects have satellites? ... 
Yifu Yu / RenRenRP ... yes
Wine Mirror / WineGecko ... yes
kernel panic / TATClient ... yes
htc550605125 / RealmOfMusic ... yes
Fudan STU / InfoFudan ... yes
Fudan STU / AuthGW ... yes
陈钧衍 / AuthGW ... yes
Fudan STU / Weixin ... yes
jxzhang / Weixin ... yes
Fudan STU / Sandbox ... yes
dingshu / wordpress_php ... yes
Quill Qian / AuthGW ... yes
Fudan STU / Dandu ... yes
Yifu Yu / NoBooM ... yes
johnson-li / Dandu ... yes
PTDev / pt-next ... can't create, repository is empty
Quill Qian / Zizhao ... yes
jxzhang / AuthGW ... yes
Quill Qian / csv2json Temp ... yes
Yifu Yu / Someone Project ... yes
OrzDev / Osu Mirror ... can't create, repository is empty
Indeed / osu Beatmaps Mirror Site ... yes
单昱 / EventsCrawlers ... yes
Neo Zhang / EventsCrawlers ... yes
Yifu Yu / CE-Pre ... yes
Yifu Yu / Weixin ... yes
Fudan STU / Hongtan2014 ... yes
illusate / Dandu ... yes
OrzDev / pdnsd-orznet ... yes
htc550605125 / scripts ... yes
htc550605125 / pogs ... yes
Fudan STU / ShidaVote ... yes
PTDev / PT Tracker ... yes
rapidhere / blog ... yes
Zhenbo Li / pdfium ... yes
Yifu Yu / cibic ... yes
Yifu Yu / STU-Pre ... yes
yuealves / sweepRobot ... can't create, repository is empty
Yifu Yu / paste.py ... yes
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)

Checking GitLab ... Finished
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
