### ISSUE TITLE
"undefined method `head_commit' for nil:NilClass" on new merge request email

### ISSUE THREAD

**Issue by boeserwolf91** [gitlabhq/gitlabhq#7227]
I'm using the newest GitLab 7.0.0 d1e424b

I got the following error while GitLab was trying to send an email because a new merge request was created. The error only occurred by that merge request. Every other worked fine.  

```
2014-06-28T21:53:26Z 401 TID-1q4sag Sidekiq::Extensions::DelayedMailer JID-e9afe6138b1bc80d473fb778 INFO: start
2014-06-28T21:53:26Z 401 TID-1q4sag Sidekiq::Extensions::DelayedMailer JID-e9afe6138b1bc80d473fb778 INFO: fail: 0.107 sec
2014-06-28T21:53:26Z 401 TID-1q4sag WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'Notify'\n- :send\n- - new_merge_request_email\n - 16\n - 30\n"], "jid"=>"e9afe6138b1bc80d473fb778", "enqueued_at"=>1403788505.1865382, "error_message"=>"undefined method `head_commit' for nil:NilClass", "error_class"=>"ActionView::Template::Error", "failed_at"=>"2014-06-26 13:15:17 UTC", "retry_count"=>16, "retried_at"=>2014-06-28 21:53:26 UTC}
2014-06-28T21:53:26Z 401 TID-1q4sag WARN: undefined method `head_commit' for nil:NilClass
2014-06-28T21:53:26Z 401 TID-1q4sag WARN: /home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:173:in `current_sha'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:158:in `file_exists?'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:149:in `path_with_ref'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:110:in `rebuild_path'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:66:in `block in create_relative_links'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:65:in `each'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:65:in `create_relative_links'
/home/git/gitlab/lib/redcarpet/render/gitlab_html.rb:48:in `postprocess'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:51:in `render'
/home/git/gitlab/app/helpers/gitlab_markdown_helper.rb:51:in `markdown'
/home/git/gitlab/app/views/notify/new_merge_request_email.html.haml:9:in `_app_views_notify_new_merge_request_email_html_haml___583526241_101366050'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/template.rb:145:in `block in render'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/template.rb:339:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/template.rb:143:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:17:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:99:in `_render_template'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:82:in `render_to_body'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/rendering.rb:25:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:847:in `block in collect_responses'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:861:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:861:in `each_template'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:843:in `collect_responses'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:774:in `mail'
/home/git/gitlab/app/mailers/emails/merge_requests.rb:8:in `new_merge_request_email'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:189:in `process_action'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:136:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:30:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:580:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:577:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:568:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:551:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:551:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:86:in `do_defer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:37:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
