### ISSUE TITLE
when I get a commit, I get  a 500 error unexpect

### ISSUE THREAD

**Issue by JohnSmithX** [gitlabhq/gitlabhq#7371]
production.log
```
Started GET "/root/vbtest/commit/24f6f92dfb7e0dcfc68aa35332265f5334ef9938" for 121.239.33.196 at 2014-07-25 19:21:14 +0800
Processing by Projects::CommitController#show as HTML
  Parameters: {"project_id"=>"root/vbtest", "id"=>"24f6f92dfb7e0dcfc68aa35332265f5334ef9938"}
Completed 500 Internal Server Error in 6273ms

ActionView::Template::Error (wrong argument type nil (expected String)):
    1: - file = project.repository.blob_at(@commit.id, diff.new_path)
    2: - file = project.repository.blob_at(@commit.parent_id, diff.old_path) unless file
    3: - return unless file
    4: .diff-file{id: "diff-#{i}"}
    5:   .diff-header{id: "file-path-#{hexdigest(diff.new_path || diff.old_path)}"}
  app/models/repository.rb:147:in `method_missing'
  app/models/repository.rb:157:in `blob_at'
  app/views/projects/commits/_diff_file.html.haml:2:in `_app_views_projects_commits__diff_file_html_haml__425067498892949474_48540220'
  app/views/projects/commits/_diffs.html.haml:16:in `block in _app_views_projects_commits__diffs_html_haml__1639109970573993286_22077700'
  app/views/projects/commits/_diffs.html.haml:15:in `each'
  app/views/projects/commits/_diffs.html.haml:15:in `each_with_index'
  app/views/projects/commits/_diffs.html.haml:15:in `_app_views_projects_commits__diffs_html_haml__1639109970573993286_22077700'
  app/views/projects/commit/show.html.haml:2:in `_app_views_projects_commit_show_html_haml__3340627707867217241_35864040'
  app/controllers/projects/commit_controller.rb:39:in `show'
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
