### ISSUE TITLE
Test webhook error: 500

### ISSUE THREAD

**Issue by abdullah-git** [gitlabhq/gitlabhq#7447]
I am trying to do a transaction on Stripe via my application but not getting Stripe events which was working perfectly earlier. Then I try to test via Stripe dashboard but getting this exception on server,  and it say "Test webhook error: 500" on Stripe dashboard.Is this Stripe's end issue or something wrong at my side?

```
2014-08-06 05:55:56,561 [http-8080-12] ERROR errors.GrailsExceptionResolver  - InvalidRequestException occurred when processing request: [POST] /webHookUrl
No such event: evt_00000000000000. Stacktrace follows:
com.stripe.exception.InvalidRequestException: No such event: evt_00000000000000
	at com.stripe.net.APIResource.handleAPIError(APIResource.java:418)
	at com.stripe.net.APIResource._request(APIResource.java:404)
	at com.stripe.net.APIResource.request(APIResource.java:342)
	at com.stripe.model.Event.retrieve(Event.java:36)
	at com.stripe.model.Event.retrieve(Event.java:24)
	at com.cvsurgeon.PaymentService.stripeEventsViaWebHook(PaymentService.groovy:402)
	at com.cvsurgeon.UserPaymentController.webHookEventsViaStripe(UserPaymentController.groovy:1116)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.lang.Thread.run(Thread.java:662)
```

**Comment by Razer6** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the [GitLab.com issue tracker][https://gitlab.com/gitlab-org/gitlab-ce/issues]. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker][https://gitlab.com/gitlab-org/gitlab-ce/issues].
