### ISSUE TITLE
add "cas" to gitlab get error ould not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by webluoye** [gitlabhq/gitlabhq#7567]
https://github.com/gitlabhq/gitlab-public-wiki/wiki/Custom-omniauth-provider-configurations#working-cas-configuration

Restart GitLab  get error in /var/log/gitlab/unicorn/current

```
2014-08-22_03:29:36.82146 /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
2014-08-22_03:29:36.82161 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `map!'
2014-08-22_03:29:36.82164 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `materialize'
2014-08-22_03:29:36.82167 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/definition.rb:133:in `specs'
2014-08-22_03:29:36.82169 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/definition.rb:178:in `specs_for'
2014-08-22_03:29:36.82172 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/definition.rb:167:in `requested_specs'
2014-08-22_03:29:36.82175 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/environment.rb:18:in `requested_specs'
2014-08-22_03:29:36.82177 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:13:in `setup'
2014-08-22_03:29:36.82182 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler.rb:119:in `setup'
2014-08-22_03:29:36.82185 	from /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/bundler-1.5.3/lib/bundler/setup.rb:17:in `<top (required)>'
2014-08-22_03:29:36.82188 	from /opt/gitlab/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2014-08-22_03:29:36.82191 	from /opt/gitlab/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require
```
how to solve
tks.

**Comment by Razer6** [comment]
This is likely due to a RVM installation, which is not supported.
