### ISSUE TITLE
gitlab push error with ssh public keys

### ISSUE THREAD

**Issue by xiqingongzi** [gitlabhq/gitlabhq#7926]
i use ssh public keys to auth my git project .
but when i want to upload my project .i got a error
just like this 
```
opt/gitlab/ruby/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Address family not supported by protocol - socket(2) (Errno::EAFNOSUPPORT)
	from /opt/gitlab/ruby/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /opt/gitlab/ruby/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /opt/gitlab/ruby/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /opt/gitlab/ruby/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /opt/gitlab/ruby/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /opt/gitlab/ruby/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /opt/gitlab/apps/gitlab/gitlab-shell/lib/gitlab_net.rb:97:in `post'
	from /opt/gitlab/apps/gitlab/gitlab-shell/lib/gitlab_net.rb:27:in `allowed?'
	from /opt/gitlab/apps/gitlab/gitlab-shell/lib/gitlab_shell.rb:64:in `validate_access'
	from /opt/gitlab/apps/gitlab/gitlab-shell/lib/gitlab_shell.rb:25:in `exec'
	from /opt/gitlab/apps/gitlab/gitlab-shell/bin/gitlab-shell:16:in `<main>'
fatal: The remote end hung up unexpectedly
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
