### ISSUE TITLE
[7.3.2] Could not find RedCloth-4.2.9 in any of the sources

### ISSUE THREAD

**Issue by bbodenmiller** [gitlabhq/gitlabhq#8045]
Using GitLab 7.3.2 (f092e53) I'm not able to push over HTTPS to my Git endpoint on a new or existing repo. Previously this worked fine on 7.1 before I followed the upgrade guides. When I attempt to push I get the following output:

```
$ git push
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 522 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/spec_set.r
b:92:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sour
ces (Bundler::GemNotFound)
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/spec_set.rb:85:in `map!'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/spec_set.rb:85:in `materialize'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/definition.rb:133:in `specs'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/definition.rb:178:in `specs_for'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/definition.rb:167:in `requested_specs'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/environment.rb:18:in `requested_specs'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/runtime.rb:13:in `setup'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er.rb:120:in `setup'
remote:         from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundl
er/setup.rb:17:in `<top (required)>'
remote:         from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `requi
re'
remote:         from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `requi
re'
To https://gitlab-dev.website.com/someone/gitlab-dev-test.git
 ! [remote rejected] temp -> temp (pre-receive hook declined)
error: failed to push some refs to 'https://gitlab-dev.website.com/someone/gitlab-dev-test.git'
```

Checks:

```
$ sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production SANITIZE=true
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.0.1 ? ... OK (2.0.1)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ...
2/1 ... repository is empty
2/2 ... ok
2/3 ... repository is empty
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /home/git/repositories: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.4
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...
2/1 ... yes
2/2 ... yes
2/3 ... yes
Projects have satellites? ...
2/1 ... yes
2/2 ... yes
2/3 ... can't create, repository is empty
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.2)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.1)

Checking GitLab ... Finished
```

```
$ sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.

System information
System:         Ubuntu 14.04
Current User:   git
Using RVM:      no
Ruby Version:   2.1.2p95
Gem Version:    2.2.2
Bundler Version:1.6.5
Rake Version:   10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:        7.3.2
Revision:       f092e53
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            https://gitlab-dev.website.com
HTTP Clone URL: https://gitlab-dev.website.com/some-project.git
SSH Clone URL:  git@gitlab-dev.website.com:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        2.0.1
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

```
$ sudo -u git -H bundle list
Gems included by the bundle:
  * RedCloth (4.2.9)
  * ace-rails-ap (2.0.1)
  * actionmailer (4.1.1)
  * actionpack (4.1.1)
  * actionview (4.1.1)
  * activemodel (4.1.1)
  * activerecord (4.1.1)
  * activesupport (4.1.1)
  * acts-as-taggable-on (2.4.1)
  * arel (5.0.1.20140414130214)
  * asciidoctor (0.1.4)
  * axiom-types (0.0.5)
  * bcrypt (3.1.7)
  * bootstrap-sass (3.0.3.0)
  * builder (3.2.2)
  * bundler (1.6.5)
  * carrierwave (0.9.0)
  * celluloid (0.15.2)
  * charlock_holmes (0.6.9.4)
  * coercible (1.0.0)
  * coffee-rails (4.0.1)
  * coffee-script (2.2.0)
  * coffee-script-source (1.6.3)
  * colored (1.2)
  * connection_pool (1.2.0)
  * creole (0.3.8)
  * d3_rails (3.1.10)
  * default_value_for (3.0.0)
  * descendants_tracker (0.0.3)
  * devise (3.2.4)
  * devise-async (0.9.0)
  * diff-lcs (1.2.5)
  * diffy (3.0.3)
  * dotenv (0.9.0)
  * dropzonejs-rails (0.4.14)
  * emoji (1.0.1)
  * enumerize (0.7.0)
  * equalizer (0.0.8)
  * erubis (2.7.0)
  * escape_utils (0.2.4)
  * eventmachine (1.0.3)
  * excon (0.32.1)
  * execjs (2.0.2)
  * expression_parser (0.9.0)
  * faraday (0.8.9)
  * faraday_middleware (0.9.0)
  * fog (1.21.0)
  * fog-brightbox (0.0.1)
  * fog-core (1.21.1)
  * fog-json (1.0.0)
  * font-awesome-rails (3.2.1.3)
  * foreman (0.63.0)
  * formatador (0.2.4)
  * gemnasium-gitlab-service (0.2.2)
  * github-markup (1.1.0)
  * gitlab-flowdock-git-hook (0.4.2.2)
  * gitlab-grack (2.0.0.pre)
  * gitlab-grit (2.6.11)
  * gitlab-linguist (3.0.0)
  * gitlab_emoji (0.0.1.1)
  * gitlab_git (6.2.1)
  * gitlab_meta (7.0)
  * gitlab_omniauth-ldap (1.1.0)
  * gollum-lib (3.0.0)
  * gon (5.0.1)
  * grape (0.6.1)
  * grape-entity (0.4.2)
  * haml (4.0.5)
  * haml-rails (0.5.3)
  * hashie (2.1.2)
  * hike (1.2.3)
  * hipchat (0.14.0)
  * http_parser.rb (0.5.3)
  * httparty (0.13.0)
  * httpauth (0.2.1)
  * i18n (0.6.11)
  * ice_nine (0.10.0)
  * jquery-atwho-rails (0.3.3)
  * jquery-rails (3.1.0)
  * jquery-scrollto-rails (1.4.3)
  * jquery-turbolinks (2.0.1)
  * jquery-ui-rails (4.2.1)
  * json (1.8.1)
  * jwt (0.1.13)
  * kaminari (0.15.1)
  * kgio (2.8.1)
  * libv8 (3.16.14.3)
  * mail (2.5.4)
  * mime-types (1.25.1)
  * mini_portile (0.6.0)
  * minitest (5.3.5)
  * mousetrap-rails (1.4.6)
  * multi_json (1.10.1)
  * multi_xml (0.5.5)
  * multipart-post (1.2.0)
  * mysql2 (0.3.16)
  * net-ldap (0.7.0)
  * net-scp (1.1.2)
  * net-ssh (2.8.0)
  * newrelic_rpm (3.9.4.245)
  * nokogiri (1.6.2.1)
  * nprogress-rails (0.1.2.3)
  * oauth (0.4.7)
  * oauth2 (0.8.1)
  * omniauth (1.1.4)
  * omniauth-github (1.1.1)
  * omniauth-google-oauth2 (0.2.5)
  * omniauth-oauth (1.0.1)
  * omniauth-oauth2 (1.1.1)
  * omniauth-shibboleth (1.1.1)
  * omniauth-twitter (1.0.1)
  * org-ruby (0.9.8)
  * orm_adapter (0.5.0)
  * polyglot (0.3.4)
  * posix-spawn (0.3.9)
  * pyu-ruby-sasl (0.0.3.3)
  * rack (1.5.2)
  * rack-accept (0.4.5)
  * rack-attack (2.3.0)
  * rack-cors (0.2.9)
  * rack-mount (0.8.3)
  * rack-protection (1.5.1)
  * rack-test (0.6.2)
  * rails (4.1.1)
  * rails_autolink (1.1.6)
  * railties (4.1.1)
  * raindrops (0.12.0)
  * rake (10.3.2)
  * raphael-rails (2.1.2)
  * rdoc (3.12.2)
  * redcarpet (3.1.2)
  * redis (3.0.6)
  * redis-actionpack (4.0.0)
  * redis-activesupport (4.0.0)
  * redis-namespace (1.4.1)
  * redis-rack (1.5.0)
  * redis-rails (4.0.0)
  * redis-store (1.1.4)
  * ref (1.0.5)
  * request_store (1.0.5)
  * rinku (1.7.3)
  * rouge (1.3.3)
  * rubyntlm (0.1.1)
  * rubypants (0.2.0)
  * rugged (0.21.0)
  * sanitize (2.1.0)
  * sass (3.2.19)
  * sass-rails (4.0.3)
  * seed-fu (2.3.1)
  * select2-rails (3.5.2)
  * semantic-ui-sass (0.16.1.0)
  * settingslogic (2.0.9)
  * sidekiq (2.17.0)
  * simple_oauth (0.1.9)
  * sinatra (1.4.4)
  * six (0.2.0)
  * slack-notifier (0.3.2)
  * slim (2.0.2)
  * sprockets (2.11.0)
  * sprockets-rails (2.1.3)
  * stamp (0.5.0)
  * state_machine (1.2.0)
  * stringex (2.5.1)
  * temple (0.6.7)
  * therubyracer (0.12.0)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * timers (1.1.0)
  * tinder (1.9.3)
  * treetop (1.4.15)
  * turbolinks (2.0.0)
  * twitter-stream (0.1.16)
  * tzinfo (1.2.2)
  * uglifier (2.3.2)
  * underscore-rails (1.4.4)
  * unf (0.1.4)
  * unf_ext (0.0.6)
  * unicorn (4.6.3)
  * unicorn-worker-killer (0.4.2)
  * version_sorter (1.1.0)
  * virtus (1.0.1)
  * warden (1.2.3)
  * wikicloth (0.8.1)
```

**Comment by setola** [comment]
@cirosantilli it seems [your commit] (https://gitlab.com/cirosantilli/gitlab-shell/commit/660f1113775cd4e797eb4d31ff51eaec6ec2fa66) has been [rolled back]
(https://gitlab.com/gitlab-org/gitlab-shell/commit/4157d523994b2fae7908cb93b4e78ee1db763ce7)

I've applied your commit to gitlab shell v2.4.1 and it works.
Does anyone knows if there is a way to make the official commit work?

**Comment by cirosantilli** [comment]
@setola that was updated at https://github.com/gitlabhq/gitlab-shell/pull/199 because before it didn't work for SSH, but I don't have the time anymore to test it so it was closed.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
