### ISSUE TITLE
Redis::TimeoutError & IO::EAGAINWaitReadable on rake assets:clean assets:precompile cache:clear RAILS_ENV=production

### ISSUE THREAD

**Issue by bbodenmiller** [gitlabhq/gitlabhq#8059]
Getting an error when attempting to clear my assets as part of the 7.1->7.2 upgrade:

```
$ sudo -u git -H bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.en          force_available_locales = false to avoid this message.
rake aborted!
Redis::TimeoutError: Connection timed out
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:210:in `rescue in io'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:208:in `io'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:216:in `read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:84:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:189:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:297:in `ensure_connected'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:179:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:258:in `logging'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:178:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:84:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:435:in `block in keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `block in synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:434:in `keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:29:in `block in keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:50:in `namespace'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:29:in `keys'
/home/git/gitlab/lib/tasks/cache.rake:7:in `block (2 levels) in <top (required)>'
Redis::TimeoutError: Redis::TimeoutError
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:55:in `rescue in _read_from_socket'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:48:in `_read_from_socket'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:41:in `gets'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:242:in `read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:217:in `block in read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:208:in `io'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:216:in `read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:84:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:189:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:297:in `ensure_connected'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:179:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:258:in `logging'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:178:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:84:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:435:in `block in keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `block in synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:434:in `keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:29:in `block in keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:50:in `namespace'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:29:in `keys'
/home/git/gitlab/lib/tasks/cache.rake:7:in `block (2 levels) in <top (required)>'
IO::EAGAINWaitReadable: Resource temporarily unavailable - read would block
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:41:in `gets'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/connection/ruby.rb:242:in `read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:217:in `block in read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:208:in `io'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:216:in `read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:84:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:189:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:297:in `ensure_connected'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:179:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:258:in `logging'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:178:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis/client.rb:84:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:435:in `block in keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `block in synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:36:in `synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.0.6/lib/redis.rb:434:in `keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:29:in `block in keys'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:50:in `namespace'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:29:in `keys'
/home/git/gitlab/lib/tasks/cache.rake:7:in `block (2 levels) in <top (required)>'
Tasks: TOP => cache:clear
(See full trace by running task with --trace)
```

GitLab appears to be working fine from what I can tell. I've attempted to reboot my system and it does not appear I have a shortage of memory or CPU when running this rake.

Checks are all passing.

```
$ sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.

System information
System:         Ubuntu 14.04
Current User:   git
Using RVM:      no
Ruby Version:   2.1.2p95
Gem Version:    2.2.2
Bundler Version:1.6.5
Rake Version:   10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:        7.2.2
Revision:       e8c2c62
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            https://git.domain.com
HTTP Clone URL: https://git.domain.com/some-project.git
SSH Clone URL:  git@git.domain.com:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.8
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by maxlazio** [comment]
@bbodenmiller Did you manage to resolve this somehow?

**Comment by bbodenmiller** [comment]
I'm running the packaged release now so it's a nonissue for me now I guess.
