### ISSUE TITLE
Can't accept merge request

### ISSUE THREAD

**Issue by agjmills** [gitlabhq/gitlabhq#8229]
Using stable-7-3

When I click 'Accept merge request' the page refreshes after a couple of seconds and the MR has not been merged

In githost.log I get the following:

```
November 03, 2014 14:15 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/gitlab/gitlab-satellites/amills/test/.git --work-tree=/home/gitlab/gitlab-satellites/amills/test push origin master

remote: /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find gitlab-grit-2.6.11 in any of the sources (Bundler::GemNotFound)
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/spec_set.rb:85:in `map!'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/spec_set.rb:85:in `materialize'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/definition.rb:132:in `specs'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/definition.rb:177:in `specs_for'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/definition.rb:166:in `requested_specs'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/environment.rb:18:in `requested_specs'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/runtime.rb:13:in `setup'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler.rb:121:in `setup'
remote: 	from /usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.0/lib/bundler/setup.rb:17:in `<top (required)>'
remote: 	from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
remote: 	from /usr/local/rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
To /home/gitlab/repositories/amills/test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '/home/gitlab/repositories/amills/test.git'
```

**Comment by Razer6** [comment]
Closing as duplicate.
