### ISSUE TITLE
unicorn reload failed,I really don`t know where has caused this problem"path_adapter (LoadError)"

### ISSUE THREAD

**Issue by kesin** [gitlabhq/gitlabhq#8245]
everything works fine,but after a few days,it caused many 500 error like https://github.com/gitlabhq/gitlabhq/issues/8219

when i try to reload unicorn,it failed,and the error is below
this is the backtrace:
```
I, [2014-11-04T21:31:39.778339 #13528]  INFO -- : executing ["/home/git/gitlab/vendor/bundle/ruby/1.9.1/bin/unicorn_rails", "-c", "/home/git/gitlab/config/unicorn.rb", "-E", "production", {11=>#<Kgio::UNIXServer:fd 11>}] (in /home/git/gitlab)
I, [2014-11-04T21:31:39.778608 #13528]  INFO -- : forked child re-executing...
I, [2014-11-04T21:31:40.635493 #13528]  INFO -- : inherited addr=/home/git/gitlab/tmp/sockets/gitlab.socket fd=11
I, [2014-11-04T21:31:40.636024 #13528]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/backports-2.6.7/lib/backports/tools.rb:314:in `require': cannot load such file -- /home/git/gitlab/lib/gitlab/backend/path_adapter (LoadError)
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/backports-2.6.7/lib/backports/tools.rb:314:in `require_with_backports'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
        from /home/git/gitlab/config/initializers/3_grit_ext.rb:2:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:245:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:245:in `block in load'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:245:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/engine.rb:592:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/engine.rb:592:in `block in <class:Engine>'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:30:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/application.rb:136:in `initialize!'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/railties-3.2.16/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn.rb:44:in `eval'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn.rb:44:in `block in builder'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/bin/unicorn_rails:139:in `call'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:722:in `call'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:722:in `build_app!'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:140:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/unicorn-4.6.2/bin/unicorn_rails:209:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `<main>'
E, [2014-11-04T21:32:04.391884 #2085] ERROR -- : reaped #<Process::Status: pid 13528 exit 1> exec()-ed
```

when I revert the code to one week ago , the unicorn will reload successfully,what was going on about my gitlab?

**Comment by kesin** [comment]
something terrible force delete 

`/home/git/gitlab/lib/gitlab/backend/path_adapter` 

that`s why so many 500 requests!
