### ISSUE TITLE
Error 500 invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by jehy** [gitlabhq/gitlabhq#8277]
Here us the trace log:

```
Started GET "/oracle-repository/ora-sma/commits/master" for 77.105.132.246 at 2014-11-07 19:34:04 +0300
Processing by Projects::CommitsController#show as HTML
  Parameters: {"project_id"=>"oracle-repository/ora-sma", "id"=>"master"}
Completed 500 Internal Server Error in 57ms

ActionView::Template::Error (invalid byte sequence in UTF-8):
    3:     = link_to commit.short_id, project_commit_path(project, commit), class: "commit_short_id"
    4:     &nbsp;
    5:     %span.str-truncated
    6:       = link_to_gfm commit.title, project_commit_path(project, commit.id), class: "commit-row-message"
    7:       - if commit.description?
    8:         %a.text-expander.js-toggle-button ...
    9:
  app/models/commit.rb:76:in `title'
  app/views/projects/commits/_commit.html.haml:6:in `_app_views_projects_commits__commit_html_haml___33198984
73514931984_31167600'
  app/views/projects/commits/_commits.html.haml:10:in `block in _app_views_projects_commits__commits_html_ham
l__4409608720156784451_31384820'
  app/views/projects/commits/_commits.html.haml:1:in `each'
  app/views/projects/commits/_commits.html.haml:1:in `_app_views_projects_commits__commits_html_haml__4409608
720156784451_31384820'
  app/views/projects/commits/show.html.haml:18:in `_app_views_projects_commits_show_html_haml___7335147921900
65859_38672460'
  app/controllers/projects/commits_controller.rb:19:in `show'
```

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
