### ISSUE TITLE
500 Error in tree_controller.rb

### ISSUE THREAD

**Issue by lahdekorpi** [gitlabhq/gitlabhq#8300]
When trying to load one directory under a project, I get this.
Other work just fine and I don't see anything unusual about this particular directory.
It just contains three folders with no special characters and a .htaccess-file.

cat /home/git/gitlab/VERSION
7.4.3
(Just pulled the latest codes from git 7-4-stable branch, 85a9feabd67d6403a59d8aa98f52f83b6bd42fea)

```
Started GET "/lygon-software/secret/tree/master/vendor" for 127.0.0.1 at 2014-11-13 14:35:11 +0200
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"lygon-software/secret", "id"=>"master/vendor"}
Completed 500 Internal Server Error in 49ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: - tree, commit = submodule_links(submodule_item)
    2: %tr{ class: "tree-item" }
    3:   %td.tree-item-file-name
    4:     %i.fa.fa-archive
  app/models/repository.rb:162:in `method_missing'
  app/models/repository.rb:228:in `submodule_url_for'
  app/helpers/submodule_helper.rb:6:in `submodule_links'
  app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml___3443920098639008414_70188242143820'
  app/helpers/tree_helper.rb:19:in `render_tree'
  app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml___3852518911604255446_70188244014680'
  app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml___3170785774790579373_70188245253540'
  app/controllers/projects/tree_controller.rb:13:in `show'
```

**Comment by miramir** [comment]
on my server in one of the repositories bug reprodused. version 7.6.2

**Comment by kossmac** [comment]
Same problem here with 7.6.1.

**Comment by ilijamt** [comment]
I get the same error, from GitLab 7.4, upgrade to the newest to see if it's gonna work or not but not yet.

If I access a subdirectory or a file that I know it's there, it opens it.

There are no submodules anywhere in this repository.

```
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Arduino-PID-Library
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Test_Motor_Control_top
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Test_PWM_test
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Test_speed_sensor
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 libraries
```

Env info
```
$ bundle exec rake gitlab:env:info RAILS_ENV=production
System information
System:
Current User:   git
Using RVM:      yes
RVM Version:    1.26.9
Ruby Version:   2.1.3p242
Gem Version:    2.4.5
Bundler Version:1.7.11
Rake Version:   10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:        7.6.2
Revision:       16f0968
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            http://git.example.com
HTTP Clone URL: http://git.examplecom/some-project.git
SSH Clone URL:  git@git.example.com:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        2.4.0
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

```
$ bundle exec rake gitlab:check RAILS_ENV=production SANITIZE=true
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.4.0 ? ... OK (2.4.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ...
6/3 ... ok
6/5 ... ok
6/8 ... ok
2/9 ... ok
6/12 ... ok
6/14 ... ok
2/16 ... ok
6/18 ... ok
2/20 ... ok
2/22 ... ok
2/24 ... ok
2/28 ... ok
2/29 ... ok
2/30 ... ok
6/32 ... ok
2/36 ... ok
6/38 ... ok
5/45 ... ok
2/47 ... repository is empty
2/49 ... ok
5/51 ... ok
5/52 ... ok
2/54 ... ok
2/55 ... ok
2/57 ... ok
8/58 ... ok
8/60 ... ok
9/62 ... ok
9/63 ... ok
9/64 ... ok
9/66 ... ok
9/67 ... ok
9/68 ... ok
9/69 ... ok
10/70 ... ok
10/71 ... ok
11/72 ... ok
11/74 ... ok
11/75 ... ok
2/76 ... ok
12/77 ... ok
12/78 ... ok
2/79 ... ok
2/80 ... ok
13/82 ... ok
13/83 ... ok
13/84 ... ok
13/85 ... ok
13/86 ... ok
2/87 ... ok
2/88 ... ok
2/89 ... ok
2/90 ... ok
2/91 ... ok
12/92 ... ok
12/93 ... ok
12/94 ... ok
5/95 ... ok
2/96 ... ok
2/97 ... ok
5/98 ... ok
2/100 ... ok
2/101 ... ok
5/102 ... ok
12/104 ... ok
12/105 ... ok
12/106 ... ok
12/107 ... ok
2/108 ... ok
7/109 ... ok
2/110 ... ok
19/111 ... repository is empty
19/113 ... repository is empty
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /home/git/repositories/: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.4.14
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...
6/3 ... yes
6/5 ... yes
6/8 ... yes
2/9 ... yes
6/12 ... yes
6/14 ... yes
2/16 ... yes
6/18 ... yes
2/20 ... yes
2/22 ... yes
2/24 ... yes
2/28 ... yes
2/29 ... yes
2/30 ... yes
6/32 ... yes
2/36 ... yes
6/38 ... yes
5/45 ... yes
2/47 ... yes
2/49 ... yes
5/51 ... yes
5/52 ... yes
2/54 ... yes
2/55 ... yes
2/57 ... yes
8/58 ... yes
8/60 ... yes
9/62 ... yes
9/63 ... yes
9/64 ... yes
9/66 ... yes
9/67 ... yes
9/68 ... yes
9/69 ... yes
10/70 ... yes
10/71 ... yes
11/72 ... yes
11/74 ... yes
11/75 ... yes
2/76 ... yes
12/77 ... yes
12/78 ... yes
2/79 ... yes
2/80 ... yes
13/82 ... yes
13/83 ... yes
13/84 ... yes
13/85 ... yes
13/86 ... yes
2/87 ... yes
2/88 ... yes
2/89 ... yes
2/90 ... yes
2/91 ... yes
12/92 ... yes
12/93 ... yes
12/94 ... yes
5/95 ... yes
2/96 ... yes
2/97 ... yes
5/98 ... yes
2/100 ... yes
2/101 ... yes
5/102 ... yes
12/104 ... yes
12/105 ... yes
12/106 ... yes
12/107 ... yes
2/108 ... yes
7/109 ... yes
2/110 ... yes
19/111 ... yes
19/113 ... yes
Projects have satellites? ...
6/3 ... yes
6/5 ... yes
6/8 ... yes
2/9 ... yes
6/12 ... yes
6/14 ... yes
2/16 ... yes
6/18 ... yes
2/20 ... yes
2/22 ... yes
2/24 ... yes
2/28 ... yes
2/29 ... yes
2/30 ... yes
6/32 ... yes
2/36 ... yes
6/38 ... yes
5/45 ... yes
2/47 ... can't create, repository is empty
2/49 ... yes
5/51 ... yes
5/52 ... yes
2/54 ... yes
2/55 ... yes
2/57 ... yes
8/58 ... yes
8/60 ... yes
9/62 ... yes
9/63 ... yes
9/64 ... yes
9/66 ... yes
9/67 ... yes
9/68 ... yes
9/69 ... yes
10/70 ... yes
10/71 ... yes
11/72 ... yes
11/74 ... yes
11/75 ... yes
2/76 ... yes
12/77 ... yes
12/78 ... yes
2/79 ... yes
2/80 ... yes
13/82 ... yes
13/83 ... yes
13/84 ... yes
13/85 ... yes
13/86 ... yes
2/87 ... yes
2/88 ... yes
2/89 ... yes
2/90 ... yes
2/91 ... yes
12/92 ... yes
12/93 ... yes
12/94 ... yes
5/95 ... yes
2/96 ... yes
2/97 ... yes
5/98 ... yes
2/100 ... yes
2/101 ... yes
5/102 ... yes
12/104 ... yes
12/105 ... yes
12/106 ... yes
12/107 ... yes
2/108 ... yes
7/109 ... yes
2/110 ... yes
19/111 ... can't create, repository is empty
19/113 ... can't create, repository is empty
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.3)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)

Checking GitLab ... Finished
```
```
==> production.log <==
Started GET "/dissolution-tester/motor-control-prototype/tree/master/motor_drive_code" for xx.xx.xx.xx at 2015-01-11 15:36:17 +0100
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"dissolution-tester/motor-control-prototype", "id"=>"master/motor_drive_code"}
Completed 500 Internal Server Error in 23ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: - tree, commit = submodule_links(submodule_item)
    2: %tr{ class: "tree-item" }
    3:   %td.tree-item-file-name
    4:     %i.fa.fa-archive
  app/models/repository.rb:162:in `method_missing'
  app/models/repository.rb:228:in `submodule_url_for'
  app/helpers/submodule_helper.rb:6:in `submodule_links'
  app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml___3500888102168699947_109800500'
  app/helpers/tree_helper.rb:19:in `render_tree'
  app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml__4423253723950718480_48962860'
  app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__736981549564409748_46927540'
  app/controllers/projects/tree_controller.rb:13:in `show'
```

**Comment by stanhu** [comment]
Can you output the following?

```
git ls-tree HEAD
cat .gitmodules
```

**Comment by stanhu** [comment]
The reason I ask whether there is a stale .gitmodules lying around or a directory that appears to be a submodule that is not listed in .gitmodules. I'm wondering if ea939d4691b97acbb87df53cddbdc157b70aae0d fixes the issue, which will be available in GitLab v7.10 on April 22.

**Comment by ilijamt** [comment]
At the time I updated to the newest version available, and it worked, haven't had issues since then.
Plus I don't have any modules in this repository

**Comment by Razer6** [comment]
Then close this here
