### ISSUE TITLE
Error 500 on Project, Files and Graphs Page

### ISSUE THREAD

**Issue by raphaelheitor** [gitlabhq/gitlabhq#8481]
After you import a repository Gitorious (old git server, we are migrating to gitlab). I am having problem (mainly encode utf8), to view graphics, network, files and project pages.

follows the producion.log:

Files:
```
Started GET "/dides/protocolo/tree/master" for 127.0.0.1 at 2014-12-23 11:10:05 -0400
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"dides/protocolo", "id"=>"master"}
Completed 500 Internal Server Error in 64ms

ArgumentError (invalid byte sequence in UTF-8):
  app/models/tree.rb:11:in `select'
  app/models/tree.rb:11:in `initialize'
  app/models/repository.rb:208:in `new'
  app/models/repository.rb:208:in `tree'
  lib/extracts_path.rb:120:in `tree'
  app/controllers/projects/tree_controller.rb:5:in `show'
```

Project:
```
Started GET "/dides/protocolo" for 127.0.0.1 at 2014-12-23 11:19:25 -0400
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"dides/protocolo"}
Completed 500 Internal Server Error in 188ms

ActionView::Template::Error (invalid byte sequence in UTF-8):
    1: = render "home_panel"
    2:
    3: - readme = @repository.readme
    4: %ul.nav.nav-tabs
    5:   %li.active
    6:     = link_to '#tab-activity', 'data-toggle' => 'tab' do
  app/models/tree.rb:11:in `select'
  app/models/tree.rb:11:in `initialize'
  app/models/repository.rb:208:in `new'
  app/models/repository.rb:208:in `tree'
  app/models/repository.rb:181:in `block in readme'
  app/models/repository.rb:180:in `readme'
  app/views/projects/show.html.haml:3:in `_app_views_projects_show_html_haml___1630649596823991859_42615660'
  app/controllers/projects_controller.rb:71:in `block (2 levels) in show'
  app/controllers/projects_controller.rb:65:in `show'
```

Graphs:

```
Started GET "/dides/concessao-diarias/graphs/master" for 127.0.0.1 at 2014-12-23 11:20:44 -0400
Processing by Projects::GraphsController#show as JSON
  Parameters: {"project_id"=>"dides/concessao-diarias", "id"=>"master"}
Completed 500 Internal Server Error in 229ms

JSON::GeneratorError (source sequence is illegal/malformed utf-8):
  app/controllers/projects/graphs_controller.rb:44:in `fetch_graph'
  app/controllers/projects/graphs_controller.rb:11:in `block (2 levels) in show'
  app/controllers/projects/graphs_controller.rb:8:in `show'
```

**Comment by DouweM** [comment]
A fix to this issue has been merged and will be in version 7.9. Please reopen this issue if the problem persists after upgrading to 7.9.
