### ISSUE TITLE
activity page not update

### ISSUE THREAD

**Issue by layzerar** [gitlabhq/gitlabhq#8488]
In my git repository, there are three commits which the commit timestamp is broken. They are very old commits, so I have no idea how to fix it.

So, when I push something, the sidekiq would raise an exception about this. As the result, the activity page would not update any more.

Exception information:
```
2014-12-24T06:28:35Z 2135 TID-or6mj0oeo WARN: {"class"=>"PostReceive", "args"=>["/home/git/repositories/test/test.git", "key-15", "0302657f0c699bd90a202f8616886ebbc742025e 001b95ea4d808c3f91c6a7426c8b0dfea220e8a8 refs/heads/dev\n"]}
2014-12-24T06:28:35Z 2135 TID-or6mj0oeo WARN: Failed to parse commit 81a8f4efa1150ef2a19d13d5f1128a3f6e1affd4 - cannot parse commit time
2014-12-24T06:28:35Z 2135 TID-or6mj0oeo WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc12/lib/gitlab_git/repository.rb:256:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc12/lib/gitlab_git/repository.rb:256:in `to_a'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc12/lib/gitlab_git/repository.rb:256:in `commits_between'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/gitlab_git-7.0.0.rc12/lib/gitlab_git/commit.rb:96:in `between'
/home/git/gitlab/app/models/repository.rb:50:in `commits_between'
/home/git/gitlab/app/services/git_push_service.rb:43:in `execute'
/home/git/gitlab/app/workers/post_receive.rb:39:in `block in perform'
/home/git/gitlab/app/workers/post_receive.rb:26:in `each'
/home/git/gitlab/app/workers/post_receive.rb:26:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:86:in `do_defer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:37:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

Product environment:
```
System information
System:		Ubuntu 12.04
Current User:	git
Using RVM:	no
Ruby Version:	2.1.2p95
Gem Version:	2.2.2
Bundler Version:1.6.4
Rake Version:	10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:	7.5.3
Revision:	b656b85
Directory:	/home/git/gitlab
DB Adapter:	postgresql
URL:		https://172.16.1.131
HTTP Clone URL:	https://172.16.1.131/some-project.git
SSH Clone URL:	git@172.16.1.131:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.2.0
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/local/bin/git
```

**Comment by layzerar** [comment]
Yes, `rake gitlab:check` all pass.

**Comment by Plonk42** [comment]
+1

Plus, the commits list for all branches containing corrupted commits, and the network graph (if corrupted commits supposed to be shown) are not displayed.

Production log when trying to display one of those commits:
```
Started GET "/XXXX/XXXX/compare/master...dev" for 127.0.0.1 at 2015-01-05 16:47:00 +0100
Processing by Projects::CompareController#show as HTML
Parameters: {"project_id"=>"xxxxxxxxxxxxx", "from"=>"master", "to"=>"dev"}
Completed 500 Internal Server Error in 44ms
Rugged::OdbError (Failed to parse commit YYYYYYYYYYYYY - cannot parse commit time):
app/services/compare_service.rb:11:in `new'
app/services/compare_service.rb:11:in `execute'
app/controllers/projects/compare_controller.rb:14:in `show'
```

The error is probably coming from `rugged-0.19.0/vendor/libgit2/src/commit_list.c`, l.170:
```C
if ((buffer == committer_start) || (git__strtol32(&commit_time, (char *)(buffer + 1), NULL, 10) < 0))
     return commit_error(commit, "cannot parse commit time");
```

In a shell, the corrupted commit is displayed like that:
```
> git show YYYYYYYYYYYYY
commit YYYYYYYYYYYYY
Author: John Doe
Date:   Sun Feb 7 06:28:38 2106 -38842451
```

**Comment by layzerar** [comment]
It doesn't work by simply skipping the corrupted commits ether.
```ruby
        # repository.rb:257
        # commits = walker.to_a
        commits = Array.new
        iter = walker.each
        loop do
            begin
                commits.push(iter.next)
            rescue Rugged::OdbError
            rescue StopIteration
                break
            end
        end
```

**Comment by Razer6** [comment]
Thank you for your interest in improving GitLab. We don't use the issue tracker for feature requests. Things that are wrong but are not a regression compared to older versions of GitLab are considered feature requests and not issues. Please use the [feature request forum](http://feedback.gitlab.com/) for this purpose or create a merge request implementing this feature. Have a look at the [contribution guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md) for more information.
