### ISSUE TITLE
Push over https not working: couldn't find rake 10.3.2

### ISSUE THREAD

**Issue by nightcoding** [gitlabhq/gitlabhq#8542]
Hi there,

I recently installed a fresh gitlab installation with the following system informations:

Debian 7.7, 2 CPUs, 8 GB RAM
GitLab 7.6.2, Ruby 2.1.5 with RVM
MySQL 5.5.40

Also not recommended I had to install it with RVM, as the system ruby version is 1.9.x and this ruby version is needed by another software. 
The installation worked and everything works fine, except that a push/pull over HTTPS is not working. Over SSH it's working. The current error message is the following:

```
remote: /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/spec_set.rb:85:in `map!'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/spec_set.rb:85:in `materialize'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/definition.rb:132:in `specs'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/definition.rb:177:in `specs_for'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/definition.rb:166:in `requested_specs'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/environment.rb:18:in `requested_specs'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:13:in `setup'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:121:in `setup'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/setup.rb:17:in `<top (required)>'
remote: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
remote: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
To https://dev.example.com/admin/rm_theme_minimal.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://dev.example.com/admin/rm_theme_minimal.git'
```
I think it has to do with the RVM installation. But since push/pull over SSH is working I have no idea what could be wrong. Have you any suggestions?

Thanks a lot!
Martin

**Comment by jangrewe** [comment]
+1 for the same problem when trying to merge requests via the web, running GitLab 7.7 and Ruby 2.1.5 in RVM on Ubuntu 14.04
```
February 09, 2015 09:20 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/dc/puppet-master/.git --work-tree=/home/git/gitlab-satellites/dc/puppet-master push origin master

remote: /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `map!'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `materialize'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/definition.rb:132:in `specs'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/definition.rb:177:in `specs_for'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/definition.rb:166:in `requested_specs'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/environment.rb:18:in `requested_specs'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/runtime.rb:13:in `setup'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler.rb:122:in `setup'
remote: 	from /home/git/.rvm/gems/ruby-2.1.5/gems/bundler-1.7.12/lib/bundler/setup.rb:17:in `<top (required)>'
remote: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
remote: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
To /home/git/repositories/dc/puppet-master.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to '/home/git/repositories/dc/puppet-master.git'
```

**Comment by jangrewe** [comment]
@nightcoding  I was able to fix it by applying the changes in #8356 (make sure to first do the gitlab step and the rake task, then create the hook scripts).

**Comment by Razer6** [comment]
Closing this here because solution provided

**Comment by nightcoding** [comment]
@jangrewe Thanks a lot! I've updated yesterday to current GitLab version and it works well!
