### ISSUE TITLE
Mail not sent Gitlab 7.6.2 (TypeError no implicit conversion of false into Integer)

### ISSUE THREAD

**Issue by ZaDarkSide** [gitlabhq/gitlabhq#8543]
Clean installation on Ubuntu 14.04 LTS

This happens when I set gitlab_rails['smtp_tls'] = true in /etc/gitlab/gitlab.rb
If I set gitlab_rails['smtp_tls'] = false I get the error *Net::ReadTimeout* instead of *TypeError: no implicit conversion of false into Integer*

sidekiq.log

```
2015-01-06_15:34:51.10732 2015-01-06T15:34:51Z 11152 TID-c35uk WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'Notify'\n- :new_user_email\n- - 2\n - U_1X2ob5sFGoz8Fqyjs3\n"], "jid"=>"64f58bf2988755bbc7c4432a", "enqueued_at"=>1420554162.0893998, "error_message"=>"no implicit conversion of false into Integer", "error_class"=>"TypeError", "failed_at"=>1420554177.8173306, "retry_count"=>6, "retried_at"=>1420558491.079166}
2015-01-06_15:34:51.10780 2015-01-06T15:34:51Z 11152 TID-c35uk WARN: no implicit conversion of false into Integer
2015-01-06_15:34:51.11466 2015-01-06T15:34:51Z 11152 TID-c35uk WARN: /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:578:in `initialize'
2015-01-06_15:34:51.11470 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:578:in `new'
2015-01-06_15:34:51.11472 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:578:in `ssl_socket'
2015-01-06_15:34:51.11473 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:583:in `tlsconnect'
2015-01-06_15:34:51.11474 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:554:in `do_start'
2015-01-06_15:34:51.11475 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
2015-01-06_15:34:51.11476 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
2015-01-06_15:34:51.11477 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
2015-01-06_15:34:51.11479 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:232:in `block in deliver'
2015-01-06_15:34:51.11480 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:527:in `block in deliver_mail'
2015-01-06_15:34:51.11481 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
2015-01-06_15:34:51.11485 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-01-06_15:34:51.11491 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
2015-01-06_15:34:51.11492 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:525:in `deliver_mail'
2015-01-06_15:34:51.11494 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:232:in `deliver'
2015-01-06_15:34:51.11495 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/extensions/action_mailer.rb:20:in `perform'
2015-01-06_15:34:51.11496 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
2015-01-06_15:34:51.11497 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:122:in `call'
2015-01-06_15:34:51.11499 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
2015-01-06_15:34:51.11500 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sidekiq_middleware/memory_killer.rb:16:in `call'
2015-01-06_15:34:51.11504 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-01-06_15:34:51.11505 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2015-01-06_15:34:51.11506 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-01-06_15:34:51.11507 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
2015-01-06_15:34:51.11509 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-01-06_15:34:51.11510 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2015-01-06_15:34:51.11511 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/logging.rb:22:in `with_context'
2015-01-06_15:34:51.11512 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2015-01-06_15:34:51.11514 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-01-06_15:34:51.11517 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:127:in `call'
2015-01-06_15:34:51.11519 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:127:in `invoke'
2015-01-06_15:34:51.11520 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
2015-01-06_15:34:51.11521 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:108:in `stats'
2015-01-06_15:34:51.11522 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:47:in `block in process'
2015-01-06_15:34:51.11524 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:86:in `do_defer'
2015-01-06_15:34:51.11525 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:37:in `process'
2015-01-06_15:34:51.11526 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2015-01-06_15:34:51.11527 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2015-01-06_15:34:51.11531 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
2015-01-06_15:34:51.11533 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2015-01-06_15:34:51.11534 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2015-01-06_15:34:51.11537 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2015-01-06_15:34:51.11538 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

/opt/gitlab/embedded/service/gitlab-rails/config/initializers/smtp_settings.rb

```
# This file is managed by gitlab-ctl. Manual changes will be
# erased! To change the contents below, edit /etc/gitlab/gitlab.rb
# and run `sudo gitlab-ctl reconfigure`.

if Rails.env.production?
  Gitlab::Application.config.action_mailer.delivery_method = :smtp

  ActionMailer::Base.smtp_settings = {
    authentication: :login,
    address: "smtp.xxxxxxx",
    port: 465,
    user_name: "gitlab@xxxxxx",
    password: "xxxxxxxxxxx",
    domain: "gitlab.xxxxxxx",
    enable_starttls_auto: true,
    tls: true,
    openssl_verify_mode: false,
  }
end
```

/etc/gitlab/gitlab.rb

```
...
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "smtp.xxxxxxx"
gitlab_rails['smtp_port'] = 465
gitlab_rails['smtp_user_name'] = "gitlab@xxxxxxx"
gitlab_rails['smtp_password'] = "xxxxxxxxxxxxxx"
gitlab_rails['smtp_domain'] = "gitlab.xxxxxxx"
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['smtp_tls'] = true
gitlab_rails['smtp_openssl_verify_mode'] = false
...
```

![gitlab](https://cloud.githubusercontent.com/assets/291278/5631159/f00c9a0c-95cc-11e4-91f1-b4168da3f63b.png)

**Comment by pbotadra** [comment]
I have the same issue. Would appreciate some help.

**Comment by luoka** [comment]
same issue,send email failed

**Comment by lancedikson** [comment]
Help, please! I have the same issue.

**Comment by lancedikson** [comment]
Oh, I have decide my problem. Just commented string ```gitlab_rails['smtp_openssl_verify_mode'] = true``` in the /etc/gitlab/gitlab.rc.
it's was been stumbling block for me.

**Comment by ZaDarkSide** [comment]
Well in my config I have ```gitlab_rails['smtp_openssl_verify_mode'] = false``` commenting it out will change anything?

**Comment by skwerlman** [comment]
I am having the same issue; also on Ubuntu 14.04.

**Comment by gagan0123** [comment]
Was having the same issue, both with Gmail and Postmarkapp SMTP, 
Just commented the line `gitlab_rails['smtp_openssl_verify_mode'] = true in the /etc/gitlab/gitlab.rc` and it worked, as suggested by @lancedikson .

**Comment by pbotadra** [comment]
Yes, that change (suggest by @lancedikson worked for me too.

**Comment by Razer6** [comment]
Closing because fix provided
