### ISSUE TITLE
Could not commit changes via HTTP or Web

### ISSUE THREAD

**Issue by tormedo** [gitlabhq/gitlabhq#8555]
First i was having trouble with the error mentioned in #7230 so i removed ruby except 2.1.5p273.
Now when i am trying to push via http or edit a file in the Web GUI i get the error:

```
remote: /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/dsl.rb:35:in `eval_gemfile': Gemfile syntax error compile error (Bundler::GemfileError)[K
remote: on line 20: syntax error, unexpected ':', expecting $end[K
remote: gem "mysql2", group: :mysql[K
remote:                     ^[K
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/dsl.rb:10:in `evaluate'[K
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/definition.rb:25:in `build'[K
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:155:in `definition'[K
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:118:in `setup'[K
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/setup.rb:17[K
```
if i run
```
sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
```
i get no errors. Any idea here?

**Comment by kmetsalu** [comment]
I second that.

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
