### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Poil** [gitlabhq/gitlabhq#8556]
Hi,

With Gitlab 7.6.2 I've got an error 500 when browsing a subfolder of a repository, there is nothing special in this directory

```bash
drwxrwxr-x 10 git git  4096 Oct 27 17:34 ./
drwxr-xr-x 13 git git  4096 Oct 27 17:34 ../
drwxrwxr-x  2 git git  4096 Oct 27 17:34 AWS-Audit/
drwxrwxr-x  2 git git  4096 Oct 27 17:34 aws-scheduler/
drwxrwxr-x  2 git git  4096 Oct 27 17:34 aws-scheduler-pprod/
drwxrwxr-x  2 git git  4096 Oct 27 17:34 check_backup/
-rwxrwxr-x  1 git git  4290 Oct 27 17:34 entratact_backup.py*
-rwxrwxr-x  1 git git 12490 Oct 27 17:34 entratact_trim_backup.py*
drwxrwxr-x  3 git git  4096 Oct 27 17:34 CLOUDWATCH/
drwxrwxr-x  2 git git  4096 Oct 27 17:34 DESCRIBE_AWS_SERVICE/
drwxrwxr-x  2 git git  4096 Oct 27 17:34 dns/
-rwxrwxr-x  1 git git  1876 Oct 27 17:34 pop_network.sh*
-rwxrwxr-x  1 git git  3006 Oct 27 17:34 tag_instance_from_reverse_lookup.py*
-rwxrwxr-x  1 git git  2690 Oct 27 17:34 tag_volume.py*
drwxrwxr-x  2 git git  4096 Oct 27 17:34 website/
```

```ruby
==> production.log <==
Started GET "/build/cfn-entratact/tree/master/tools" for 127.0.0.1 at 2015-01-10 10:50:43 +0100
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"build/cfn-entratact", "id"=>"master/tools"}
Completed 500 Internal Server Error in 113ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: - tree, commit = submodule_links(submodule_item)
    2: %tr{ class: "tree-item" }
    3:   %td.tree-item-file-name
    4:     %i.fa.fa-archive
  app/models/repository.rb:162:in `method_missing'
  app/models/repository.rb:228:in `submodule_url_for'
  app/helpers/submodule_helper.rb:6:in `submodule_links'
  app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml__3078344663143695756_69989017211620'
  app/helpers/tree_helper.rb:19:in `render_tree'
  app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml___565237418053301959_69988919221660'
  app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__3362908899797241201_69988926032940'
  app/controllers/projects/tree_controller.rb:13:in `show'
```

**Comment by ilijamt** [comment]
I get the same error, from GitLab 7.4, upgrade to the newest to see if it's gonna work or not but not yet.

If I access a subdirectory or a file that I know it's there, it opens it.

```
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Arduino-PID-Library
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Test_Motor_Control_top
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Test_PWM_test
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 Test_speed_sensor
drwxr-xr-x  2 git git 4.0K Nov 13 18:41 libraries
```


```
==> production.log <==
Started GET "/dissolution-tester/motor-control-prototype/tree/master/motor_drive_code" for xx.xx.xx.xx at 2015-01-11 15:36:17 +0100
Processing by Projects::TreeController#show as HTML
  Parameters: {"project_id"=>"dissolution-tester/motor-control-prototype", "id"=>"master/motor_drive_code"}
Completed 500 Internal Server Error in 23ms

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: - tree, commit = submodule_links(submodule_item)
    2: %tr{ class: "tree-item" }
    3:   %td.tree-item-file-name
    4:     %i.fa.fa-archive
  app/models/repository.rb:162:in `method_missing'
  app/models/repository.rb:228:in `submodule_url_for'
  app/helpers/submodule_helper.rb:6:in `submodule_links'
  app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml___3500888102168699947_109800500'
  app/helpers/tree_helper.rb:19:in `render_tree'
  app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml__4423253723950718480_48962860'
  app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml__736981549564409748_46927540'
  app/controllers/projects/tree_controller.rb:13:in `show'
```

**Comment by Razer6** [comment]
This is fixed on master. Report back if the error still exists in the next release
