### ISSUE TITLE
OmniAuth Error when Installing GitLab Shell

### ISSUE THREAD

**Issue by DaAwesomeP** [gitlabhq/gitlabhq#8569]
When try to install the latest GitLab:
```
root@gitlabtest-debian-vm2:/home/git/gitlab# sudo -u git -H bundle exec rake --trace gitlab:shell:install[v2.4.0] REDIS_URL=unix:/var/run/redis/redis.sock RAILS_ENV=production
rake aborted!
NameError: uninitialized constant OmniAuth::Strategy
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-oauth2-1.1.1/lib/omniauth/strategies/oauth2.rb:16:in `<class:OAuth2>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-oauth2-1.1.1/lib/omniauth/strategies/oauth2.rb:15:in `<module:Strategies>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-oauth2-1.1.1/lib/omniauth/strategies/oauth2.rb:9:in `<module:OmniAuth>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-oauth2-1.1.1/lib/omniauth/strategies/oauth2.rb:8:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-google-oauth2-0.2.5/lib/omniauth/strategies/google_oauth2.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-google-oauth2-0.2.5/lib/omniauth/google_oauth2.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/omniauth-google-oauth2-0.2.5/lib/omniauth-google-oauth2.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
/home/git/gitlab/config/application.rb:6:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:94:in `block in load_rakefile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:93:in `load_rakefile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:77:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
```
I have little to no experience with Ruby.

Up to this point, the manual install has run smoothly. I originally tried the automated install, but I ran into lots of problems (there wasn't a git user nor `init.d` service yet it said it completed with no errors).

I added `--trace` to the command, which is originally is from [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/7-6-stable/doc/install/installation.md#install-gitlab-shell).

*Debian 7.8 x64*

**Comment by DaAwesomeP** [comment]
Resolved. 

For more information see: [GitLab Community Forum - Troubleshooting - OmniAuth rake Error when Installing GitLab Shell](https://forum.gitlab.com/t/omniauth-rake-error-when-installing-gitlab-shell/74).
