### ISSUE TITLE
Issue installing gitlab shell v2.4.0 with gitlab 7.6

### ISSUE THREAD

**Issue by MelonSmasher** [gitlabhq/gitlabhq#8582]
I'm on Debian 7 using git `v2.1.2` and Ruby `v2.1.5p273`
This is the full trace:
```shell
root@gitlab:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:shell:install[v2.4.0] REDIS_URL=unix:/var/run/redis/redis.sock RAILS_ENV=production --trace
** Invoke gitlab:shell:install (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 18 column 3
/usr/local/lib/ruby/2.1.0/psych.rb:370:in `parse'
/usr/local/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
/usr/local/lib/ruby/2.1.0/psych.rb:318:in `parse'
/usr/local/lib/ruby/2.1.0/psych.rb:245:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
/home/git/gitlab/config/initializers/1_settings.rb:57:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:161:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:647:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:611:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:44:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.1.0/tsort.rb:411:in `call'
/usr/local/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/local/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:288:in `initialize!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `method_missing'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:264:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:367:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:shell:install => environment
```

**Comment by Razer6** [comment]
This is related to an invalid YAML configuration. Please verify your configuration files.
