### ISSUE TITLE
Commit view raises 500 internal error

### ISSUE THREAD

**Issue by blackst0ne** [gitlabhq/gitlabhq#8587]
GitLab 7.6.1 0286222

I get `500 Error ` when I want to view some commits or comparison of commits.
Examples of URL: 
1. `http://example.com/it_group/project_example/commit/0b61bbaedb461b7f7d1560fdef51405dea16d0b0`
2. `http://example.com/it_group/project_example/compare/09df545cbc7825b5ea1d5a75b454d286b786c97e...37515325d93b56951072aa6b39302135d6b73006`

`log/production.log` says:
```
Started GET "/it_group/project_example/commit/68220efc612d254b021fb6262f01acbf8c559c5d" for 127.0.0.1 at 2015-01-16 09:41:50 +1000
Processing by Projects::CommitController#show as HTML
  Parameters: {"project_id"=>"it_group/project_example", "id"=>"68220efc612d254b021fb6262f01acbf8c559c5d"}
Completed 500 Internal Server Error in 135ms

ActionView::Template::Error (undefined method `[]' for #<Enumerator:0x0000000af2e478>):
    1: - too_big = diff_file.diff_lines.count > Commit::DIFF_SAFE_LINES
    2: - if too_big
    3:   %a.supp_diff_link Changes suppressed. Click to show
    4: 
  lib/gitlab/inline_diff.rb:12:in `block in processing'
  lib/gitlab/inline_diff.rb:11:in `each'
  lib/gitlab/inline_diff.rb:11:in `processing'
  lib/gitlab/diff/parser.rb:14:in `parse'
  lib/gitlab/diff/file.rb:15:in `diff_lines'
  app/views/projects/diffs/_text_file.html.haml:1:in `_app_views_projects_diffs__text_file_html_haml__4139344899471268651_91344860'
  app/views/projects/diffs/_file.html.haml:46:in `_app_views_projects_diffs__file_html_haml___3469335261346728823_91024520'
  app/views/projects/diffs/_diffs.html.haml:20:in `block in _app_views_projects_diffs__diffs_html_haml___4057689204440181923_90338880'
  app/views/projects/diffs/_diffs.html.haml:19:in `each'
  app/views/projects/diffs/_diffs.html.haml:19:in `each_with_index'
  app/views/projects/diffs/_diffs.html.haml:19:in `_app_views_projects_diffs__diffs_html_haml___4057689204440181923_90338880'
  app/views/projects/commit/show.html.haml:2:in `_app_views_projects_commit_show_html_haml___39477098123020149_88956840'
  app/controllers/projects/commit_controller.rb:26:in `show'

```

**Comment by blackst0ne** [comment]
```
$ bundle exec rake gitlab:env:info RAILS_ENV=production

System information
System:         Ubuntu 14.04
Current User:   git
Using RVM:      no
Ruby Version:   1.9.3p484
Gem Version:    1.8.23
Bundler Version:1.3.5
Rake Version:   10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:        7.6.1
Revision:       0286222
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            http://example.com
HTTP Clone URL: http://example.com/some-project.git
SSH Clone URL:  git@example.com:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        2.4.0
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by blackst0ne** [comment]
Just upgraded to 7.6.2 and everything got working now.
