### ISSUE TITLE
500 We're sorry, but something went wrong -> for …/commits/master

### ISSUE THREAD

**Issue by offlinehoster** [gitlabhq/gitlabhq#8617]
```
==> gitlab-rails/production.log <==
Started GET "/company/reponame/commits/master" for 266.266.266.266 at 2015-01-20 13:36:15 +0100
Processing by Projects::CommitsController#show as HTML
  Parameters: {"project_id"=>"company/reponame", "id"=>"master"}
Completed 500 Internal Server Error in 87ms

ActionView::Template::Error (invalid byte sequence in UTF-8):
    3:     = link_to commit.short_id, project_commit_path(project, commit), class: "commit_short_id"
    4:     &nbsp;
    5:     %span.str-truncated
    6:       = link_to_gfm commit.title, project_commit_path(project, commit.id), class: "commit-row-message"
    7:       - if commit.description?
    8:         %a.text-expander.js-toggle-button ...
    9:
  app/models/commit.rb:76:in `title'
  app/views/projects/commits/_commit.html.haml:6:in `_app_views_projects_commits__commit_html_haml___3002010716750934910_52146240'
  app/views/projects/commits/_commits.html.haml:10:in `block in _app_views_projects_commits__commits_html_haml___3290458241762894901_52443960'
  app/views/projects/commits/_commits.html.haml:1:in `each'
  app/views/projects/commits/_commits.html.haml:1:in `_app_views_projects_commits__commits_html_haml___3290458241762894901_52443960'
  app/views/projects/commits/show.html.haml:18:in `_app_views_projects_commits_show_html_haml___1667700406023641542_53924420'
  app/controllers/projects/commits_controller.rb:18:in `show'
```

**Comment by offlinehoster** [comment]
Maybe the same like https://github.com/gitlabhq/gitlabhq/issues/8277

**Comment by Leryan** [comment]
Had almost the same problem.

```
Started GET "/capensis/hpanywhere/commits/master" for 82.226.113.5 at 2015-01-22 11:45:26 +0100
Processing by Projects::CommitsController#show as HTML
  Parameters: {"project_id"=>"capensis/hpanywhere", "id"=>"master"}
Completed 500 Internal Server Error in 38ms

ActionView::Template::Error (invalid byte sequence in UTF-8):
    3:     = link_to commit.short_id, project_commit_path(project, commit), class: "commit_short_id"
    4:     &nbsp;
    5:     %span.str-truncated
    6:       = link_to_gfm commit.title, project_commit_path(project, commit.id), class: "commit-row-message"
    7:       - if commit.description?
    8:         %a.text-expander.js-toggle-button ...
    9: 
  app/models/commit.rb:76:in `title'
  app/views/projects/commits/_commit.html.haml:6:in `_app_views_projects_commits__commit_html_haml___991546656153737523_69822528193580'
  app/views/projects/commits/_commits.html.haml:10:in `block in _app_views_projects_commits__commits_html_haml__2775621781898873469_69822528081480'
  app/views/projects/commits/_commits.html.haml:1:in `each'
  app/views/projects/commits/_commits.html.haml:1:in `_app_views_projects_commits__commits_html_haml__2775621781898873469_69822528081480'
  app/views/projects/commits/show.html.haml:18:in `_app_views_projects_commits_show_html_haml___2624881465811712797_69822527522560'
  app/controllers/projects/commits_controller.rb:18:in `show'


Started GET "/capensis/hpanywhere/commits/master" for 82.226.113.5 at 2015-01-22 11:45:26 +0100
Processing by Projects::CommitsController#show as HTML
  Parameters: {"project_id"=>"capensis/hpanywhere", "id"=>"master"}
Completed 500 Internal Server Error in 37ms

ActionView::Template::Error (invalid byte sequence in UTF-8):
    3:     = link_to commit.short_id, project_commit_path(project, commit), class: "commit_short_id"
    4:     &nbsp;
    5:     %span.str-truncated
    6:       = link_to_gfm commit.title, project_commit_path(project, commit.id), class: "commit-row-message"
    7:       - if commit.description?
    8:         %a.text-expander.js-toggle-button ...
    9: 
  app/models/commit.rb:76:in `title'
  app/views/projects/commits/_commit.html.haml:6:in `_app_views_projects_commits__commit_html_haml___991546656153737523_69822524856200'
  app/views/projects/commits/_commits.html.haml:10:in `block in _app_views_projects_commits__commits_html_haml__2775621781898873469_69822525238120'
  app/views/projects/commits/_commits.html.haml:1:in `each'
  app/views/projects/commits/_commits.html.haml:1:in `_app_views_projects_commits__commits_html_haml__2775621781898873469_69822525238120'
  app/views/projects/commits/show.html.haml:18:in `_app_views_projects_commits_show_html_haml___2624881465811712797_69822526451740'
  app/controllers/projects/commits_controller.rb:18:in `show'


Started GET "/static.css" for 82.226.113.5 at 2015-01-22 11:45:27 +0100
Processing by NamespacesController#show as HTML
  Parameters: {"id"=>"static.css"}
Completed 404 Not Found in 4ms (Views: 0.5ms | ActiveRecord: 0.2ms)
Started GET "/Leryan/puppet-peterschmitt-fr/refs/4dae0713b06a86995e3e65bcda162a4b74737b8e/logs_tree/file_repository/module_files/0002-web.peterschmitt.fr/var" for 66.249.73.205 at 2015-01-22 11:45:46 +0100
Processing by Projects::RefsController#logs_tree as HTML
  Parameters: {"project_id"=>"Leryan/puppet-peterschmitt-fr", "id"=>"4dae0713b06a86995e3e65bcda162a4b74737b8e", "path"=>"file_repository/module_files/0002-web.peterschmitt.fr/var"}
Completed 500 Internal Server Error in 25ms

ActionView::MissingTemplate (Missing template projects/refs/logs_tree, projects/application/logs_tree, application/logs_tree with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :haml]}. Searched in:
  * "/home/git/gitlab/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/semantic-ui-sass-0.16.1.0/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/kaminari-0.15.1/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/app/views"
):
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/path_set.rb:46:in `find'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/lookup_context.rb:124:in `find'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:41:in `determine_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:8:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:99:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:82:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/rendering.rb:25:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /opt/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:40:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:189:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:229:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:229:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:229:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:229:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal.rb:195:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal.rb:231:in `block in action'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:80:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:48:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:71:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:676:in `call'
  vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-cors-0.2.9/lib/rack/cors.rb:54:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-attack-2.3.0/lib/rack/attack.rb:63:in `call'
  vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/flash.rb:254:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:552:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/unicorn-worker-killer-0.4.2/lib/unicorn/worker_killer.rb:51:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:632:in `worker_loop'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:511:in `maintain_worker_count'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:277:in `join'
  vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/bin/unicorn_rails:209:in `<top (required)>'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
  vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
```

A commit was malformed: invalid character sequence for UTF-8.

**Comment by offlinehoster** [comment]
This issue doesn't exist anymore after upgrading to GitLab CE 7.8.2
