### ISSUE TITLE
500 error when i try to look at a file when not connected

### ISSUE THREAD

**Issue by Eijebong** [gitlabhq/gitlabhq#8637]
Hi,
if I try to look at a file when not connected. I'm on the master branch.

```
ActionView::Template::Error (undefined method `can?' for nil:NilClass):
    1: .btn-group.tree-btn-group
    2:   = edit_blob_link(@project, @ref, @path)
    3:   = link_to 'Raw', project_raw_path(@project, @id),
    4:       class: 'btn btn-small', target: '_blank'
    5:   -# only show normal/blame view links for text files
  lib/gitlab/git_access.rb:13:in `can_push_to_branch?'
  app/helpers/tree_helper.rb:64:in `allowed_tree_edit?'
  app/helpers/tree_helper.rb:82:in `edit_blob_link'
  app/views/projects/blob/_actions.html.haml:2:in `_app_views_projects_blob__actions_html_haml___4479821848823101402_101467040'
  app/views/projects/blob/_blob.html.haml:29:in `_app_views_projects_blob__blob_html_haml__931798590182255399_104045860'
  app/views/projects/blob/show.html.haml:5:in `_app_views_projects_blob_show_html_haml___1590138917233534051_105476800'
```

I can reproduce on gitlab.com

**Comment by JonathonReinhart** [comment]
What does "when not connected" mean?

**Comment by Eijebong** [comment]
Offline.
