### ISSUE TITLE
PG::Error: ERROR: null value in column "developers_can_push" violates not-null constraint

### ISSUE THREAD

**Issue by Bitplaces-Veit** [gitlabhq/gitlabhq#8780]
After converting from standalone MySQL with 7.7.1 to Omnibus pgSQL 7.7.1, then 7.7.2, following "Upgrading from non-Omnibus MySQL to an Omnibus installation (version 6.8+)" at https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/update.md

```
2015-02-11_18:11:24.13470 2015-02-11T18:11:24Z 10734 TID-cjifg PostReceive JID- INFO: start
2015-02-11_18:11:24.24782 2015-02-11T18:11:24Z 10734 TID-cjifg PostReceive JID- INFO: fail: 0.113 sec
2015-02-11_18:11:24.24866 2015-02-11T18:11:24Z 10734 TID-cjifg WARN: {"class"=>"PostReceive", "args"=>["/data/gitlab/git-data/repositories/veit.nachtmann/test321.git", "key-83", "0000000000000000000000000000000000000000 0679a15c0106cc1dcb9e273b49f189913451b70d refs/heads/master\n"]}
2015-02-11_18:11:24.24884 2015-02-11T18:11:24Z 10734 TID-cjifg WARN: PG::Error: ERROR: null value in column "developers_can_push" violates not-null constraint
2015-02-11_18:11:24.24885 DETAIL: Failing row contains (13, 147, master, 2015-02-11 18:11:24.245914+00, 2015-02-11 18:11:24.245914+00, null).
2015-02-11_18:11:24.24885 : INSERT INTO "protected_branches" ("created_at", "name", "project_id", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
2015-02-11_18:11:24.24894 2015-02-11T18:11:24Z 10734 TID-cjifg WARN: /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:827:in `get_last_result'
2015-02-11_18:11:24.24894 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:827:in `block in exec_cache'
2015-02-11_18:11:24.24894 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
2015-02-11_18:11:24.24895 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-02-11_18:11:24.24895 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
2015-02-11_18:11:24.24895 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:824:in `exec_cache'
2015-02-11_18:11:24.24895 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `exec_query'
2015-02-11_18:11:24.24896 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:180:in `exec_insert'
2015-02-11_18:11:24.24896 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:105:in `insert'
2015-02-11_18:11:24.24896 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
2015-02-11_18:11:24.24897 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation.rb:64:in `insert'
2015-02-11_18:11:24.24897 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/persistence.rb:502:in `create_record'
2015-02-11_18:11:24.24897 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/attribute_methods/dirty.rb:87:in `create_record'
2015-02-11_18:11:24.24897 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/callbacks.rb:306:in `block in create_record'
2015-02-11_18:11:24.24898 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
2015-02-11_18:11:24.24899 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/callbacks.rb:306:in `create_record'
2015-02-11_18:11:24.24899 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/timestamp.rb:57:in `create_record'
2015-02-11_18:11:24.24899 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/persistence.rb:482:in `create_or_update'
2015-02-11_18:11:24.24899 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
2015-02-11_18:11:24.24899 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
2015-02-11_18:11:24.24899 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
2015-02-11_18:11:24.24900 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2015-02-11_18:11:24.24900 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `call'
2015-02-11_18:11:24.24900 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `run_callbacks'
2015-02-11_18:11:24.24900 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/callbacks.rb:302:in `create_or_update'
2015-02-11_18:11:24.24901 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/persistence.rb:103:in `save'
2015-02-11_18:11:24.24901 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/validations.rb:51:in `save'
2015-02-11_18:11:24.24901 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
2015-02-11_18:11:24.24901 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
2015-02-11_18:11:24.24901 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
2015-02-11_18:11:24.24902 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `transaction'
2015-02-11_18:11:24.24903 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:208:in `transaction'
2015-02-11_18:11:24.24904 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
2015-02-11_18:11:24.24904 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:268:in `block in save'
2015-02-11_18:11:24.24904 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
2015-02-11_18:11:24.24904 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:267:in `save'
2015-02-11_18:11:24.24904 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:40:in `insert_record'
2015-02-11_18:11:24.24905 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:462:in `block (2 levels) in create_record'
2015-02-11_18:11:24.24905 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
2015-02-11_18:11:24.24905 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:460:in `block in create_record'
2015-02-11_18:11:24.24905 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
2015-02-11_18:11:24.24906 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
2015-02-11_18:11:24.24906 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
2015-02-11_18:11:24.24906 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
2015-02-11_18:11:24.24907 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:208:in `transaction'
2015-02-11_18:11:24.24907 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:167:in `transaction'
2015-02-11_18:11:24.24907 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:459:in `create_record'
2015-02-11_18:11:24.24907 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:137:in `create'
2015-02-11_18:11:24.24908 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_proxy.rb:285:in `create'
2015-02-11_18:11:24.24908 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:33:in `execute'
2015-02-11_18:11:24.24908 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:39:in `block in perform'
2015-02-11_18:11:24.24908 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:26:in `each'
2015-02-11_18:11:24.24908 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:26:in `perform'
2015-02-11_18:11:24.24908 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
2015-02-11_18:11:24.24909 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:122:in `call'
2015-02-11_18:11:24.24909 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
2015-02-11_18:11:24.24909 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sidekiq_middleware/memory_killer.rb:16:in `call'
2015-02-11_18:11:24.24909 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-02-11_18:11:24.24909 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2015-02-11_18:11:24.24910 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-02-11_18:11:24.24910 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
2015-02-11_18:11:24.24910 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-02-11_18:11:24.24911 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2015-02-11_18:11:24.24911 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/logging.rb:22:in `with_context'
2015-02-11_18:11:24.24911 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2015-02-11_18:11:24.24912 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-02-11_18:11:24.24912 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:127:in `call'
2015-02-11_18:11:24.24912 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/middleware/chain.rb:127:in `invoke'
2015-02-11_18:11:24.24912 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
2015-02-11_18:11:24.24913 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:108:in `stats'
2015-02-11_18:11:24.24913 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:47:in `block in process'
2015-02-11_18:11:24.24913 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:86:in `do_defer'
2015-02-11_18:11:24.24914 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.8/lib/sidekiq/processor.rb:37:in `process'
2015-02-11_18:11:24.24914 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2015-02-11_18:11:24.24914 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2015-02-11_18:11:24.24914 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
2015-02-11_18:11:24.24914 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2015-02-11_18:11:24.24914 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2015-02-11_18:11:24.24915 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2015-02-11_18:11:24.24915 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

**Comment by Bitplaces-Veit** [comment]
I just fixed it.
apparently the pgsql DB converter script is insufficient, the default value was not created.

to create it:
```
# su - gitlab-psql
$ /opt/gitlab/embedded/bin/psql gitlabhq_production

gitlabhq_production=# alter table protected_branches alter developers_can_push set default false;
ALTER TABLE
\q
```
