### ISSUE TITLE
Post upgrade - 500 errors when viewing previous merge requests.

### ISSUE THREAD

**Issue by mattseymour** [gitlabhq/gitlabhq#8824]
I have been updating gitlab from 6.6 to 7.7 and whilst the process has been interesting I have come across the following problem with merge requests. All merge requests created in Gitlab 6.6 when migrated now result in a 500 error with the following trace.

```
Started GET "/account/project/merge_requests/59" for 127.0.0.1 at 2015-02-19 15:49:20 +0000
Processing by Projects::MergeRequestsController#show as HTML
  Parameters: {"project_id"=>"account/project", "id"=>"59"}
Completed 500 Internal Server Error in 63ms

Module::DelegationError (MergeRequest#commits delegated to merge_request_diff.commits, but
merge_request_diff is nil: #<MergeRequest id: 81, target_branch: "develop", source_branch: "develop",
source_project_id: 18, author_id: 6, assignee_id: nil, title: "Develop", created_at: "2015-01-09
17:44:55", updated_at: "2015-01-13 10:16:57", milestone_id: nil, state: "merged", merge_status:
"unchecked", target_project_id: 7, iid: 59, description: "", position: 0, locked_at: nil>):
  app/models/merge_request.rb:39:in `rescue in commits'
  app/models/merge_request.rb:39:in `commits'
  app/controllers/projects/merge_requests_controller.rb:195:in `validates_merge_request'
```

System information:
```
System information
System:		Ubuntu 12.04
Current User:	git
Using RVM:	no
Ruby Version:	2.1.4p265
Gem Version:	2.2.1
Bundler Version:1.5.3
Rake Version:	10.3.2
Sidekiq Version:2.17.8

GitLab information
Version:	7.7.2
Revision:	bd98290
Directory:	/opt/gitlab/embedded/service/gitlab-rails
DB Adapter:	postgresql
URL:		http://aserver
HTTP Clone URL:	http://aserver/some-project.git
SSH Clone URL:	git@aserver:some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.4.2
Repositories:	/var/opt/gitlab/git-data/repositories
Hooks:		/opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:		/opt/gitlab/embedded/bin/git

```

**Comment by mattseymour** [comment]
Note: this is does not appear to be a duplicate of #8732 or #8717

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
