### ISSUE TITLE
No such middleware to insert before: ActionDispatch::Static

### ISSUE THREAD

**Issue by argosback** [gitlabhq/gitlabhq#8837]
I'm updating from 7.7-stable to 7.8-stable, the problem start on **4. Install libs, migrations, etc** (Run database migrations)

Ouput:

```
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production --trace
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/fog-core-1.21.1/lib/fog/core/collection.rb:148: warning: circular argument reference - filters
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
No such middleware to insert before: ActionDispatch::Static
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/stack.rb:125:in `assert_index'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/stack.rb:101:in `swap'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/configuration.rb:68:in `block in merge_into'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/configuration.rb:67:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/configuration.rb:67:in `merge_into'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/engine.rb:497:in `app'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
/usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
/usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/application.rb:288:in `initialize!'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `method_missing'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/application.rb:264:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/application.rb:367:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
```

**Comment by axilleas** [comment]
There is a fix that will be pushed as stated in https://gitlab.com/gitlab-org/gitlab-ce/issues/1115
