### ISSUE TITLE
Failing with EACCES when precompiling assets

### ISSUE THREAD

**Issue by perfaram** [gitlabhq/gitlabhq#8888]
## Failing with EACCES when precompiling assets
When trying to precompile assets on GitLab 7.8.1, I get errors (see below). When trying to do so on 7.7.1 (so, before I update), I got no errors. Thus making this issue either a regression or a Omnibus failure.

### Setup
I'm running a GitLab omnibus-type install on DigitalOcean (RAM 2Gb, 2 cores, 40Gb SSD). I successfully updated it from 7.7.1 to 7.8.1.

### Issue
After I made some tweaking in the app/assets, I tried to recompile the assets - but I can't.
Specifically, when I run  ``gitlab-rake assets:precompile RAILS_ENV=production``, I get 
```
root@Gitlab:~# gitlab-rake assets:precompile RAILS_ENV=production --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
I, [2015-02-28T01:59:07.508402 #17847]  INFO -- : Writing /opt/gitlab/embedded/service/gitlab-rails/public/assets/application-28ec99999307bab87f734e979f6f5ee2.css
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /opt/gitlab/embedded/service/gitlab-rails/public/assets/application-28ec99999307bab87f734e979f6f5ee2.css+
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:146:in `initialize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:146:in `open'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:146:in `write_to'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:134:in `block in compile'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61:in `block (3 levels) in define'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `load'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```
When trying with sudo : 
```
root@Gitlab:~# sudo gitlab-rake assets:precompile RAILS_ENV=production --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
I, [2015-02-28T02:00:52.723610 #17994]  INFO -- : Writing /opt/gitlab/embedded/service/gitlab-rails/public/assets/application-28ec99999307bab87f734e979f6f5ee2.css
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /opt/gitlab/embedded/service/gitlab-rails/public/assets/application-28ec99999307bab87f734e979f6f5ee2.css+
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:146:in `initialize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:146:in `open'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:146:in `write_to'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:134:in `block in compile'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61:in `block (3 levels) in define'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/gitlab/embedded/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `load'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```
When running ``sudo -u gitlab -H bundle exec rake gitlab:check RAILS_ENV=production`` : 
```
root@Gitlab:~# sudo -u gitlab -H bundle exec rake gitlab:check RAILS_ENV=production
sudo: unknown user: gitlab
sudo: unable to initialize policy plugin
```

Thanks !

**Comment by perfaram** [comment]
Note that there's no GitLab user on my server, there is however a Git user.
When ``sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production``, I get a "Could not locate gemfile" error.

**Comment by perfaram** [comment]
Okay, just had to chmod -R 1777 on public/assets (see : http://stackoverflow.com/questions/28760917/gitlab-rake-assetsprecompile-rails-env-production-fails-with-permission-error/28786777#28786777)

**Comment by Heni-ghodbane** [comment]
@perfaram if you got this "Could not locate gemfile" error you must go to /home/git/gitlab and run the backup cmd and it will work

**Comment by nyxee** [comment]
I got this error when i had **invalid characters** in my filename. i changed to a simple file-name without spaces and everything worked.
