### ISSUE TITLE
Unable to assign tags

### ISSUE THREAD

**Issue by n-studio** [gitlabhq/gitlabhq#8906]
I'm using GitLab 7.8.1 "e2d785c".
I get a 500 error when I try to assign a label to an issue.
The logs say:

```
Started PATCH "/me/yanda/issues/4" for 183.77.128.223 at 2015-03-03 10:43:59 +0900
Processing by Projects::IssuesController#update as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"KQGrqNcip9IX/ag6z2Hhiyfnk9ru5BDsHrLP2OO9udM=", "issue"=>{"title"=>"Admin interface from scratch", "description"=>"", "assignee_id"=>"1", "label_ids"=>["", "52"]}, "project_id"=>"me/yanda", "id"=>"4"}
Completed 500 Internal Server Error in 207ms

NoMethodError (undefined method `name' for nil:NilClass):
  app/services/issues/update_service.rb:19:in `execute'
  app/controllers/projects/issues_controller.rb:75:in `update'
```

**Comment by n-studio** [comment]
More info from the rails console
```
irb(main):011:0> @issue.label_ids = ["52"]
NoMethodError: undefined method `name' for nil:NilClass
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:79:in `cached_counter_attribute_name'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:75:in `has_cached_counter?'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/has_many_association.rb:83:in `update_counter'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/has_many_through_association.rb:65:in `insert_record'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:522:in `block (2 levels) in concat_records'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:521:in `block in concat_records'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:519:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:519:in `concat_records'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/has_many_through_association.rb:42:in `concat_records'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:153:in `block in concat'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:208:in `transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:167:in `transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:153:in `concat'
... 4 levels...
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `block in transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:219:in `within_new_transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/transactions.rb:208:in `transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:167:in `transaction'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:362:in `replace'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/collection_association.rb:61:in `ids_writer'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activerecord-4.1.1/lib/active_record/associations/builder/collection_association.rb:76:in `label_ids='
	from (irb):11
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
irb(main):012:0> Label.find(52)
=> #<Label id: 52, title: "Feature", color: "#5CB85C", project_id: 47, created_at: "2015-03-03 01:43:52", updated_at: "2015-03-03 01:43:52">
irb(main):013:0> 

```

**Comment by n-studio** [comment]
https://github.com/activescaffold/active_scaffold/issues/380

It seems to be a Ruby 2.2 related issue.

**Comment by n-studio** [comment]
Duplicate of #8567
