### ISSUE TITLE
Unicorn: unexpected keyword_end, expecting end-of-input

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#8932]
**Information:**
I just updated my gitlab up to 1475cb9aaae75d37719c8eac92f9483bb2fde416. And run upgrade process. Starting gitlab failed and giving this error from log.

**Logs:**
```
I, [2015-03-08T10:52:30.342269 #996]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require': /home/git/gitlab/vendor/bundle/ruby/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service/client.rb:17: syntax error, unexpected ',' (SyntaxError)
...oad_files(files, project_slug:, branch_name:, commit_sha:)
...                               ^
/home/git/gitlab/vendor/bundle/ruby/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service/client.rb:60: syntax error, unexpected keyword_end, expecting end-of-input
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service/pusher.rb:1:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/gemnasium-gitlab-service-0.2.5/lib/gemnasium/gitlab_service.rb:2:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/app/models/project_services/gemnasium_service.rb:20:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:348:in `require_or_load'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:307:in `depend_on'
        from /home/git/gitlab/vendor/bundle/ruby/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:225:in `require_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/engine.rb:467:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/engine.rb:467:in `block in eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/engine.rb:465:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/engine.rb:465:in `eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/engine.rb:346:in `eager_load!'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/share/ruby/tsort.rb:150:in `block in tsort_each'
        from /usr/share/ruby/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /usr/share/ruby/tsort.rb:219:in `each_strongly_connected_component_from'
        from /usr/share/ruby/tsort.rb:182:in `block in each_strongly_connected_component'
        from /usr/share/ruby/tsort.rb:180:in `each'
        from /usr/share/ruby/tsort.rb:180:in `each_strongly_connected_component'
        from /usr/share/ruby/tsort.rb:148:in `tsort_each'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
        from /home/git/gitlab/vendor/bundle/ruby/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
        from /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
        from config.ru:13:in `require'
        from config.ru:13:in `block in <main>'
        from /home/git/gitlab/vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /home/git/gitlab/vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/lib/unicorn.rb:48:in `eval'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/lib/unicorn.rb:48:in `block in builder'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/bin/unicorn_rails:139:in `call'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:722:in `call'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:722:in `build_app!'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:140:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/gems/unicorn-4.6.3/bin/unicorn_rails:209:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/bin/unicorn_rails:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/bin/unicorn_rails:23:in `<main>'
```

**Comment by Razer6** [comment]
@gravis Can you take a look? Seems related to the gemansium update. Otherwise I've to revert the commit.

**Comment by jameswritescode** [comment]
I talked to @MrKeiKun about this on IRC and it's because the gemnasium service is using ruby 2.1 specific syntax in the parameters of the `upload_files` method.

**Comment by Razer6** [comment]
Thanks for that update. What ruby is @mrkeikun using? Gitlab requires 2.1.5

**Comment by jameswritescode** [comment]
He was using 2.0.X, after he upgraded to 2.1.5 and everything was fine.

**Comment by gravis** [comment]
Ok, so I understand we don't have anything to update on our side, right?

**Comment by Razer6** [comment]
@MrKeiKun Please reposnd to issues if they are fixed. @gravis Thanks, seems everything ios ok :)

**Comment by MrKeiKun** [comment]
oh yeah
unable to update issue due to
no internet connection a whole day yesterday :3
