### ISSUE TITLE
ActionView::Template::Error for project pages after update to v7.8.2 (from 7.7.1)

### ISSUE THREAD

**Issue by nvdk** [gitlabhq/gitlabhq#8940]
Since upgrading to v7.8.2 (from v7.7.1) we encounter the following issue for some (but not all) project pages: A 500 error is returned and the following error is raised in the logs. This seems related to #8864, but another error is raised. No errors were raised during migration.

```
Started GET "/sco/sco-documentation" for 127.0.0.1 at 2015-03-10 08:55:39 +0000
Processing by ProjectsController#show as HTML
Parameters: {"id"=>"sco/sco-documentation"}
Completed 500 Internal Server Error in 486ms
ActionView::Template::Error (The single-table inheritance mechanism failed to locate the subclass: 'GitlabIssueTrackerService'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Service.inheritance_column to use another column for that information.):
65: - else
66: #{link_to @project.owner_name, @project.owner}
67:
68: - @project.ci_services.each do |ci_service|
69: - if ci_service.active? && ci_service.respond_to?(:builds_path)
70: - if ci_service.respond_to?(:status_img_path)
71: = link_to ci_service.builds_path do
app/models/project.rb:327:in `ci_services'
app/views/projects/show.html.haml:68:in `_app_views_projects_show_html_haml__4182785123250870404_32490220'
app/controllers/projects_controller.rb:72:in `block (2 levels) in show'
app/controllers/projects_controller.rb:65:in `show'
```

**Comment by nvdk** [comment]
sorry, seems to be related to our setup and not gitlab
