### ISSUE TITLE
Omnibus-ctl doesn't work

### ISSUE THREAD

**Issue by Vrael** [gitlabhq/gitlabhq#9072]
I have installed GitLab following the guide: https://about.gitlab.com/downloads/ but in the step 3:
`sudo gitlab-ctl reconfigure` I get the message:

```shell
/opt/gitlab/embedded/bin/omnibus-ctl: 9: /opt/gitlab/embedded/bin/omnibus-ctl: require: not found
/opt/gitlab/embedded/bin/omnibus-ctl: 11: /opt/gitlab/embedded/bin/omnibus-ctl: version: not found
/opt/gitlab/embedded/bin/omnibus-ctl: 15: /opt/gitlab/embedded/bin/omnibus-ctl: Syntax error: "(" unexpected (expecting "then")
```

I have installed ruby 2.2.1p85 in my pc and if I try to run:
`ruby /opt/gitlab/embedded/bin/omnibus-ctl`
This is the message:
``` shell
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find omnibus-ctl (>= 0) amongst [] (Gem::LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
	from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
	from /opt/gitlab/embedded/bin/omnibus-ctl:22:in `<main>'
```

**Comment by Razer6** [comment]
For the omnibus package please head over to the omnibus repository: https://gitlab.com/gitlab-org/omnibus-gitlab
