### ISSUE TITLE
7.9.1 ActionView::MissingTemplate caused by Google bot indexing

### ISSUE THREAD

**Issue by artworx** [gitlabhq/gitlabhq#9087]
log:

```
Started GET "/asddu/wee/refs/b543963c1364e6e7a1f4f37bd02c5e50e3351b8b/logs_tree/app/Models" for 66.249.64.106 at 2015-03-29 06:48:58 +0300
Processing by Projects::RefsController#logs_tree as HTML
  Parameters: {"project_id"=>"asddu/wee", "id"=>"b543963c1364e6e7a1f4f37bd02c5e50e3351b8b", "path"=>"app/Models"}
Completed 500 Internal Server Error in 30ms

ActionView::MissingTemplate (Missing template projects/refs/logs_tree, projects/application/logs_tree, application/logs_tree with {:locale=>[:en], :formats=>[:ht
ml], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :haml]}. Searched in:
  * "/home/git/gitlab/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/semantic-ui-sass-1.8.0.0/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/kaminari-0.15.1/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.1.0/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/app/views"
):
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/path_set.rb:46:in `find'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/lookup_context.rb:124:in `find'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:41:in `determine_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/template_renderer.rb:8:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:99:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:82:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/rendering.rb:25:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/local/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'

```

I seems to be a

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
