### ISSUE TITLE
6.2.3 to 7.8.1 migration error 

### ISSUE THREAD

**Issue by maestromani** [gitlabhq/gitlabhq#9162]
Error while executing sudo -u git -H /opt/gitlab/ruby/bin/bundle exec rake db:migrate RAILS_ENV=production --trace.

Following is the error message...

== 20140903115954 MigrateToNewShell: migrating ================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Failed to rewrite gitlab-shell hooks in repositories/opt/gitlab/apps/gitlab/htdocs/db/migrate/20140903115954_migrate_to_new_shell.rb:7:in `change'
/opt/gitlab/apps/gitlab/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:595:in `exec_migration'
/opt/gitlab/apps/gitlab/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'

**Comment by maestromani** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/commit/4803af45dfbd516890b3ab31fa55b93009174d63 didn't help too.
