### ISSUE TITLE
LoadError: cannot load such file -- krb5_auth

### ISSUE THREAD

**Issue by programacion-web** [gitlabhq/gitlabhq#9170]
Hi friends,

I'm trying to run Gitlab in OpenBSD.

I am also documenting it in a document that I want to post to the wiki.

By using the following command, I get an error.

```bash
# sudo -u git -H /usr/local/lib/ruby/gems/2.1/gems/bundler-1.9.4/bin/bundle exec rake gitlab:setup RAILS_ENV=production 
rake aborted!
LoadError: cannot load such file -- krb5_auth
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/omniauth-kerberos-0.2.0/lib/omniauth/strategies/kerberos.rb:2:in `<top (required)>'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/var/www/git/gitlab/vendor/bundle/ruby/2.1/gems/omniauth-kerberos-0.2.0/lib/omniauth-kerberos.rb:1:in `<top (required)>'
/var/www/git/gitlab/config/application.rb:6:in `<top (required)>'
/var/www/git/gitlab/Rakefile:5:in `require'
/var/www/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

I try to install timfel-krb5-auth, I get an error

```bash
# gem install timfel-krb5-auth
Building native extensions.  This could take a while...
ERROR:  Error installing timfel-krb5-auth:
        ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby21 extconf.rb
checking for main() in -lc... yes
checking for krb5_init_context() in -lkrb5... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/ruby21
        --with-krb5_auth-dir
        --without-krb5_auth-dir
        --with-krb5_auth-include
        --without-krb5_auth-include=${krb5_auth-dir}/include
        --with-krb5_auth-lib
        --without-krb5_auth-lib=${krb5_auth-dir}/lib
        --with-clib
        --without-clib
        --with-krb5lib
        --without-krb5lib
extconf.rb:7:in `<main>': Cannot find krb5 library (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.1/gems/timfel-krb5-auth-0.8.3 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.1/extensions/x86_64-openbsd/2.1/timfel-krb5-auth-0.8.3/gem_make.out
```
How I can fix this?

thanks
----edit----
I think OpenBSD no longer use kerberos.

I'm not sure if it has to do. the GEM with kerberos but I found this:
(like http://undeadly.org/cgi?action=article&sid=20140425065910)

**Comment by Razer6** [comment]
Kerberos is now in a dedicated group to avoid such problems.
