### ISSUE TITLE
7.8.4 - no new commits in Dashboard

### ISSUE THREAD

**Issue by Kami-no** [gitlabhq/gitlabhq#9171]
New commits do not appear in Dashboard but at pull you get new commits.

Updated from 7.8.1
> repository https://github.com/fritteli/gentoo-overlay/
> using systemd + MySQL
> pre 7.8.4 versions were in slot 6 and dir /opt/gitlab-6
> 7.8.4+ not in slot and in dir /opt/gitlab

Have some WARN in log:

```sh
$ grep WARN /var/log/gitlab/sidekiq.log
2015-04-18T23:25:03.576Z 1061 TID-ndyuk WARN: {"class"=>"PostReceive", "args"=>["/var/lib/git/repositories/zininda/oxford.git", "key-5", "MzQ4NWJkY2FmOThlMjFiNWM2NDczOTFmYjJlOTkwM2IwODYzYzUyZCA3MDVh\nNDNlNzIwZDI5YTRhNmIzZTM0ZjhhYmI0ODYwNGM5NDUxZjZjIHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-04-18T23:25:03.576Z 1061 TID-ndyuk WARN: undefined method `include?' for nil:NilClass
2015-04-18T23:25:03.576Z 1061 TID-ndyuk WARN: /opt/gitlab-6/app/services/git_push_service.rb:127:in `push_to_branch?'
2015-04-22T13:17:46.101Z 17054 TID-pasuw WARN: {"class"=>"PostReceive", "args"=>["/var/lib/git/repositories/zininda/oxford.git", "key-5", "NzA1YTQzZTcyMGQyOWE0YTZiM2UzNGY4YWJiNDg2MDRjOTQ1MWY2YyA3MjZj\nMTU0MDBhYTExNGYyMTVlNDIwZWJiYmVkNDRhMGU5OTk5MWU0IHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-04-22T13:17:46.101Z 17054 TID-pasuw WARN: undefined method `include?' for nil:NilClass
2015-04-22T13:17:46.101Z 17054 TID-pasuw WARN: /opt/gitlab/app/services/git_push_service.rb:127:in `push_to_branch?'
2015-04-22T13:38:05.967Z 17054 TID-pasuw WARN: {"class"=>"PostReceive", "args"=>["/var/lib/git/repositories/zininda/oxford.git", "key-5", "NzI2YzE1NDAwYWExMTRmMjE1ZTQyMGViYmJlZDQ0YTBlOTk5OTFlNCA0N2Iw\nMDgxYjAyNzViMmM4MTc0ZGNjNjI1NTViNTE4YTE0ODBlMWJkIHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-04-22T13:38:05.967Z 17054 TID-pasuw WARN: undefined method `include?' for nil:NilClass
2015-04-22T13:38:05.967Z 17054 TID-pasuw WARN: /opt/gitlab/app/services/git_push_service.rb:127:in `push_to_branch?'
2015-04-22T13:39:36.851Z 17054 TID-rkbys WARN: {"class"=>"PostReceive", "args"=>["/var/lib/git/repositories/zininda/oxford.git", "key-5", "NDdiMDA4MWIwMjc1YjJjODE3NGRjYzYyNTU1YjUxOGExNDgwZTFiZCA5NGVh\nY2M1MGFjZmUyMjdmY2EwMjkyYjc3MzBhMGZhNjRiN2Y3YjE5IHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-04-22T13:39:36.851Z 17054 TID-rkbys WARN: undefined method `include?' for nil:NilClass
2015-04-22T13:39:36.851Z 17054 TID-rkbys WARN: /opt/gitlab/app/services/git_push_service.rb:127:in `push_to_branch?'
2015-04-22T13:42:44.811Z 17054 TID-rkbys WARN: {"class"=>"PostReceive", "args"=>["/var/lib/git/repositories/zininda/oxford.git", "key-5", "OTRlYWNjNTBhY2ZlMjI3ZmNhMDI5MmI3NzMwYTBmYTY0YjdmN2IxOSBmNmVl\nZjQ2MzdhNDQ4MjY1ODI5Y2IwYjc4OTQyODMwZTRhMmViYmMxIHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-04-22T13:42:44.811Z 17054 TID-rkbys WARN: undefined method `include?' for nil:NilClass
2015-04-22T13:42:44.811Z 17054 TID-rkbys WARN: /opt/gitlab/app/services/git_push_service.rb:127:in `push_to_branch?'
2015-04-22T22:11:02.700Z 750 TID-px28w WARN: {"class"=>"PostReceive", "args"=>["/var/lib/git/repositories/zininda/oxford.git", "key-5", "ZjZlZWY0NjM3YTQ0ODI2NTgyOWNiMGI3ODk0MjgzMGU0YTJlYmJjMSA4ZTcz\nNDI2ZjJlOTczZDczNjc5ZjBmNzFkODZmMmJiMjAzYzNmM2JjIHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-04-22T22:11:02.700Z 750 TID-px28w WARN: undefined method `include?' for nil:NilClass
2015-04-22T22:11:02.700Z 750 TID-px28w WARN: /opt/gitlab/app/services/git_push_service.rb:127:in `push_to_branch?'
```

```sh
$ bundle exec rake gitlab:env:info RAILS_ENV=production

System information
System:		Gentoo n/a
Current User:	git
Using RVM:	no
Ruby Version:	2.0.0p645
Gem Version:	2.2.2
Bundler Version:1.7.13
Rake Version:	10.3.2
Sidekiq Version:3.3.0

GitLab information
Version:	7.8.4
Revision:	fatal: Not a git repository (or any of the parent directories): .git
Directory:	/opt/gitlab
DB Adapter:	mysql2
URL:		
HTTP Clone URL:	
SSH Clone URL:	
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.6.0
Repositories:	/var/lib/git/repositories/
Hooks:		/usr/share/gitlab-shell/hooks/
Git:		/usr/bin/git
```

```sh
$ bundle exec rake gitlab:check RAILS_ENV=production
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.5.4 ? ... OK (2.6.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
#### ... ok
#### ... ok
Running /usr/share/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/var/lib/git/repositories: OK
	/var/lib/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.17
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... no
  Try fixing it:
  Install the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
Init script up-to-date? ... can't check because of previous errors
projects have namespace: ... 
### ... yes
### ... yes
Projects have satellites? ... 
### ... yes
### ... yes
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.0.0)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (2.0.5)

Checking GitLab ... Finished
```

**Comment by Kami-no** [comment]
https://github.com/fritteli/gentoo-overlay/issues/17

**Comment by Kami-no** [comment]
More details:
* Dashboard - no updates;
* Project-Commits - all new commits visible;

**Comment by Kami-no** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/issues/1311

**Comment by blacklizard** [comment]
+1 Same here
GitLab 7.9.4

**Comment by blacklizard** [comment]
Also the same in GitLab 7.10.0

**Comment by strobe33333** [comment]
Same Here.  Also seeing:

remote: GitLab: No such project
To git@gitlab.<example>.com:<user>/testproject.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to .....

**Comment by dreis2211** [comment]
Same here

**Comment by PaulBGD** [comment]
Same with 7.10.0

**Comment by blacklizard** [comment]
@PaulBGD @dreis2211 @strobe33333 @Kami-no 

Run the following command:

stop service:
```
sudo service gitlab stop
```

then:
```
cd /home/git/gitlab/vendor
sudo -u git -H rm -r bundle
cd /home/git/gitlab/

# MySQL installations (note: the line below states '--without ... postgres')
sudo -u git -H bundle install --without development test postgres --deployment

# PostgreSQL installations (note: the line below states '--without ... mysql')
sudo -u git -H bundle install --without development test mysql --deployment
```

Execute this inside each of the repository
```
sudo -u git -H rm hooks
sudo -u git -H ln -s /home/git/gitlab-shell/hooks hooks
```
Location:
`/home/git/repositories/{namespace}/repository_name.git`

Managed to solve it

**Comment by PaulBGD** [comment]
@blacklizard Amazing! Everyone on my team thanks you.

**Comment by JoKeyser** [comment]
Same problem here, running GitLab 7.11.4.
Like @Kami-no said already,
* Dashboard - no updates
* Project-Commits - all new commits visible
* Profile-UserActivity - no updates
* Profile-CommitsCalendar - all new commits visible

The relevant log in sidekiq.log  
```
2015-08-16T19:26:06.059Z 11194 TID-oxb3mvs94 PostReceive JID- INFO: start
2015-08-16T19:26:06.302Z 11194 TID-oxb3mvs94 PostReceive JID- INFO: fail: 0.244 sec
2015-08-16T19:26:06.304Z 11194 TID-oxb3mvs94 WARN: {"class"=>"PostReceive", "args"=>["/home/git/repositories/sensorimotorlab/PaperSimulations.git", "key-1", "OTcwZTNlZjUjMCAwNDQy\nZWE5N2Y4YmUwODNmxZjM5NjBhNDNmZCAwNDQy\nZWE5N2Y4YmUwODNmODZkMZDViMjVkNWE2MWVlIHJlZnMvaGVh\nZHMvbWFzdGVyCg==\n"]}
2015-08-16T19:26:06.305Z 11194 TID-oxb3mvs94 WARN: wrong number of arguments (1 for 0)
2015-08-16T19:26:06.305Z 11194 TID-oxb3mvs94 WARN: /home/git/gitlab/app/models/commit.rb:108:in `hook_attrs'
/home/git/gitlab/lib/gitlab/push_data_builder.rb:38:in `block in build'
/home/git/gitlab/lib/gitlab/push_data_builder.rb:37:in `map'
/home/git/gitlab/lib/gitlab/push_data_builder.rb:37:in `build'
/home/git/gitlab/app/services/git_push_service.rb:109:in `build_push_data'
/home/git/gitlab/app/services/git_push_service.rb:59:in `execute'
/home/git/gitlab/app/workers/post_receive.rb:41:in `block in perform'
/home/git/gitlab/app/workers/post_receive.rb:28:in `each'
/home/git/gitlab/app/workers/post_receive.rb:28:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

What @blacklizard suggested does not help; the `hooks` in all repositories were/are linked as required.
Please let me know if you need more logs to track this down.

**Comment by JoKeyser** [comment]
For me, upgrading from 7.11.4 to 7.12-stable did not help with this issue.

Possibly this is unrelated, but when upgrading further to 7.13.4, I saw this message during `db:migrate` :  
```
git@sml:~/gitlab$ bundle exec rake db:migrate RAILS_ENV=production
rake aborted!
ArgumentError: You tried to define an enum named "dashboard" on the model "User", but this will generate a instance method "dashboard=", which is already defined by another enum.
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/enum.rb:189:in `detect_enum_conflict!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/enum.rb:93:in `block (2 levels) in enum'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/enum.rb:91:in `module_eval'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/enum.rb:91:in `block in enum'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/enum.rb:82:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/enum.rb:82:in `enum'
/home/git/gitlab/app/models/user.rb:752:in `<class:User>'
/home/git/gitlab/app/models/user.rb:66:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:348:in `require_or_load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:480:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:180:in `const_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/inflector/methods.rb:238:in `const_get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/inflector/methods.rb:238:in `block in constantize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/inflector/methods.rb:236:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/inflector/methods.rb:236:in `inject'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/inflector/methods.rb:236:in `constantize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:552:in `get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:583:in `constantize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise.rb:297:in `get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/mapping.rb:77:in `to'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/mapping.rb:72:in `modules'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/mapping.rb:89:in `ro
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/mapping.rb:156:in `d
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/mapping.rb:66:in `in
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise.rb:331:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise.rb:331:in `add_mappi
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/rails/routes.rb:221:for'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/rails/routes.rb:220:
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/lib/devise/rails/routes.rb:220:
/home/git/gitlab/config/routes.rb:301:in `block in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routinn `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routinn `eval_block'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routinn `draw'
/home/git/gitlab/config/routes.rb:4:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/block in load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsblock in load_paths'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railseach'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsload_paths'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsreload!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsblock in updater'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/5:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/5:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsupdater'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsxecute_if_updated'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsn <module:Finisher>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsnitializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsrs'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railsment!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/railssks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by stanhu** [comment]
@JoKeyser Can you include the related log? It looks to me that your earlier log doesn't quite match up with the source code for GitLab 7.11.4. It looks to me that the failure was due to a stale `commit.rb`; it seems that the version installed required that `project` be included as an argument to `hook_attrs`. This changed in [this commit](https://gitlab.com/gitlab-org/gitlab-ce/commit/27af24c1c951385bccd298c98044d57ff22ccd1c), which should have been shipped with GitLab v7.11.

**Comment by JoKeyser** [comment]
@stanhu : Great catch, this was exactly what happened. I was being an idiot during my update (to preserve my changes, I kind of just merged the new versions into my custom branch). Now it's fixed, thank you.

**Comment by Razer6** [comment]
Closing for now because seems to be fixed
