### ISSUE TITLE
ERROR: column "taggings_count" does not exist

### ISSUE THREAD

**Issue by remcoros** [gitlabhq/gitlabhq#9194]
On a fresh install of gitlab (omnibus-ce 7.10 package), I get this error when trying to save a project with a tag.

```PG::Error: ERROR: column "taggings_count" does not exist
LINE 1: UPDATE "tags" SET "taggings_count" = COALESCE("taggings_coun...
^
: UPDATE "tags" SET "taggings_count" = COALESCE("taggings_count", 0) + 1 WHERE "tags"."id" = 4
Completed 500 Internal Server Error in 208ms
ActiveRecord::StatementInvalid (PG::Error: ERROR: column "taggings_count" does not exist
LINE 1: UPDATE "tags" SET "taggings_count" = COALESCE("taggings_coun...
^
: UPDATE "tags" SET "taggings_count" = COALESCE("taggings_count", 0) + 1 WHERE "tags"."id" = 4):
app/services/projects/update_service.rb:20:in `execute'
app/controllers/projects_controller.rb:36:in `update'```

Might be due to upgrading acts-as-taggables-on here: be65373fc78ea887aa2d59ee49ae8bb14c64b084

I tried to do the database migrations myself, but I'm not really experienced with ruby.

**Comment by remcoros** [comment]
Fxied it for now by downgrading acts-as-taggable-on back to 2.4.1 manually.

**Comment by stanhu** [comment]
Thanks, this has been fixed:

https://gitlab.com/gitlab-org/gitlab-ce/commit/2f4426b7e4830f4ec9c318c944c0b53c8af261ab

ping @Razer6
