### ISSUE TITLE
centos 6 adding ssh keys fails

### ISSUE THREAD

**Issue by eworksmedia** [gitlabhq/gitlabhq#9195]
fresh install of centos 6.6 and gitlab from https://about.gitlab.com/downloads/ "CentOS 6". installed and configured successfully, however, when I try and "Add key" there's a 500 internal server error with the following output in `gitlab-ctl tail`

```
Started POST "/profile/keys" for IP_ADDR at 2015-04-24 15:43:20 -0700
Processing by Profiles::KeysController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "key"=>{"title"=>"MY_TITLE", "key"=>"MY_KEY"}}
Completed 500 Internal Server Error in 27ms

Errno::ENOENT (No such file or directory - ssh):
  lib/gitlab/popen.rb:23:in `popen'
  lib/gitlab/key_fingerprint.rb:42:in `explicit_fingerprint_algorithm?'
  lib/gitlab/key_fingerprint.rb:21:in `block in fingerprint'
  lib/gitlab/key_fingerprint.rb:15:in `fingerprint'
  app/models/key.rb:84:in `generate_fingerprint'
  app/controllers/profiles/keys_controller.rb:20:in `create'
```

**Comment by eworksmedia** [comment]
```
[root@git ~]# gitlab-rake gitlab:check
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.6.2 ? ... OK (2.6.2)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
Running /opt/gitlab/embedded/service/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/var/opt/gitlab/git-data/repositories: OK
	/var/opt/gitlab/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.2
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
Server: ldapmain
	...LDAP_USER_LIST...
Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... skipped (omnibus-gitlab has no init script)
Init script up-to-date? ... skipped (omnibus-gitlab has no init script)
projects have namespace: ... 
Projects have satellites? ... 
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.6)
Your git bin path is "/opt/gitlab/embedded/bin/git"
Git version >= 1.7.10 ? ... yes (2.0.5)
Active users: 3

Checking GitLab ... Finished
```

I see a bunch of temp files under /tmp, looks like all my attempts
```
-rw-------.  1 git         git          410 Apr 27 10:49 gitlab_key_file20150427-2128-7l5rch
-rw-------.  1 git         git          410 Apr 27 10:57 gitlab_key_file20150427-2136-1bkwhpj
-rw-------.  1 git         git          410 Apr 27 10:46 gitlab_key_file20150427-2136-1pivz7i
-rw-------.  1 git         git          410 Apr 27 10:55 gitlab_key_file20150427-2652-11tzip3
```

**Comment by Razer6** [comment]
This seems to be an omnibus error. Can you please head over to the right tracker: https://gitlab.com/gitlab-org/omnibus-gitlab

**Comment by eworksmedia** [comment]
@Razer6 sorry :) posting over there now
