### ISSUE TITLE
Sending emails via SMTP: SSL verify error

### ISSUE THREAD

**Issue by IngwiePhoenix** [gitlabhq/gitlabhq#9236]
(I posted this to Gitlab Issues before, but after a moment I realized that my issue might not be relevant just for people over there. So I will repost the very issue here also, just in case.)

I am trying to use my GMail account with my gitlab instance...but it isn't working right. My friend is trying to register and not getting a mail, and this pops up in the logs:

```
==> /var/log/gitlab/sidekiq/current <==
2015-05-02_16:24:15.76704 2015-05-02T16:24:15Z 7684 TID-64omo Devise::Async::Backend::Sidekiq JID-2eca8e14202277cfef86e171 INFO: start
2015-05-02_16:24:15.76714 2015-05-02T16:24:15Z 7684 TID-64omo Devise::Async::Backend::Sidekiq JID-2eca8e14202277cfef86e171 INFO: arguments: ["confirmation_instructions", "User", "11", "rgYxsgy8Z_cZoryYyBUS", {}]

==> /var/log/gitlab/gitlab-rails/production.log <==

Sent mail to [...]@gmail.com (103.9ms)

==> /var/log/gitlab/sidekiq/current <==
2015-05-02_16:24:15.88372 2015-05-02T16:24:15Z 7684 TID-64omo Devise::Async::Backend::Sidekiq JID-2eca8e14202277cfef86e171 INFO: fail: 0.117 sec
2015-05-02_16:24:15.88452 2015-05-02T16:24:15Z 7684 TID-64omo WARN: {"retry"=>true, "queue"=>"mailer", "class"=>"Devise::Async::Backend::Sidekiq", "args"=>["confirmation_instructions", "User", "11", "rgYxsgy8Z_cZoryYyBUS", {}], "jid"=>"2eca8e14202277cfef86e171", "enqueued_at"=>1430583819.1617012, "error_message"=>"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed", "error_class"=>"OpenSSL::SSL::SSLError", "failed_at"=>"2015-05-02 16:23:39 UTC", "retry_count"=>1, "retried_at"=>2015-05-02 16:24:15 UTC}
2015-05-02_16:24:15.88454 2015-05-02T16:24:15Z 7684 TID-64omo WARN: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
2015-05-02_16:24:15.88459 2015-05-02T16:24:15Z 7684 TID-64omo WARN: /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:586:in `connect'
2015-05-02_16:24:15.88460 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:586:in `tlsconnect'
2015-05-02_16:24:15.88461 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:563:in `do_start'
2015-05-02_16:24:15.88462 /opt/gitlab/embedded/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
2015-05-02_16:24:15.88462 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
2015-05-02_16:24:15.88463 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
2015-05-02_16:24:15.88463 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:232:in `block in deliver'
2015-05-02_16:24:15.88464 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:527:in `block in deliver_mail'
2015-05-02_16:24:15.88465 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
2015-05-02_16:24:15.88465 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2015-05-02_16:24:15.88468 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
2015-05-02_16:24:15.88469 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:525:in `deliver_mail'
2015-05-02_16:24:15.88469 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:232:in `deliver'
2015-05-02_16:24:15.88470 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-async-0.9.0/lib/devise/async/backend/base.rb:16:in `perform'
2015-05-02_16:24:15.88470 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
2015-05-02_16:24:15.88471 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `call'
2015-05-02_16:24:15.88471 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
2015-05-02_16:24:15.88472 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sidekiq_middleware/arguments_logger.rb:6:in `call'
2015-05-02_16:24:15.88472 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-05-02_16:24:15.88473 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2015-05-02_16:24:15.88474 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-05-02_16:24:15.88474 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
2015-05-02_16:24:15.88475 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-05-02_16:24:15.88475 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2015-05-02_16:24:15.88476 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/logging.rb:22:in `with_context'
2015-05-02_16:24:15.88476 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2015-05-02_16:24:15.88477 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
2015-05-02_16:24:15.88477 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `call'
2015-05-02_16:24:15.88478 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/middleware/chain.rb:127:in `invoke'
2015-05-02_16:24:15.88479 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
2015-05-02_16:24:15.88479 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:105:in `stats'
2015-05-02_16:24:15.88480 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:47:in `block in process'
2015-05-02_16:24:15.88480 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:86:in `do_defer'
2015-05-02_16:24:15.88481 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-2.17.0/lib/sidekiq/processor.rb:37:in `process'
2015-05-02_16:24:15.88481 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
2015-05-02_16:24:15.88482 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
2015-05-02_16:24:15.88482 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
2015-05-02_16:24:15.88484 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
2015-05-02_16:24:15.88484 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
2015-05-02_16:24:15.88485 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
2015-05-02_16:24:15.88486 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
```

Can anyone tell me how to fix this? This is in my config.rb:
```ruby
gitlab_rails['gitlab_email_from'] = "Ingwie's Gitlab <ingwie2000@gmail.com>"
gitlab_rails['gitlab_email_reply_to'] = 'ingwie2000@gmail.com'

gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = "smtp.gmail.com"
gitlab_rails['smtp_port'] = 25
gitlab_rails['smtp_user_name'] = "ingwie2000@gmail.com"
gitlab_rails['smtp_password'] = "[...]"
gitlab_rails['smtp_domain'] = "smtp.gmail.com"
gitlab_rails['smtp_authentication'] = "login"
gitlab_rails['smtp_enable_starttls_auto'] = true
gitlab_rails['smtp_tls'] = false
gitlab_rails['smtp_openssl_verify_mode'] = 'client_once'
```

My Gitlab:
```
$ dpkg -l | grep gitlab
ii  gitlab        7.2.1-omnibus-1        amd64        The full stack of gitlab
```

**Comment by duper51** [comment]
This problem is most likely related to your server's CA bundle. According to that log, when the client attempted to connect to the IMAP server, the IMAP server's SSL certificate failed to verify. Try updating your server's CA bundle.

**Comment by stanhu** [comment]
It's more complicated than that. GitLab ships with a recent CA bundle, but right now you have to specify the CA bundle in the SMTP configuration due to an issue with defaults not being set properly. See:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1558#note_1183160

**Comment by Razer6** [comment]
Closing this here as a duplicate. Since this is related to the omnibus package discuss this issue on that issue tracker.
