### ISSUE TITLE
[7.10] rake assets:clean target fails

### ISSUE THREAD

**Issue by stefan-it** [gitlabhq/gitlabhq#9258]
Hi,

using the latest *7.10.1* and *7.10.2* version of GitLab caused an error when executing the `rake assets:clean` command. I deleted the whole `vendor` directory and did a fresh `bundle install --without development test postgres --deployment`.

After that I executed:

```bash
bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production
```

And an error occurs:

```bash
bundle exec rake assets:clean assets:precompile cache:clear RAILS_ENV=production
rake aborted!
Sprockets::FileNotFound: couldn't find file 'jquery.cookie'
  (in /gitlab/git/gitlab/app/assets/javascripts/application.js.coffee:10)
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:106:in `resolve'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:146:in `require_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/directive_processor.rb:217:in `process_require_directive'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/directive_processor.rb:167:in `block in process_directives'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/directive_processor.rb:165:in `each'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/directive_processor.rb:165:in `process_directives'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/directive_processor.rb:99:in `evaluate'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:37:in `init_with'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/asset.rb:24:in `from_hash'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:54:in `cache_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/gitlab/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

Thanks in advance for any help :)

**Comment by drmonty** [comment]
After removing `vendor`, you have to reset some files from the directory (see `git status`). Call `git checkout -- vendor` and you're ready to go.

**Comment by stefan-it** [comment]
@drmonty Thanks for that hint! Totally forgot that GitLab has some files in `vendor`... Closing :)
