### ISSUE TITLE
Markdown can't handle a specific form of link

### ISSUE THREAD

**Issue by drmonty** [gitlabhq/gitlabhq#9268]
Try to write an issue / a note to an issue including the following content:

```
[whatever you want](mailto:?subject=test)
```

saving the note / issue will lead to an 500 error and you won't be able to access the issue again:

```
ActionView::Template::Error (undefined method `split' for nil:NilClass):
    53:       .note-body
    54:         .note-text
    55:           = preserve do
    56:             = markdown(note.note, {no_header_anchors: true})
    57:         = render 'projects/notes/edit_form', note: note
    58: 
    59:       - if note.attachment.url
  app/helpers/application_helper.rb:259:in `add_nofollow'
  app/helpers/application_helper.rb:244:in `link_to'
  app/helpers/gitlab_markdown_helper.rb:28:in `link_to_gfm'
  lib/redcarpet/render/gitlab_html.rb:50:in `link'
  app/helpers/gitlab_markdown_helper.rb:56:in `render'
  app/helpers/gitlab_markdown_helper.rb:56:in `markdown'
  app/views/projects/notes/_note.html.haml:56:in `block in _app_views_projects_notes__note_html_haml__3876338607041020239_93733460'
  app/views/projects/notes/_note.html.haml:55:in `_app_views_projects_notes__note_html_haml__3876338607041020239_93733460'
  app/views/projects/notes/_notes.html.haml:11:in `block in _app_views_projects_notes__notes_html_haml__2477740104681122725_84756340'
  app/views/projects/notes/_notes.html.haml:9:in `_app_views_projects_notes__notes_html_haml__2477740104681122725_84756340'
  app/views/projects/notes/_notes_with_form.html.haml:2:in `_app_views_projects_notes__notes_with_form_html_haml___4560095801635258783_89665080'
  app/views/projects/issues/_discussion.html.haml:15:in `_app_views_projects_issues__discussion_html_haml__3763303589821729458_99794140'
  app/views/projects/issues/show.html.haml:40:in `_app_views_projects_issues_show_html_haml__4485239047692662664_100344300'
  app/controllers/projects/issues_controller.rb:54:in `show'
```

The link itself is correct (your mailprogram should open with preset subject `test`), but without a destination-address.

Tried with 7.8.0 -> 7.10.3.

**Comment by tsigo** [comment]
@Razer6 Confirmed working in latest master.

**Comment by Razer6** [comment]
Then close it here. :)

**Comment by tsigo** [comment]
@Razer6 I'm not an admin here :)
