### ISSUE TITLE
Error 500 on project page

### ISSUE THREAD

**Issue by benunter** [gitlabhq/gitlabhq#9355]
Hello,

I'm migrating from 7.1 to 7.11 version of gitlab and I get this error when I access the root page of a project:
```
Started GET "/<namespace>/<id>" for 127.0.0.1 at 2015-06-03 22:00:24 +0200
Processing by ProjectsController#show as HTML
Parameters: {"namespace_id"=>"xxx", "id"=>"xxx"}
Mysql2::Error: Field 'id' doesn't have a default value: INSERT INTO `services` (`active`, `created_at`, `issues_events`, `merge_requests_events`, `note_events`, `project_id`, `properties`, `push_events`, `tag_push_events`, `type`, `updated_at`) VALUES (0, '2015-06-03 20:00:24', 1, 1, 1, 63, '{}', 1, 1, 'GitlabIssueTrackerService', '2015-06-03 20:00:24')
Completed 500 Internal Server Error in 93ms

ActionView::Template::Error (Mysql2::Error: Field 'id' doesn't have a default value: INSERT INTO `services` (`active`, `created_at`, `issues_events`, `merge_requests_events`, `note_events`, `project_id`, `properties`, `push_events`, `tag_push_events`, `type`, `updated_at`) VALUES (0, '2015-06-03 20:00:24', 1, 1, 1, 63, '{}', 1, 1, 'GitlabIssueTrackerService', '2015-06-03 20:00:24')):
    22: 
    23:       .actions
    24:         - if can? current_user, :write_issue, @project
    25:           = link_to url_for_new_issue(@project, only_path: true), title: "New Issue", class: 'btn btn-sm append-right-10' do
    26:             = icon("exclamation-circle fw")
    27:             New Issue
    28: 
  app/models/project.rb:345:in `default_issue_tracker'
  app/models/project.rb:352:in `issues_tracker'
  app/helpers/issues_helper.rb:30:in `url_for_new_issue'
  app/views/projects/_aside.html.haml:25:in `_app_views_projects__aside_html_haml___2811813838468492683_125532560'
  app/views/projects/show.html.haml:16:in `_app_views_projects_show_html_haml___3681379416707470575_123906720'
  app/controllers/projects_controller.rb:77:in `block (2 levels) in show'
  app/controllers/projects_controller.rb:70:in `show' 
```

I used rake command to migrate my database to new schema and rake check command does not return error from different components running gitlab.

It seems that when trying to insert a new entry in services, the id should be specified in the SQL INSERT as the table service does not have a default value for the id field ?

Thank you

**Comment by stanhu** [comment]
If `id` is a primary key, it should not be needed, since this is automatically assigned by the database. Can you show the output of `DESCRIBE services` in your gitlab database?

**Comment by benunter** [comment]
Here is the structure of the services table:
```
mysql> DESCRIBE services;
+-----------------------+--------------+------+-----+---------+-------+
| Field                 | Type         | Null | Key | Default | Extra |
+-----------------------+--------------+------+-----+---------+-------+
| id                    | int(11)      | NO   | PRI | NULL    |       |
| type                  | varchar(255) | YES  |     | NULL    |       |
| title                 | varchar(255) | YES  |     | NULL    |       |
| project_id            | int(11)      | YES  | MUL | NULL    |       |
| created_at            | timestamp    | YES  | MUL | NULL    |       |
| updated_at            | timestamp    | YES  |     | NULL    |       |
| active                | tinyint(1)   | NO   |     | 0       |       |
| properties            | text         | YES  |     | NULL    |       |
| template              | tinyint(1)   | YES  |     | 0       |       |
| push_events           | tinyint(1)   | YES  |     | 1       |       |
| issues_events         | tinyint(1)   | YES  |     | 1       |       |
| merge_requests_events | tinyint(1)   | YES  |     | 1       |       |
| tag_push_events       | tinyint(1)   | YES  |     | 1       |       |
| note_events           | tinyint(1)   | NO   |     | 1       |       |
+-----------------------+--------------+------+-----+---------+-------+
14 rows in set (0.01 sec)
```

**Comment by benunter** [comment]
OK I found the problem, my tables missed auto increment for their id.
