### ISSUE TITLE
undefined method `close' for ExternalIssue

### ISSUE THREAD

**Issue by amiuhle** [gitlabhq/gitlabhq#9392]
When I have configured both an external issue tracker and a Web Hook for a project, the Web Hook isn't executed. I also don't see the push event on the project's dashboard.

I'm on `7.11.4`

`sidekiq.log` shows the following error:

```
2015-06-16T11:17:59.926Z 14368 TID-ow4npumak PostReceive JID- INFO: start
2015-06-16T11:18:01.014Z 14368 TID-ow4npumak PostReceive JID- INFO: fail: 1.088 sec
2015-06-16T11:18:01.015Z 14368 TID-ow4npumak WARN: {"class"=>"PostReceive", "args"=>["/home/git/repositories/<user>/<repository>.git", "key-1", "MzA0ODRlMWRkNDY1NjFhOTdkNjQ2NzY0MmExYmFkNjNmNDk2MGFmMSA4ZWU0\nMDczZTdiMjAzOWRlNjE4NDRkMDBiYzkzMGUyMDExMjliN2E5IHJlZnMvaGVh\nZHMvZGV2ZWxvcAo=\n"]}
2015-06-16T11:18:01.015Z 14368 TID-ow4npumak WARN: undefined method `close' for #<ExternalIssue:0x007fbccf4f0108>
2015-06-16T11:18:01.015Z 14368 TID-ow4npumak WARN: /home/git/gitlab/app/services/issues/close_service.rb:4:in `execute'
/home/git/gitlab/app/services/git_push_service.rb:87:in `block (2 levels) in process_commit_messages'
/home/git/gitlab/app/services/git_push_service.rb:86:in `each'
/home/git/gitlab/app/services/git_push_service.rb:86:in `block in process_commit_messages'
/home/git/gitlab/app/services/git_push_service.rb:73:in `each'
/home/git/gitlab/app/services/git_push_service.rb:73:in `process_commit_messages'
/home/git/gitlab/app/services/git_push_service.rb:56:in `execute'
/home/git/gitlab/app/workers/post_receive.rb:41:in `block in perform'
/home/git/gitlab/app/workers/post_receive.rb:28:in `each'
/home/git/gitlab/app/workers/post_receive.rb:28:in `perform'
```

**Comment by amiuhle** [comment]
This seems to have been fixed in 903132bc079970787333347209f6baebdd48800f and will be released in `7.12.0`
