### ISSUE TITLE
The update broke my Lab.

### ISSUE THREAD

**Issue by IngwiePhoenix** [gitlabhq/gitlabhq#9419]
I tried updating from 7.2.x to current, and that is what I now see in my logs:

```
==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/" for 92.212.39.70 at 2015-06-28 17:13:31 +0200
Processing by DashboardController#show as HTML

==> /var/log/gitlab/postgresql/current <==
2015-06-28_15:13:31.31355 ERROR:  relation "users_groups" does not exist at character 323
2015-06-28_15:13:31.31360 STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2015-06-28_15:13:31.31363 	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2015-06-28_15:13:31.31364 	                FROM pg_attribute a LEFT JOIN pg_attrdef d
2015-06-28_15:13:31.31365 	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2015-06-28_15:13:31.31366 	               WHERE a.attrelid = '"users_groups"'::regclass
2015-06-28_15:13:31.31366 	                 AND a.attnum > 0 AND NOT a.attisdropped
2015-06-28_15:13:31.31367 	               ORDER BY a.attnum
2015-06-28_15:13:31.31368 	

==> /var/log/gitlab/gitlab-rails/production.log <==
PG::Error: ERROR:  relation "users_groups" does not exist
LINE 5:                WHERE a.attrelid = '"users_groups"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users_groups"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

Completed 500 Internal Server Error in 10ms

ActiveRecord::StatementInvalid (PG::Error: ERROR:  relation "users_groups" does not exist
LINE 5:                WHERE a.attrelid = '"users_groups"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users_groups"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):
  app/models/user.rb:284:in `authorized_projects'
  app/controllers/dashboard_controller.rb:77:in `load_projects'



==> /var/log/gitlab/nginx/gitlab_access.log <==
92.212.39.70 - - [28/Jun/2015:17:13:31 +0200] "GET / HTTP/1.1" 500 415 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"
92.212.39.70 - - [28/Jun/2015:17:13:31 +0200] "GET /static.css HTTP/1.1" 304 0 "http://git.ingwie.me/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"
92.212.39.70 - - [28/Jun/2015:17:13:31 +0200] "GET /favicon.ico HTTP/1.1" 200 32988 "http://git.ingwie.me/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"
```

I prooooobably failed on the upgrade... Any way I can fix this? Its just a private little server, so it does not have a big database at all.

I suspect that I didn't do a correct backup; I `cp -R`'d the repositories... o.o'

**Comment by stanhu** [comment]
Can you make sure all your migrations are up-to-date?

```
sudo gitlab-rake gitlab:check
```

If they aren't, then a `sudo gitlab-ctl reconfigure` should bring them up-to-date.

**Comment by stanhu** [comment]
Are you still having trouble? I'm going to close this issue for now. Please feel free to reopen if you are still having issues.
