### ISSUE TITLE
MergeRequest can't be accepted [GitLab-7.11.4]

### ISSUE THREAD

**Issue by rob19780114** [gitlabhq/gitlabhq#9424]
A user ("master" role) tries to get his stuff on (unprotected) branch `develop` from his fork back to the original project. Upon hitting the "Accept" button the following error occurs

```
July 01, 2015 11:06 -> ERROR -> Command failed [1]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/ps-moxn/moxn-build-pom/.git --work-tree=/home/git/gitlab-satellites/ps-moxn/moxn-build-pom push origin develop
remote: /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/spec_set.rb:85:in `map!'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/spec_set.rb:85:in `materialize'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/definition.rb:133:in `specs'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/definition.rb:178:in `specs_for'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/definition.rb:167:in `requested_specs'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/environment.rb:18:in `requested_specs'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:13:in `setup'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler.rb:120:in `setup'[K
remote: from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/setup.rb:17:in `<top (required)>'[K
remote: from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'[K
remote: from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'[K
To /home/git/repositories/ps-moxn/moxn-build-pom.git
! [remote rejected] develop -> develop (pre-receive hook declined)
error: failed to push some refs to '/home/git/repositories/ps-moxn/moxn-build-pom.git'
```

Again: the user has role `master` on `ps-moxn/moxn-build-pom`, and only the `master branch` is protected on this project. The fork is completly unprotected.

**Comment by stanhu** [comment]
Are you installing from source? This seems to be a case of missing gems:

https://github.com/gitlabhq/gitlabhq/blob/master/doc/install/installation.md#install-gems

**Comment by rob19780114** [comment]
Yes, it's installed by source. Is there a way to check if the gems are correctly installed? Strangest thing is that two repositories from around 40 are "infected".

**Comment by stanhu** [comment]
Great! I'll close this for now then.
