### ISSUE TITLE
500 when renaming root user

### ISSUE THREAD

**Issue by shijij** [gitlabhq/gitlabhq#9440]
What I'm doing: rename the default admin user "root" to "newusername"

Clean Install(omnibus), latest version.

GitLab 7.12.2

GitLab Shell 2.6.3

GitLab API v3

Ruby 2.1.6p336

Rails 4.1.11

````
Started GET "/admin/users" for 76.28.*.* at 2015-07-08 01:43:29 -0700
Processing by Admin::UsersController#index as HTML
Completed 200 OK in 40ms (Views: 24.6ms | ActiveRecord: 6.5ms)
Started GET "/admin/users/root/edit" for 76.28.*.* at 2015-07-08 01:43:32 -0700
Processing by Admin::UsersController#edit as HTML
  Parameters: {"id"=>"root"}
Completed 200 OK in 52ms (Views: 35.9ms | ActiveRecord: 5.5ms)
Started PATCH "/admin/users/root" for 76.28.*.* at 2015-07-08 01:43:50 -0700
Processing by Admin::UsersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"name"=>"Administrator", "username"=>"newusername", "email"=>"admin@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "projects_limit"=>"10000", "can_create_group"=>"1", "skype"=>"", "linkedin"=>"", "twitter"=>"", "website_url"=>""}, "id"=>"root"}
Completed 500 Internal Server Error in 31ms (ActiveRecord: 7.7ms)

Exception (namespace directory cannot be moved):
  app/models/namespace.rb:133:in `move_dir'
  app/models/user.rb:610:in `ensure_namespace_correct'
  app/controllers/admin/users_controller.rb:76:in `block in update'
  app/controllers/admin/users_controller.rb:74:in `update'
````

**Comment by shijij** [comment]
Follow up:

This issue ONLY happens when there is ZERO project for root.

After adding a project, 'root' is able to rename

**Comment by Razer6** [comment]
Fixed with https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1101
