### ISSUE TITLE
Update to 7.13 (from 7.12) Google Oauth Broken

### ISSUE THREAD

**Issue by rlambrechts** [gitlabhq/gitlabhq#9479]
Hello since the update to 7.13 OAuth seems to be broken;

Any advice on this?
Kind regards,

gitlab.rb:
```
# Change the external_url to the address your users will type in their browser
external_url 'http://git.mycompany.com'
gitlab_rails['internal_api_url'] = 'http://localhost/'
# OmniAuth
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_providers'] = [
{
        "name" => "google_oauth2",
        "app_id" => "3XXX.apps.googleusercontent.com",
        "app_secret" => "YYYY",
        "args" => { "access_type" => "offline", "approval_prompt" => "" }
}
]
# Workers
unicorn['worker_processes'] = 3
unicorn['timeout'] = 300
```
cat /var/log/gitlab/gitlab-rails/production.log
```
Completed 200 OK in 740ms (Views: 2.1ms | ActiveRecord: 32.1ms)
Started POST "/users/auth/google_oauth2" for 147.67.241.226 at 2015-07-23 14:35:16 +0000
Can't verify CSRF token authenticity
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  lib/omni_auth/request_forgery_protection.rb:58:in `handle_unverified_request'
  lib/omni_auth/request_forgery_protection.rb:33:in `verify_authenticity_token'
  lib/omni_auth/request_forgery_protection.rb:27:in `call'
  config/initializers/7_omniauth.rb:18:in `block in <top (required)>'
```

**Comment by rlambrechts** [comment]
I also found a test case: 

a) open a private browser without a user signed in: this will give you 422 error.
b) try again this time: already sign in and then select google as verification method. now it will pass

**Comment by stanhu** [comment]
Do you happen to have another Web server in front of your GitLab nginx server?

**Comment by rlambrechts** [comment]
No none at all.

**Comment by stanhu** [comment]
Great!
