### ISSUE TITLE
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"projects/merge_requests"

### ISSUE THREAD

**Issue by rubnov** [gitlabhq/gitlabhq#9496]
Using 7-12-stable (installed from source) after having upgraded from 5.3 (!) with non-negligible effort, yet successfully, we are getting 500 error when trying to access a projects merge-requests e.g. 

https://<base_url>/<project>/merge_requests?assignee_id=&author_id=&label_name=&milestone_id=&scope=all&sort=created_desc&state=merged

Error details from production.log: 

```
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"projects/merge_requests", :id=>#<MergeRequest id: 3, target_branch: "master", source_branch: "wip/proxy", source_project_id: 15, author_id: 11, assignee_id: 9, title: "Proxy pop up", created_at: "2013-10-09 15:28:03", updated_at: "2014-01-02 15:26:55", milestone_id: nil, state: "closed", merge_status: "cannot_be_merged", target_project_id: 15, iid: nil, description: nil, position: 0, locked_at: nil>, :namespace_id=>#<Group id: 7, name: "Vidyo", path: "vidyo", owner_id: 3, created_at: "2013-05-09 13:46:27", updated_at: "2014-01-17 10:24:02", type: "Group", description: "", avatar: nil>, :project_id=>#<Project id: 15, name: "VidyoWeb", path: "vidyoweb", description: "", created_at: "2013-07-16 09:50:14", updated_at: "2015-07-28 15:06:57", creator_id: 9, issues_enabled: true, wall_enabled: false, merge_requests_enabled: true, wiki_enabled: true, namespace_id: 7, issues_tracker: "gitlab", issues_tracker_id: nil, snippets_enabled: false, last_activity_at: "2015-07-28 14:59:48", import_url: nil, visibility_level: 0, archived: false, avatar: nil, import_status: "none", repository_size: 1376.96, star_count: 0, import_type: nil, import_source: nil, commit_count: 1735>} missing required keys: [:id]):
    1: %li{ class: mr_css_classes(merge_request) }
    2:   .merge-request-title
    3:     %span.merge-request-title-text
    4:       = link_to_gfm merge_request.title, merge_request_path(merge_request), class: "row_title"
    5:     .merge-request-labels
    6:       - merge_request.labels.each do |label|
    7:         = link_to_label(label, project: merge_request.project)
  app/helpers/gitlab_routing_helper.rb:33:in `merge_request_path'
  app/views/projects/merge_requests/_merge_request.html.haml:4:in `_app_views_projects_merge_requests__merge_request_html_haml__911737230__579980838'
  app/views/projects/merge_requests/_merge_requests.html.haml:3:in `_app_views_projects_merge_requests__merge_requests_html_haml__641156098__580810298'
  app/views/projects/merge_requests/index.html.haml:14:in `_app_views_projects_merge_requests_index_html_haml___317301154__590928488'
  app/controllers/projects/merge_requests_controller.rb:36:in `index'
```

Same error occurs for state=closed and state=all

We have followed the installation instructions and migration (upgrade) instructions e.g. here: 
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/patch_versions.md

We also upgraded 7-12-stable to 7-13-stable (from source) and performed all migration however still getting this error.

Help?!

**Comment by rubnov** [comment]
Could ```iid: nil``` be the culprit?

**Comment by rubnov** [comment]
It was indeed. Had to ```delete from merge_requests where iid is NULL;```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
