### ISSUE TITLE
NoMethodError: undefined method `observers=' for ActiveRecord::Base:Class

### ISSUE THREAD

**Issue by hupili** [gitlabhq/gitlabhq#9517]
I was following the instructions on [this doc](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md) until the following command and get the error:

```
vagrant@vagrant-ubuntu-trusty-64:/home/git/gitlab$ sudo -u git -H bundle exec rake gitlab:shell:install[v2.6.3] REDIS_URL=unix:/var/run/redis/redis.sock RAILS_ENV=production --trace
** Invoke gitlab:shell:install (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `observers=' for ActiveRecord::Base:Class
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/attr_encrypted-1.3.4/lib/attr_encrypted.rb:259:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/attr_encrypted-1.3.4/lib/attr_encrypted/adapters/active_record.rb:94:in `method_missing_with_attr_encrypted'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/railtie.rb:108:in `block (3 levels) in <class:Railtie>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/railtie.rb:107:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/railtie.rb:107:in `block (2 levels) in <class:Railtie>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/lazy_load_hooks.rb:27:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.11/lib/active_record/railtie.rb:106:in `block in <class:Railtie>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/local/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/application.rb:300:in `initialize!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/railtie.rb:194:in `method_missing'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/application.rb:276:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.11/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => gitlab:shell:install => environment
```

Don't know Ruby. Can someone help. Thanks!

**Comment by stanhu** [comment]
Is there a reason you are installing from source rather than using the omnibus installer?

**Comment by hupili** [comment]
@stanhu probably due to network problem, I get stuck on the `apt-get`

```
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
sudo apt-get install gitlab-ce
```

So I try other methods to install. 

Anyway, installing from source is still needed since I'll need to do some customisation later. It is better to get familiar with the whole thing earlier.

**Comment by stanhu** [comment]
It looks like you may have missed installing the required gems:

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md#install-gems

**Comment by Razer6** [comment]
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
