### ISSUE TITLE
UrlGenerationError: No route matches

### ISSUE THREAD

**Issue by MrKeiKun** [gitlabhq/gitlabhq#9544]
**Information:**
After updating my gitlab to latest master for almost a month. I just got this error after running `bundle exec rake gitlab:env:info RAILS_ENV=production`.

**Logs:**
```
System information
System:
Current User:   git
Using RVM:      no
Ruby Version:   2.1.5p273
Gem Version:    2.2.2
Bundler Version:1.8.4
Rake Version:   10.4.2
Sidekiq Version:3.3.0
rake aborted!
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"projects", :id=>#<Project id: nil, name: nil, path: "some-project", description: nil, created_at: nil, updated_at: nil, creator_id: nil, issues_enabled: true, wall_enabled: false, merge_requests_enabled: true, wiki_enabled: false, namespace_id: nil, issues_tracker: "gitlab", issues_tracker_id: nil, snippets_enabled: false, last_activity_at: nil, import_url: nil, visibility_level: 0, archived: false, import_status: "none", repository_size: 0.0, star_count: 0, import_type: nil, import_source: nil, avatar: nil, commit_count: 0>, :namespace_id=>nil} missing required keys: [:namespace_id]
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/journey/formatter.rb:39:in `generate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:613:in `generate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:643:in `generate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:679:in `url_for'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:411:in `url_for'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:230:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.11/lib/action_dispatch/routing/route_set.rb:284:in `block (2 levels) in define_url_helper'
/home/git/gitlab/app/models/project.rb:319:in `web_url'
/home/git/gitlab/app/models/project.rb:566:in `http_url_to_repo'
/home/git/gitlab/lib/tasks/gitlab/info.rake:36:in `block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:env:info
(See full trace by running task with --trace)
```

**Comment by pupaxxo** [comment]
Same error here

**Comment by maxlazio** [comment]
I cannot replicate that with the stable 7.14 branches. Is this still reproducible?
