### ISSUE TITLE
Error 500 "invalid byte sequence in UTF-8" when clicking blame

### ISSUE THREAD

**Issue by EmteZogaf** [gitlabhq/gitlabhq#9577]
**GitLab version:** 7.14.0
**File encoding:** iso-8859-1
**File content:** contains umlauts Ä and ü
**Action:** clicking *Blame* button on file view
**Result:** Internal Server Error (500)

production.log:
```
Processing by Projects::BlameController#show as HTML
  Parameters: {"namespace_id"=>"mynamespace", "project_id"=>"myproject", "id"=>"master/folder/file_with_iso-8859-1_encoding.txt"}
Completed 500 Internal Server Error in 53ms (ActiveRecord: 2.0ms)

ArgumentError (invalid byte sequence in UTF-8):
  app/controllers/projects/blame_controller.rb:15:in `new'
  app/controllers/projects/blame_controller.rb:15:in `group_blame_lines'
  app/controllers/projects/blame_controller.rb:11:in `show'
```

**Comment by stanhu** [comment]
Thanks. Proposed fix is here: https://gitlab.com/gitlab-org/gitlab_git/merge_requests/45
