### ISSUE TITLE
GitLab CI [Test Settings] Error

### ISSUE THREAD

**Issue by demisx** [gitlabhq/gitlabhq#9597]
Clicking on _Project -> Services -> Gitlab CI ->Test Settings_  button results in the following parsing error. The builds with the same `.gitlab-ci.yml` are green. I am on GitLab 7.14.0.

```
Started POST "/projects/2/build?token=0e1cf45bbe26ab96" for 198.61.226.222 at 2015-09-01 17:24:32 -0700
Processing by ProjectsController#build as HTML
  Parameters: {"object_kind"=>"push", "before"=>"0a104c05f7702b16968322c019aaf8", "after"=>"556dc9f3489160c83bfb07bdaf1ebfc3e8", "ref"=>"refs/heads/master", "checkout_sha"=>"556dc902a9960c83bfb07bdaf1ebfc3e8", "message"=>nil, "user_id"=>1, "user_name"=>"Dmitri Moore", "user_email"=>"dmoore@colddata.com", "project_id"=>98, "repository"=>{"name"=>"campaign-manager-api", "url"=>"git@code.colddata.com:web-services/campaign-manager-api.git", "description"=>"Web service for sending managing client email marketing campaigns.", "homepage"=>"https://git.colddata.com/web-services/campaign-manager-api", "git_http_url"=>"https://git.colddata.com/web-services/campaign-manager-api.git", "git_ssh_url"=>"git@code.colddata.com:web-services/campaign-manager-api.git", "visibility_level"=>10}, "commits"=>[{"id"=>"556dc9f34891702a99fb07bdaf1ebfc3e8", "message"=>"Update readme with new web service URLs\n", "timestamp"=>"2015-08-30T08:45:53-07:00", "url"=>"https://git.colddata.com/web-services/campaign-manager-api/commit/556dc9f34891702a9960c83bfb07bdaf1ebfc3e8", "author"=>{"name"=>"Dmitri Moore", "email"=>"dmoore@colddata.com"}}, {"id"=>"9cfbaaafc0535ef7859db1e77edca425b", "message"=>"Update readme", "timestamp"=>"2015-08-11T13:01:30-07:00", "url"=>"https://git.colddata.com/web-services/campaign-manager-api/commit/9cfbaaafcaa228740535ef7859db1edca425b", "author"=>{"name"=>"Dmitri Moore", "email"=>"dmoore@colddata.com"}}, {"id"=>"f77384885d2b16968322c019aaf8", "message"=>"Update readme\n", "timestamp"=>"2015-06-23T17:23:15-07:00", "url"=>"https://git.colddata.com/web-services/campaign-manager-api/commit/0a104c05f7704ca38d2b16968322c019aaf8", "author"=>{"name"=>"Dmitri Moore", "email"=>"dmoore@colddata.com"}}], "total_commits_count"=>3, "token"=>"xxx", "id"=>"2", "project"=>{}}
no implicit conversion of nil into String
/home/gitlab_ci/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse'
/home/gitlab_ci/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
/home/gitlab_ci/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:318:in `parse'
/home/gitlab_ci/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/psych.rb:245:in `load'
/home/gitlab_ci/gitlab-ci/lib/gitlab_ci_yaml_processor.rb:11:in `initialize'
/home/gitlab_ci/gitlab-ci/app/models/commit.rb:231:in `new'
/home/gitlab_ci/gitlab-ci/app/models/commit.rb:231:in `config_processor'
/home/gitlab_ci/gitlab-ci/app/models/commit.rb:133:in `create_builds'
/home/gitlab_ci/gitlab-ci/app/services/create_commit_service.rb:43:in `execute'
/home/gitlab_ci/gitlab-ci/app/controllers/projects_controller.rb:90:in `build'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/abstract_controller/base.rb:189:in `process_action'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.12/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:113:in `call'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:113:in `call'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:552:in `block (2 levels) in compile'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:502:in `call'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:502:in `call'
/home/gitlab_ci/gitlab-ci/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/callbacks.rb:86:in `run_callbacks'
```

**Comment by leecade** [comment]
A similar problem:

```
Processing by Projects::ServicesController#test as HTML
  Parameters: {"namespace_id"=>"xxxxx", "project_id"=>"test", "id"=>"gitlab_ci"}
Completed 500 Internal Server Error in 518ms (ActiveRecord: 8.4ms)

ArgumentError (wrong number of arguments (1 for 0)):
  app/models/commit.rb:138:in `hook_attrs'
  lib/gitlab/push_data_builder.rb:38:in `block in build'
  lib/gitlab/push_data_builder.rb:37:in `map'
  lib/gitlab/push_data_builder.rb:37:in `build'
  lib/gitlab/push_data_builder.rb:75:in `build_sample'
  app/controllers/projects/services_controller.rb:41:in `test'
```

**Comment by Razer6** [comment]
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).
