### ISSUE TITLE
Cannot do a merge request in GitLab 8.0.0 d70c05

### ISSUE THREAD

**Issue by benperiton** [gitlabhq/gitlabhq#9660]
Since upgrading, I cannot complete a merge request.
The following appears in production.log:
```
Started POST "/int-machines/intranet/merge_requests" for 127.0.0.1 at 2015-09-23 12:33:15 +0100
Processing by Projects::MergeRequestsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "merge_request"=>{"title"=>"Merge latest dev", "description"=>"Merge the latest dev stuff into master so that it can be used", "assignee_id"=>"2", "source_project_id"=>"6", "source_branch"=>"develop", "target_project_id"=>"6", "target_branch"=>"master"}, "namespace_id"=>"int-machines", "project_id"=>"intranet"}
Completed 500 Internal Server Error in 16204ms (ActiveRecord: 167.6ms)

NoMethodError (undefined method `[]' for #<Gitlab::Git::Diff:0x00000012d0f3b0>):
  app/models/merge_request_diff.rb:126:in `reload_diffs'
  app/models/merge_request_diff.rb:43:in `reload_content'
  app/services/merge_requests/create_service.rb:17:in `execute'
  app/controllers/projects/merge_requests_controller.rb:106:in `create'
```

**Comment by benperiton** [comment]
Although it seems to work for some of projects ... I'll look into it a bit more

**Comment by ColtonProvias** [comment]
For me, this error appears to be occurring when merging to a branch that is ahead.

**Comment by adaiguoguo** [comment]
It has been revoled in 8.0.3 .
[changelog](https://github.com/gitlabhq/gitlabhq/blob/v8.0.3/CHANGELOG)

**Comment by stanhu** [comment]
Closing this issue, as I believe it has been fixed.
