### ISSUE TITLE
If a connection error occurred during email's inbox check, mail_room service may crash

### ISSUE THREAD

**Issue by Senorsen** [gitlabhq/gitlabhq#9712]
```
/usr/local/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)
        from /usr/local/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
        from /usr/local/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:20:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:20:in `imap'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:69:in `setup'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:149:in `rescue in block in run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:141:in `block in run'
```

Then mail_room service seems crash, after this, `reply by email` feature fails to generate reply.

**Comment by Senorsen** [comment]
P.S. After this service crash, I must restart it use: 
```
sudo -u git -H RAILS_ENV=production bin/mail_room start
```

**Comment by DouweM** [comment]
@Senorsen Hmm, how do you suggest this could be better?

**Comment by Senorsen** [comment]
Oh, I have thought about this...

Maybe we should try to reconnect endlessly after a short delay (e.g. 10 seconds or longer, to avoid using too many system resources). It shouldn't crash or exit, because any service in servers shouldn't crash :smile:

**Comment by DouweM** [comment]
@Senorsen But if we can't connect with the server because of an actual SSL error, we want to show that to the admin, right, instead of just silently failing?

**Comment by Senorsen** [comment]
@DouweM Yes, I think so. But GitLab doesn't have a universal notification system right now...  I don't know how we can send the message the admin in an efficient way?

**Comment by DouweM** [comment]
@Senorsen The admin is encouraged to run `sudo gitlab-rake gitlab:incoming_email:check` (or `sudo -u git -H bundle exec rake gitlab:incoming_email:check RAILS_ENV=production` for installations from source) after entering the Reply by email config, which should alert them of any error.

**Comment by Senorsen** [comment]
Yes, but if there is a network error, this service will crash, too.

My title is updated just now.

**Comment by DouweM** [comment]
@Senorsen All right, fair enough :) Could you cross-post this to https://github.com/tpitale/mail_room? That's the gem we're using and this is something we'd need to fix there.

**Comment by junxy** [comment]
The same error at https web hook ?

gitlab version: 8.0.5

gitlab 7.13.1 is working

log:
```
2015-10-16T09:32:42.163Z 2994 TID-fke24 WARN: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server certificate B: certificate verify failed
2015-10-16T09:32:42.163Z 2994 TID-fke24 WARN: /usr/lib/ruby/2.1.0/net/http.rb:923:in `connect'
/usr/lib/ruby/2.1.0/net/http.rb:923:in `block in connect'
/usr/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:100:in `call'
/usr/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
/usr/lib/ruby/2.1.0/net/http.rb:923:in `connect'
/usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
/usr/lib/ruby/2.1.0/net/http.rb:1375:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/httparty-0.13.5/lib/httparty.rb:476:in `post'
/home/git/gitlab/app/models/hooks/web_hook.rb:39:in `execute'
/home/git/gitlab/app/workers/project_web_hook_worker.rb:8:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/memory_killer.rb:17:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

**Comment by DouweM** [comment]
@junxy Apparently your web hook's SSL certificate is invalid. It's unrelated to mail_room though.

**Comment by junxy** [comment]
@DouweM Thank you ; )

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
