### ISSUE TITLE
500 error, search

### ISSUE THREAD

**Issue by loukash** [gitlabhq/gitlabhq#9718]
When trying to search a word "cookie", I get a 500 error. Other repo don't have this error.
Project name: IOs_app
project path: http://geeta.example.su/bulanov/ios_app

```
Started GET "/search?utf8=%E2%9C%93&search=cookie&group_id=&project_id=54&search_code=[FILTERED]&repository_ref=master" for 127.0.0.1 at 2015-10-12 16:28:42 +0500
Processing by SearchController#show as HTML
  Parameters: {"utf8"=>"✓", "search"=>"cookie", "group_id"=>"", "project_id"=>"54", "search_code"=>"[FILTERED]", "repository_ref"=>"master"}
Started POST "/ci//api/v1/builds/register.json" for 127.0.0.1 at 2015-10-12 16:28:43 +0500
Completed 500 Internal Server Error in 418ms (ActiveRecord: 9.0ms)

ActionView::Template::Error (wrong argument type nil (expected Regexp)):
    1: - blob = @project.repository.parse_search_result(blob)
    2: .blob-result
    3:   .file-holder
    4:     .file-title
  app/models/repository.rb:492:in `sub'  
  app/models/repository.rb:492:in `block in parse_search_result'
  app/models/repository.rb:491:in `each_line'
  app/models/repository.rb:491:in `parse_search_result'
  app/views/search/results/_blob.html.haml:1:in `_app_views_search_results__blob_html_haml__1034720610060419991_110087080'
  app/views/search/_results.html.haml:20:in `_app_views_search__results_html_haml___4504652646938204219_109744740'
  app/views/search/show.html.haml:5:in `_app_views_search_show_html_haml__1196088973973186380_70319255279460'
```

gitlab:env:info
```
System information
System:         Debian 6.0.7
Current User:   git
Using RVM:      yes
RVM Version:    1.26.11
Ruby Version:   2.1.6p336
Gem Version:    2.4.8
Bundler Version:1.10.6
Rake Version:   10.4.2
Sidekiq Version:3.3.0

GitLab information
Version:        8.0.3
Revision:       f9a0c22
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            http://geeta.example.su
HTTP Clone URL: http://geeta.example.su/some-group/some-project.git
SSH Clone URL:  git@geeta.example.su:some-group/some-project.git
Using LDAP:     yes
Using Omniauth: no

GitLab Shell
Version:        2.6.5
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by jvanbaarsen** [comment]
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).
