### ISSUE TITLE
Mysql2::Error: Table 'gitlabhq_development.ci_commits' doesn't exist

### ISSUE THREAD

**Issue by NiranjanaK** [gitlabhq/gitlabhq#9753]
I just tried to clone gitlabhq source from github two days before and tried to set-up gitlab in my local machine but getting this error while running rake db:migrate
```ruby
Mysql2::Error: Table 'gitlabhq_development.ci_commits' doesn't exist: SHOW FULL FIELDS FROM `ci_commits`/home/niranjana/.rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.7/lib/patches/db/mysql2.rb:20:in `query'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.7/lib/patches/db/mysql2.rb:20:in `query'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/home/niranjana/workspace/projects/gitlabhq/config/initializers/connection_fix.rb:20:in `execute'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:310:in `execute_and_free'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:451:in `columns'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:747:in `column_for'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:673:in `change_column_sql'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:515:in `change_column'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
/home/niranjana/workspace/projects/gitlabhq/db/migrate/limits_to_mysql.rb:12:in `up'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:605:in `exec_migration'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'gitlabhq_development.ci_commits' doesn't exist: SHOW FULL FIELDS FROM `ci_commits`
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.7/lib/patches/db/mysql2.rb:20:in `query'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/rack-mini-profiler-0.9.7/lib/patches/db/mysql2.rb:20:in `query'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/home/niranjana/.rvm/gems/ruby-2.2.1/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
```

**Comment by NiranjanaK** [comment]
https://github.com/gitlabhq/gitlabhq/blob/master/db/migrate/limits_to_mysql.rb
In the above link while commenting  the following lines
```
 change_column :ci_builds, :trace, :text, limit: 1073741823
 change_column :ci_commits, :push_data, :text, limit: 16777215
```
then while running "rake db:migrate" it works fine.
Is this a proper way to fix?

**Comment by stanhu** [comment]
This seems like an ordering issue: `limits_to_mysql` is used in the `20140415124820` migration, but the column is added in `20151016131433` instead. I think we need to move the limit changes into its own migration.

**Comment by stanhu** [comment]
Did you run `rake db:setup` first by the way?

**Comment by stanhu** [comment]
If you created the DB from scratch, those two fields should have been there already, so the migration would have worked. I could see an issue if you attempted to migrate the DB from an older schema, though. I added a fix here: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1653

**Comment by NiranjanaK** [comment]
Thats Great.

**Comment by stanhu** [comment]
@NiranjanaK Can you describe in more detail the state of your database beforehand? Was this a new installation, or did your GitLab database exist in some form before pulling the latest?

**Comment by NiranjanaK** [comment]
This is the new installation of GitLab.

**Comment by stanhu** [comment]
Did you run a `rake db:setup` first?

**Comment by NiranjanaK** [comment]
Nope. I just started with ```rake db:create``` then with migrate

**Comment by stanhu** [comment]
That would explain it. Running `rake db:migrate` doesn't load the schema, so the first migration fails since the column won't exist until later. 

The fix was just merged, which fixes this bug and a slightly different bug: the limits migration would never have been applied to existing databases. Thanks! :)
