### ISSUE TITLE
Error 500 when try to access by browser

### ISSUE THREAD

**Issue by arnaud-zg** [gitlabhq/gitlabhq#9761]
Hi everyone,

Since runing that command on my server `apt-get update && apt-get upgrade`, I can't access to my gitlab. When I try to access I get an error 500.

- On my nginx config everything works, I don't have any errors.
- When I try to check my gitlab on production environment it telling me that, but I don't understand my ` /var/opt/gitlab/gitlab-shell/config.yml` seems have good config.

```
root@server:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
WARNING: This version of GitLab depends on gitlab-shell 2.6.3, but you're running Unknown. Please update gitlab-shell.
Checking GitLab Shell ...

GitLab Shell version >= 2.6.3 ? ... FAIL. Please update gitlab-shell to 2.6.3 from Unknown
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ...
Project / Project_1 ... ok
Running /var/opt/gitlab/gitlab-shell/bin/check
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /var/opt/gitlab/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... no
  Try fixing it:
  sudo -u git -H RAILS_ENV=production bin/background_jobs start
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  see log/sidekiq.log for possible errors
  Please fix the error above and rerun the checks.

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... yes
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...
Project / Project_1 ... ok
Projects have satellites? ...
Project / Project_1 ... ok
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.6)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.7.10)
Active users: 7

Checking GitLab ... Finished

root@server:/home/git/gitlab#
```

Can someone tell me why it doesn't work?
![capture](https://cloud.githubusercontent.com/assets/10991546/10682552/327a6fc4-7937-11e5-8aa9-b88e06bdb6f6.PNG)

**Comment by arnaud-zg** [comment]
And that's the content of my file `log/sidekiq.log`. 

```
root@server:/home/git/gitlab# tail -n 10 log/sidekiq.log
2015-10-23T01:08:50.788Z 11809 TID-bla20wg8 WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
root@server:/home/git/gitlab#
```

**Comment by stanhu** [comment]
Can you include a few more lines of `sidekiq.log`? Also, where does the Error 500 show up (e.g. from the Web server or does GitLab show an error page)? Are there errors in `production.log`?

Are you running GitLab via source or omnibus? The directory structure seems to suggest source, but are you updating a GitLab CE package via `apt-get update`?

**Comment by arnaud-zg** [comment]
Gitlab show an error page, my web server don't have any error. Actually I'm running Gitlab by source (manually), I haven't installed this project with `apt-get`.

This is the content of my `production.log`, it seems there is some error in `rack_attack_git_basic_auth.rb`.

```
root@server:/home/git/gitlab# tail -n 30 log/production.log
  config/initializers/rack_attack_git_basic_auth.rb:5:in `block in <top (required)>'


Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Started GET "/" for 127.0.0.1 at 2015-10-23 03:16:15 +0200

Errno::ENOENT (No such file or directory - connect(2) for /var/run/redis/redis.sock):
  config/initializers/rack_attack_git_basic_auth.rb:5:in `block in <top (required)>'


Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scoped order and limit are ignored, it's forced to be batch order and batch size
Started GET "/" for 127.0.0.1 at 2015-10-23 03:35:31 +0200

Errno::ENOENT (No such file or directory - connect(2) for /var/run/redis/redis.sock):
  config/initializers/rack_attack_git_basic_auth.rb:5:in `block in <top (required)>'


root@server:/home/git/gitlab#
```

Here is some more lines of `sidekid.log`
```
root@server:/home/git/gitlab# tail -n 30 log/sidekiq.log
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
2015-10-23T01:08:50.787Z 11809 TID-bla20wg8 WARN: {:context=>"Manager#processor_died died"}
2015-10-23T01:08:50.787Z 11809 TID-bla20wg8 WARN: task was terminated
2015-10-23T01:08:50.787Z 11809 TID-bla20wg8 WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
2015-10-23T01:08:50.788Z 11809 TID-bla20wg8 WARN: {:context=>"Manager#processor_died died"}
2015-10-23T01:08:50.788Z 11809 TID-bla20wg8 WARN: task was terminated
2015-10-23T01:08:50.788Z 11809 TID-bla20wg8 WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:164:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
root@server:/home/git/gitlab#
```

**Comment by stanhu** [comment]
This looks like Redis stopped running. You may want to check that `redis-server` is still running and listening on the UNIX socket `/var/run/redis/redis.sock` (e.g. check `/etc/redis/redis.conf`).

**Comment by arnaud-zg** [comment]
Indeed Redis stopped running, but that's file doesn't exist `/var/run/redis/redis.sock`.
```
root@server:/var/run/redis# service redis-server start
Starting redis-server: redis-server.
root@server:/var/run/redis#
```

**Comment by stanhu** [comment]
Did your upgrade overwrite your `/etc/redis/redis.conf`? Are these lines commented out?

```
unixsocket /var/run/redis/redis.sock
unixsocketperm 755
```

**Comment by arnaud-zg** [comment]
I haven't modify my `/etc/redis/redis.conf`manually, but it something has overwritten my `redis.conf`.
```
root@server:/etc/redis# ls -l
total 156
-rw-r----- 1 redis redis 41623 Oct 15 17:47 redis.conf
-rw-r--r-- 1 root  root  41489 Jul 26 23:56 redis.conf.dpkg-old
-rw-r--r-- 1 root  root  41456 Jul 26 23:56 redis.conf.orig
drwxr-xr-x 2 root  root   4096 Oct 22 18:49 redis-server.post-down.d
drwxr-xr-x 2 root  root   4096 Oct 22 18:49 redis-server.post-up.d
drwxr-xr-x 2 root  root   4096 Oct 22 18:49 redis-server.pre-down.d
drwxr-xr-x 2 root  root   4096 Oct 22 18:49 redis-server.pre-up.d
-rw-r--r-- 1 root  root   7109 Dec 19  2014 sentinel.conf
root@Chaos:/etc/redis# grep unixsocket *
redis.conf:# unixsocket /var/run/redis/redis.sock
redis.conf:# unixsocketperm 700
redis.conf.dpkg-old:# unixsocket /tmp/redis.sock
redis.conf.dpkg-old:unixsocketperm 0775
redis.conf.dpkg-old:unixsocket /var/run/redis/redis.sock
redis.conf.orig:# unixsocket /tmp/redis.sock
redis.conf.orig:# unixsocketperm 700
grep: redis-server.post-down.d: Is a directory
grep: redis-server.post-up.d: Is a directory
grep: redis-server.pre-down.d: Is a directory
grep: redis-server.pre-up.d: Is a directory
root@server:/etc/redis#
```

**Comment by stanhu** [comment]
Yes, it looks like the upgrade replaced your conf file and disabled `unixsocket`. The upgrader should have asked you whether you wanted to replace the existing file.

**Comment by stanhu** [comment]
You want `unixsocket` to be active, so the lines should NOT be commented.

**Comment by arnaud-zg** [comment]
Okay thank you very much I just copied `redis.conf.dpkg-old` to `redis.conf` and restart  `redis-server`.
It works! :smiley:

![capture](https://cloud.githubusercontent.com/assets/10991546/10683015/470a3928-793d-11e5-8871-e62fe9c51653.PNG)

**Comment by stanhu** [comment]
Great!
