### ISSUE TITLE
Incorrectly configured Mailroom uses 100% CPU

### ISSUE THREAD

**Issue by Armada651** [gitlabhq/gitlabhq#9891]
If the Mailroom can't connect to the mailserver due to an SSL error it will keep attempting to connect to it going so far as to dedicate a CPU core to the task of banging the mailserver.

To be precise, the command `/opt/gitlab/embedded/bin/ruby /opt/gitlab/embedded/bin/bundle exec mail_room -c /var/opt/gitlab/gitlab-rails/etc/mail_room.yml` is using 100% CPU.

My system is Ubuntu Server 14.04 and I am using the omnibus distribution of GitLab.

Here is an excerpt from my mailroom log file:

```
2015-12-05_16:28:10.65112 /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
2015-12-05_16:28:10.65116 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
2015-12-05_16:28:10.65116 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
2015-12-05_16:28:10.65117 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
2015-12-05_16:28:10.65117 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
2015-12-05_16:28:10.65118 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
2015-12-05_16:28:10.65121 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
2015-12-05_16:28:10.65122 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
2015-12-05_16:28:10.65123 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
2015-12-05_16:28:10.65123 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
2015-12-05_16:28:10.65124 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
2015-12-05_16:28:10.65124 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
2015-12-05_16:28:10.65125 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `load'
2015-12-05_16:28:10.65125 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `<main>'
2015-12-05_16:28:10.82077 Runit: starting mail_room
2015-12-05_16:28:23.33484 /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
2015-12-05_16:28:23.33493 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
2015-12-05_16:28:23.33494 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
2015-12-05_16:28:23.33496 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
2015-12-05_16:28:23.33498 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
2015-12-05_16:28:23.33499 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
2015-12-05_16:28:23.33501 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
2015-12-05_16:28:23.33502 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
2015-12-05_16:28:23.33504 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
2015-12-05_16:28:23.33506 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
2015-12-05_16:28:23.33507 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
2015-12-05_16:28:23.33509 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
2015-12-05_16:28:23.33510 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `load'
2015-12-05_16:28:23.33512 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `<main>'
2015-12-05_16:28:23.51205 Runit: starting mail_room
2015-12-05_16:28:36.27779 /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
2015-12-05_16:28:36.27782 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1454:in `start_tls_session'
2015-12-05_16:28:36.27783 	from /opt/gitlab/embedded/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
2015-12-05_16:28:36.27783 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `new'
2015-12-05_16:28:36.27783 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:20:in `imap'
2015-12-05_16:28:36.27784 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
2015-12-05_16:28:36.27784 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:69:in `setup'
2015-12-05_16:28:36.27785 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/mailbox_watcher.rb:132:in `run'
2015-12-05_16:28:36.27787 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `each'
2015-12-05_16:28:36.27787 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/coordinator.rb:19:in `run'
2015-12-05_16:28:36.27787 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/lib/mail_room/cli.rb:52:in `start'
2015-12-05_16:28:36.27788 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/mail_room-0.6.1/bin/mail_room:5:in `<top (required)>'
2015-12-05_16:28:36.27788 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `load'
2015-12-05_16:28:36.27788 	from /opt/gitlab/embedded/service/gem/ruby/2.1.0/bin/mail_room:23:in `<main>'
2015-12-05_16:28:36.44894 Runit: starting mail_room
```

**Comment by DouweM** [comment]
@Armada651 Thanks for reporting this. Would you mind creating an issue in https://github.com/tpitale/mail_room so the creator of mail_room can participate as well.

**Comment by Armada651** [comment]
@DouweM This issue has been refused upstream, please reopen this issue here.

**Comment by DouweM** [comment]
@Armada651 Thank you, I will check it out asap,

**Comment by DouweM** [comment]
@jacobvosmaer Do you have any ideas on what to do if mail_room fails because of an (unrecoverable) SSL error, to keep runit from taking up a core trying to restart it? I don't have any right now.

**Comment by jacobvosmaer** [comment]
Restarted like crazy seems to be Runit's thing.

@Armada651 is this a transient problem? Or do you just want to turn mail_room off? I think the latter would mean `mail_room['enable'] = false` in /etc/gitlab/gitlab.rb.

**Comment by Armada651** [comment]
@jacobvosmaer I already solved it by turning Mailroom off, but I could've probably fixed the issue by fixing the certificate chain.

I reported this issue not to fix my configuration, but to let Gitlab know that misconfiguration is not handled correctly right now.

**Comment by jacobvosmaer** [comment]
Thanks @Armada651 

Reading http://smarden.org/runit/runsv.8.html I think we could improve on the current by having an exectuable `/opt/gitlab/sv/mail-room/finish` with just the line `#!/bin/sh` in it. That alone should tell Runit to wait 1s in between restarts, which should prevent the pathological core-pinning behavior.

cc @maxlazio

**Comment by jacobvosmaer** [comment]
The Runit Chef definition in omnibus-gitlab supports 'finish' files.

**Comment by jacobvosmaer** [comment]
omnibus-gitlab MR: https://gitlab.com/gitlab-org/omnibus-gitlab/merge_requests/611

**Comment by askz** [comment]
Hi, I have the same issue, in 8.4. Patch not seems to work.

**Comment by jacobvosmaer** [comment]
@askz are you using omnibus packages? All the patch does is create delays between restart attempts; the restart loop does not go away.

**Comment by askz** [comment]
@jacobvosmaer  I use the dockerized version of sameersbn.

**Comment by jacobvosmaer** [comment]
@askz I am not sure if that Docker image uses the omnibus package (try `head /opt/gitlab/version-manifest.txt` inside the container). Omnibus-gitlab is the only place where we made a change.

**Comment by askz** [comment]
@jacobvosmaer I don't have this file the docker filesystem.. Even at the root of gitlab install.

**Comment by jacobvosmaer** [comment]
@askz in that case you might want to take this up with the maintainer of your Docker container. The 'fix' we applied is in the process supervision system (Runit in the case of omnibus), not in mail_room itself.  I don't know what your Docker container uses for process supervision.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
