### ISSUE TITLE
Problem installing gitlab

### ISSUE THREAD

**Issue by dummys** [gitlabhq/gitlabhq#9949]
Hello,

After installing git lab I get the following when starting unicorn:
```
I, [2016-01-05T18:55:58.172958 #2474]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb:2:in `close': Bad file descriptor - /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb (Errno::EBADF)
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb:2:in `open'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb:2:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:22:in `block in require_relative_dir'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `require_relative_dir'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io.rb:3:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:22:in `block in require_relative_dir'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `require_relative_dir'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1.rb:3:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.2.rb:2:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.3.rb:2:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.rb:2:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/2.0.0.rb:2:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/2.0.rb:2:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports.rb:3:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/virtus-0.5.5/lib/virtus.rb:7:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/grape-0.4.1/lib/grape.rb:16:in `<top (required)>'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler/runtime.rb:76:in `require'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler/runtime.rb:72:in `each'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler/runtime.rb:61:in `each'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler/runtime.rb:61:in `require'
	from /usr/lib64/ruby/gems/2.0.0/gems/bundler-1.8.9/lib/bundler.rb:134:in `require'
	from /home/git/gitlab/config/application.rb:9:in `<top (required)>'
	from /home/git/gitlab/config/environment.rb:2:in `require'
	from /home/git/gitlab/config/environment.rb:2:in `<top (required)>'
	from config.ru:4:in `require'
	from config.ru:4:in `block in <main>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn.rb:48:in `eval'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn.rb:48:in `block in builder'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/bin/unicorn_rails:139:in `call'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/bin/unicorn_rails:139:in `block in rails_builder'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:722:in `call'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:722:in `build_app!'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:140:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/unicorn-4.6.3/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.0.0/bin/unicorn_rails:23:in `<main>'

Then:
gaia gitlab # sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production
rake aborted!
Bad file descriptor - /home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb:2:in `close'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb:2:in `open'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io/open.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:22:in `block in require_relative_dir'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `require_relative_dir'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1/io.rb:3:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:22:in `block in require_relative_dir'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:21:in `require_relative_dir'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.1.rb:3:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.2.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.3.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/1.9.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/2.0.0.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/2.0.rb:2:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports/tools.rb:328:in `require_with_backports'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/backports-3.3.2/lib/backports.rb:3:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/virtus-0.5.5/lib/virtus.rb:7:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/grape-0.4.1/lib/grape.rb:16:in `<top (required)>'
/home/git/gitlab/config/application.rb:9:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```
Did you have an idea how I can debug this ?
Thanks.

**Comment by stanhu** [comment]
Looks like an error with your filesystem. You may need to check your disk/reboot/etc. I don't think this is a GitLab-specific error, so I'm closing this for now.
