### ISSUE TITLE
Push sometimes doesn't register

### ISSUE THREAD

**Issue by doenietzomoeilijk** [gitlabhq/gitlabhq#9962]
_This issue might be related to #9945, but the reporter didn't have the same error in their logs so I've decided to open a separate issue._

After upgrading to 8.3.2, we sometimes see pushes not resulting in a build, as in "it never reaches CI", it doesn't even show up in the activity log. Pushing again (after adding a newline to a readme or something silly like that) usually gets the build going. I haven't been able to reliably reproduce the behaviour, however, I did notice this in the sidekiq.log:

```
2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: {"class"=>"PostReceive", "args"=>["/gitlab/repositories/XXX/YYY.git", "key-ZZZ", "STUFF\n"]}
2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 80
2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
```

...followed by a lengthy trace that's probably not needed here (but I could produce it if needed). This error pops up every time someone has a non-triggering push, so it seems the two are related. Not sure what it's _supposed_ to connect to, but it seems to me connecting to `nil` is never going to work... (I'm not a Ruby dev, but I'd guess `nil` is equivalent to `null` or `None`).

Env info:

```
System information
System:     Ubuntu 14.04
Current User:   git
Using RVM:  no
Ruby Version:   2.1.7p400
Gem Version:    2.5.1
Bundler Version:1.10.6
Rake Version:   10.4.2
Sidekiq Version:4.0.1

GitLab information
Version:    8.3.2
Revision:   fbb8b6e
Directory:  /opt/gitlab/embedded/service/gitlab-rails
DB Adapter: postgresql
URL:        http://gitlab.vdlp.nl
HTTP Clone URL: http://gitlab.vdlp.nl/some-group/some-project.git
SSH Clone URL:  git@gitlab.vdlp.nl:some-group/some-project.git
Using LDAP: no
Using Omniauth: no

GitLab Shell
Version:    2.6.9
Repositories:   /gitlab/repositories
Hooks:      /opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:        /opt/gitlab/embedded/bin/git
```

Running `gitlab:check` shows green across the board.

Reconfiguring / restarting GitLab hasn't solved the issue.

Any ideas?

**Comment by stanhu** [comment]
Can you add a few more lines from the trace?

**Comment by doenietzomoeilijk** [comment]
@stanhu sure thing! I'll just go and add the whole thing:

```
2016-01-05_16:01:17.32347 2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: {"class"=>"PostReceive", "args"=>["/gitlab/repositories/XXX/YYY.git", "key-ZZZ", "STUFF\n"]}
2016-01-05_16:01:17.32350 2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 80
2016-01-05_16:01:17.32358 2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
2016-01-05_16:01:17.32359 /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
2016-01-05_16:01:17.32359 /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
2016-01-05_16:01:17.32360 /opt/gitlab/embedded/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
2016-01-05_16:01:17.32360 /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
2016-01-05_16:01:17.32361 /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
2016-01-05_16:01:17.32361 /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
2016-01-05_16:01:17.32362 /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
2016-01-05_16:01:17.32362 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
2016-01-05_16:01:17.32363 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
2016-01-05_16:01:17.32363 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
2016-01-05_16:01:17.32366 /opt/gitlab/embedded/service/gitlab-rails/app/models/project_services/jira_service.rb:245:in `existing_comment?'
2016-01-05_16:01:17.32367 /opt/gitlab/embedded/service/gitlab-rails/app/models/project_services/jira_service.rb:208:in `add_comment'
2016-01-05_16:01:17.32368 /opt/gitlab/embedded/service/gitlab-rails/app/models/project_services/jira_service.rb:119:in `create_cross_reference_note'
2016-01-05_16:01:17.32368 /opt/gitlab/embedded/service/gitlab-rails/app/services/system_note_service.rb:245:in `cross_reference'
2016-01-05_16:01:17.32369 /opt/gitlab/embedded/service/gitlab-rails/app/models/concerns/mentionable.rb:87:in `block in create_cross_references!'
2016-01-05_16:01:17.32369 /opt/gitlab/embedded/service/gitlab-rails/app/models/concerns/mentionable.rb:86:in `each'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/models/concerns/mentionable.rb:86:in `create_cross_references!'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:98:in `block in process_commit_messages'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:82:in `each'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:82:in `process_commit_messages'
2016-01-05_16:01:17.32371 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:52:in `execute'
2016-01-05_16:01:17.32371 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:41:in `block in perform'
2016-01-05_16:01:17.32372 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:28:in `each'
2016-01-05_16:01:17.32372 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:28:in `perform'
2016-01-05_16:01:17.32372 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
2016-01-05_16:01:17.32373 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
2016-01-05_16:01:17.32373 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
2016-01-05_16:01:17.32373 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sidekiq_middleware/memory_killer.rb:17:in `call'
2016-01-05_16:01:17.32374 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32374 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2016-01-05_16:01:17.32374 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32375 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2016-01-05_16:01:17.32375 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32375 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2016-01-05_16:01:17.32376 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
2016-01-05_16:01:17.32376 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2016-01-05_16:01:17.32376 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32377 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
2016-01-05_16:01:17.32377 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
2016-01-05_16:01:17.32377 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
2016-01-05_16:01:17.32379 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
2016-01-05_16:01:17.32379 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
2016-01-05_16:01:17.32379 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
2016-01-05_16:01:17.32380 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
2016-01-05_16:01:17.32380 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
2016-01-05_16:01:17.32363 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
2016-01-05_16:01:17.32366 /opt/gitlab/embedded/service/gitlab-rails/app/models/project_services/jira_service.rb:245:in `existing_comment?'
2016-01-05_16:01:17.32367 /opt/gitlab/embedded/service/gitlab-rails/app/models/project_services/jira_service.rb:208:in `add_comment'
2016-01-05_16:01:17.32368 /opt/gitlab/embedded/service/gitlab-rails/app/models/project_services/jira_service.rb:119:in `create_cross_reference_note'
2016-01-05_16:01:17.32368 /opt/gitlab/embedded/service/gitlab-rails/app/services/system_note_service.rb:245:in `cross_reference'
2016-01-05_16:01:17.32369 /opt/gitlab/embedded/service/gitlab-rails/app/models/concerns/mentionable.rb:87:in `block in create_cross_references!'
2016-01-05_16:01:17.32369 /opt/gitlab/embedded/service/gitlab-rails/app/models/concerns/mentionable.rb:86:in `each'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/models/concerns/mentionable.rb:86:in `create_cross_references!'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:98:in `block in process_commit_messages'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:82:in `each'
2016-01-05_16:01:17.32370 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:82:in `process_commit_messages'
2016-01-05_16:01:17.32371 /opt/gitlab/embedded/service/gitlab-rails/app/services/git_push_service.rb:52:in `execute'
2016-01-05_16:01:17.32371 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:41:in `block in perform'
2016-01-05_16:01:17.32372 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:28:in `each'
2016-01-05_16:01:17.32372 /opt/gitlab/embedded/service/gitlab-rails/app/workers/post_receive.rb:28:in `perform'
2016-01-05_16:01:17.32372 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job'
2016-01-05_16:01:17.32373 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
2016-01-05_16:01:17.32373 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
2016-01-05_16:01:17.32373 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/sidekiq_middleware/memory_killer.rb:17:in `call'
2016-01-05_16:01:17.32374 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32374 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
2016-01-05_16:01:17.32374 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32375 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2016-01-05_16:01:17.32375 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32375 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2016-01-05_16:01:17.32376 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context'
2016-01-05_16:01:17.32376 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2016-01-05_16:01:17.32376 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
2016-01-05_16:01:17.32377 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call'
2016-01-05_16:01:17.32377 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
2016-01-05_16:01:17.32377 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process'
2016-01-05_16:01:17.32379 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats'
2016-01-05_16:01:17.32379 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process'
2016-01-05_16:01:17.32379 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one'
2016-01-05_16:01:17.32380 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
2016-01-05_16:01:17.32380 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
2016-01-05_16:01:17.32380 /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by stanhu** [comment]
Looks like you're another victim of a [bug with the JIRA service integration in 8.3](https://gitlab.com/gitlab-org/gitlab-ce/issues/5878). This would stop updates from going through. This has been [patched here](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2341) and will be released in GitLab 8.3.3 soon.

Right now you have several options:

1. Deactivate JIRA temporarily in the project services
2. Manually apply the patch and restart GitLab
3. Wait for GitLab 8.3.3 (see [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/5547) for status)

**Comment by doenietzomoeilijk** [comment]
I'll see if option one helps - just disable JIRA for a project, see if all the pushes work after that? I can test that tomorrow, no problem. Not sure how easy manually applying that patch is, given that we're on an Omnibus install - just apply the change to the file in `/opt/gitlab/embedded/service/gitlab-rails/app/models/project_services` and restart? Is it going to influence the next update or should I just revert the change before then?

I'll give it a go and let you know how things went.

**Comment by stanhu** [comment]
Yes, just disable JIRA for the project in question. Yes, you can just apply the change to that file and restart. The file should automatically be updated in the next release, so no need to revert.

**Comment by stanhu** [comment]
FYI, GitLab 8.3.3 is available now.

**Comment by doenietzomoeilijk** [comment]
Installed 8.3.3 today, and it looks like it fixed the issue! 🍻

**Comment by stanhu** [comment]
FYI, 8.3.4 was released to fix a routing bug today: https://about.gitlab.com/blog/

**Comment by doenietzomoeilijk** [comment]
Thanks for the heads up!
