### ISSUE TITLE
Packager.io is broken.

### ISSUE THREAD

**Issue by Blackskyliner** [gitlabhq/gitlabhq#9970]
Hey there, I don't know if this is a known problem, didn't found anything in the issues though. Maybe it doesn't even have to be an issue regarding the direct gitlabhq jusdirection. But I didn't know where else to post this to.

The https://packager.io/gh/gitlabhq/gitlabhq#8-3-stable is broken. To be exact it's broken since 7.11

Now there are 161 Installations in the wild according to their statistics. I know omnibus/docker is the recommended way of installing Gitlab. But how about, maybe, fixing just the issue that causes the building proccess to fail, if possible? As far as the build log states it's using ruby-2.0.0, maybe thats the reason it breaks?

The most recent build log: https://packager.io/gh/gitlabhq/gitlabhq/build_runs/391 which states:

```
====== Attempt #1

-----> Fetching repository

Cloning into '/tmp/d20160112-29111-11o0lcw/input'...

-----> Restoring cache

-----> Starting packaging process

-----> Installing missing build dependencies: libicu-devel

-----> Fetching buildpack /tmp/buildpacks/sources/pkgr/heroku-buildpack-ruby.git at universal

-----> Ruby app

-----> Running hook: "./bin/pkgr_before_precompile.sh"

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.0.0

-----> Installing dependencies using bundler 1.9.7

       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j2 --deployment

       Fetching gem metadata from https://rubygems.org/........

       Fetching version metadata from https://rubygems.org/...

       Fetching dependency metadata from https://rubygems.org/..

       Installing rake 10.4.2

       Installing CFPropertyList 2.3.2

       Installing RedCloth 4.2.9

       Installing ace-rails-ap 2.0.1

       Installing i18n 0.7.0

       Installing json 1.8.3

       Installing minitest 5.7.0

       Installing thread_safe 0.3.5

       Installing tzinfo 1.2.2

       Installing activesupport 4.2.4

       Installing builder 3.2.2

       Installing erubis 2.7.0

       Installing mini_portile2 2.0.0

       Installing nokogiri 1.6.7.1

       Installing rails-deprecated_sanitizer 1.0.3

       Installing rails-dom-testing 1.0.7

       Installing loofah 2.0.3

       Installing rails-html-sanitizer 1.0.2

       Installing actionview 4.2.4

       Installing rack 1.6.4

       Installing rack-test 0.6.3

       Installing actionpack 4.2.4

       Installing globalid 0.3.6

       Installing activejob 4.2.4

       Installing mime-types 1.25.1

       Installing mail 2.6.3

       Installing actionmailer 4.2.4

       Installing activemodel 4.2.4

       Installing arel 6.0.3

       Installing activerecord 4.2.4

       Installing activerecord-deprecated_finders 1.0.4

       Installing thor 0.19.1

       Installing railties 4.2.4

       Installing activerecord-session_store 0.1.2

       Installing acts-as-taggable-on 3.5.0

       Installing addressable 2.3.8

       Installing after_commit_queue 1.3.0

       Installing multipart-post 2.0.0

       Installing faraday 0.9.2

       Installing faraday_middleware 0.10.0

       Installing multi_json 1.11.2

       Installing faraday_middleware-multi_json 0.0.6

       Installing jwt 1.5.2

       Installing multi_xml 0.5.5

       Installing oauth2 1.0.0

       Installing asana 0.4.0

       Installing asciidoctor 1.5.3

       Installing encryptor 1.3.0

       Installing attr_encrypted 1.3.4

       Installing attr_required 1.0.0

       Installing execjs 2.6.0

       Installing autoprefixer-rails 6.1.1

       Installing descendants_tracker 0.0.4

       Installing ice_nine 0.11.1

       Installing axiom-types 0.1.1

       Installing babosa 1.0.2

       Installing bcrypt 3.1.10

       Installing sass 3.2.19

       Installing bootstrap-sass 3.3.5

       Installing browser 1.0.1

       Installing cal-heatmap-rails 0.0.1

       Installing carrierwave 0.9.0

       Installing charlock_holmes 0.7.3

       Installing chunky_png 1.3.5

       Installing coercible 1.0.0

       Installing coffee-script-source 1.10.0

       Installing coffee-script 2.4.1

       Installing coffee-rails 4.1.0

       Installing colorize 0.7.7

       Installing concurrent-ruby 1.0.0

       Installing connection_pool 2.2.0

       Installing safe_yaml 1.0.4

       Installing crack 0.4.2

       Installing creole 0.5.0

       Installing d3_rails 3.5.6

       Installing default_value_for 3.0.1

       Installing orm_adapter 0.5.0

       Installing responders 2.1.0

       Installing warden 1.2.3

       Installing devise 3.5.3

       Installing devise-async 0.9.0

       Installing rotp 2.1.1

       Installing devise-two-factor 2.0.1

       Installing diff-lcs 1.2.5

       Installing diffy 3.0.7

       Installing doorkeeper 2.2.2

       Using bundler 1.9.7

       Installing hike 1.2.3

       Installing tilt 1.4.1

       Installing sprockets 2.12.4

       Installing sprockets-rails 2.3.3

       Installing rails 4.2.4

       Installing dropzonejs-rails 0.7.2

       Installing email_reply_parser 0.5.8

       Installing equalizer 0.0.11

       Installing escape_utils 1.1.0

       Installing eventmachine 1.0.8

       Installing excon 0.45.4

       Installing expression_parser 0.9.0

       Installing fission 0.5.0

       Installing httparty 0.13.7

       Installing flowdock 0.7.1

       Installing formatador 0.2.5

       Installing fog-core 1.35.0

       Installing fog-json 1.0.2

       Installing inflecto 0.0.2

       Installing fog-brightbox 0.9.0

       Installing fog-xml 0.1.2

       Installing fog-profitbricks 0.0.5

       Installing fog-radosgw 0.0.4

       Installing fog-sakuracloud 1.4.0

       Installing fog-softlayer 1.0.2

       Installing fog-terremark 0.1.0

       Installing fog-vmfusion 0.1.0

       Installing fog-voxel 0.1.0

       Installing ipaddress 0.8.0

       Installing trollop 2.1.2

       Installing rbvmomi 1.8.2

       Installing opennebula 4.14.2

       Installing fog 1.25.0

       Installing font-awesome-rails 4.5.0.0

       Installing rugged 0.23.3

       Installing gemnasium-gitlab-service 0.2.6

       Installing gemojione 2.1.0

       Installing get_process_mem 0.2.0

       Installing github-linguist 4.7.2

       Installing github-markup 1.3.3

       Installing posix-spawn 0.3.11

       Installing gitlab-grit 2.7.3

       Installing gitlab-flowdock-git-hook 1.0.1

       Installing gitlab_emoji 0.2.0

       Installing gitlab_git 7.2.21

       Installing gitlab_meta 7.0

       Installing net-ldap 0.12.1

       Installing hashie 3.4.3

       Installing omniauth 1.2.2

       Installing pyu-ruby-sasl 0.0.3.3

       Installing rubyntlm 0.5.2

       Installing gitlab_omniauth-ldap 1.2.1

       Installing gollum-grit_adapter 1.0.0

       Installing rouge 1.10.1

       Installing sanitize 2.1.0

       Installing stringex 2.5.2

       Installing gollum-lib 4.1.0

       Installing request_store 1.2.1

       Installing gon 6.0.1

       Installing rack-accept 0.4.5

       Installing rack-mount 0.8.3

       Installing virtus 1.0.5

       Installing grape 0.13.0

       Installing grape-entity 0.4.8

       Installing haml 4.0.7

       Installing sexp_processor 4.6.0

       Installing ruby_parser 3.5.0

       Installing html2haml 2.0.0

       Installing haml-rails 0.9.0

       Installing mimemagic 0.3.0

       Installing hipchat 1.5.2

       Installing html-pipeline 1.11.0

       Installing http_parser.rb 0.5.3

       Installing httpclient 2.7.0.1

       Installing jquery-atwho-rails 1.3.2

       Installing jquery-rails 3.1.4

       Installing jquery-scrollto-rails 1.4.3

       Installing turbolinks 2.5.3

       Installing jquery-turbolinks 2.1.0

       Installing jquery-ui-rails 4.2.1

       Installing kaminari 0.16.3

       Installing kgio 2.10.0

       Installing systemu 2.6.5

       Installing macaddr 1.7.1

       Installing mail_room 0.6.1

       Installing mousetrap-rails 1.4.6

       Installing mysql2 0.3.20

       Installing nested_form 0.3.2

       Installing net-ssh 3.0.1

       Installing newrelic_rpm 3.9.4.245

       Installing newrelic-grape 2.0.0

       Installing nprogress-rails 0.1.6.7

       Installing oauth 0.4.7

       Installing sawyer 0.6.0

       Installing octokit 3.7.1

       Installing omniauth-oauth 1.1.0

       Installing omniauth-bitbucket 0.0.2

       Installing omniauth-oauth2 1.3.1

       Installing omniauth-facebook 3.0.0

       Installing omniauth-github 1.1.2

       Installing omniauth-gitlab 1.0.1

       Installing omniauth-google-oauth2 0.2.10

       Installing omniauth-multipassword 0.4.2

       Installing timfel-krb5-auth 0.8.3

       Installing omniauth-kerberos 0.3.0

       Installing uuid 2.3.8

       Installing ruby-saml 1.0.0

       Installing omniauth-saml 1.4.1

       Installing omniauth-shibboleth 1.2.1

       Installing omniauth-twitter 1.2.1

       Installing omniauth_crowd 2.2.3

       Installing rubypants 0.2.0

       Installing org-ruby 0.9.12

       Installing paranoia 2.1.4

       Installing pg 0.18.4

       Installing rack-attack 4.3.1

       Installing rack-cors 0.4.0

       Installing rack-oauth2 1.2.1

       Installing rack-protection 1.5.3

       Installing raindrops 0.15.0

       Installing raphael-rails 2.1.2

       Installing rdoc 3.12.2

       Installing recaptcha 1.0.2

       Installing redcarpet 3.3.3

       Installing redis 3.2.2

       Installing redis-store 1.1.7

       Installing redis-rack 1.5.0

       Installing redis-actionpack 4.0.1

       Installing redis-activesupport 4.1.5

       Installing redis-namespace 1.5.2

       Installing redis-rails 4.0.0

       Installing rinku 1.7.3

       Installing rqrcode 0.7.0

       Installing rqrcode-rails3 0.1.7

       Installing ruby-fogbugz 0.2.1

       Installing rufus-scheduler 3.1.10

       Installing sass-rails 4.0.5

       Installing seed-fu 2.3.5

       Installing select2-rails 3.5.9.3

       Installing settingslogic 2.0.9

       Installing sidekiq 4.0.1

       Installing sidekiq-cron 0.4.0

       Installing simple_oauth 0.1.9

       Installing sinatra 1.4.6

       Installing six 0.2.0

       Installing slack-notifier 1.2.1

       Installing stamp 0.6.0

       Installing state_machines 0.4.0

       Installing state_machines-activemodel 0.3.0

       Installing state_machines-activerecord 0.3.0

       Installing task_list 1.0.2

       Installing twitter-stream 0.1.16

       Installing tinder 1.10.1

       Installing uglifier 2.7.2

       Installing underscore-rails 1.4.4

       Installing unf_ext 0.0.7.1

       Installing unf 0.1.4

       Installing unicorn 4.8.3

       Installing unicorn-worker-killer 0.4.4

       Installing version_sorter 2.0.0

       Installing wikicloth 0.8.1

       Bundle complete! 161 Gemfile dependencies, 248 gems now installed.

       Gems in the groups development and test were not installed.

       Bundled gems are installed into ./vendor/bundle.

       Post-install message from acts-as-taggable-on:

       When upgrading

       Re-run the migrations generator

       rake acts_as_taggable_on_engine:install:migrations

       This will create any new migrations and skip existing ones

       Version 3.5.0 has a migration for mysql adapter

       Post-install message from browser:

       #################### WARNING ##############################

       #                                                         #

       #   Internet Explorer detection has changed on v1.0.0+.   #

       #   If this is important for you, please read             #

       #   https://github.com/fnando/browser#internet-explorer   #

       #                                                         #

       ###########################################################

       Post-install message from httparty:

       When you HTTParty, you must party hard!

       Post-install message from haml:

       HEADS UP! Haml 4.0 has many improvements, but also has changes that may break

       your application:

       * Support for Ruby 1.8.6 dropped

       * Support for Rails 2 dropped

       * Sass filter now always outputs <style> tags

       * Data attributes are now hyphenated, not underscored

       * html2haml utility moved to the html2haml gem

       * Textile and Maruku filters moved to the haml-contrib gem

       For more info see:

       http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

       Post-install message from html-pipeline:

       -------------------------------------------------

       Thank you for installing html-pipeline!

       You must bundle Filter gem dependencies.

       See html-pipeline README.md for more details.

       https://github.com/jch/html-pipeline#dependencies

       -------------------------------------------------

       Post-install message from mousetrap-rails:

       [33mRemember to run generator to generate sample file and include mousetrap-rails with Rails Asset Pipeline[0m

       [32m$ rails generate mousetrap:install [0m

       Post-install message from rdoc:

       Depending on your version of ruby, you may need to install ruby rdoc/ri data:

       <= 1.8.6 : unsupported

       = 1.8.7 : gem install rdoc-data; rdoc-data --install

       = 1.9.1 : gem install rdoc-data; rdoc-data --install

       >= 1.9.2 : nothing to do! Yay!

       Bundle completed (318.10s)

       Cleaning up the bundler cache.

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       WARNING: This version of GitLab depends on gitlab-shell 2.6.9, but you're running Unknown. Please update gitlab-shell.

       Missing `db_key_base` for 'production' environment. The secrets will be generated and stored in `config/secrets.yml`

       rake aborted!

       SyntaxError: /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/app/models/concerns/taskable.rb:27: syntax error, unexpected ','

       def self.get_updated_tasks(old_content:, new_content:)

       ^

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/app/models/concerns/taskable.rb:62: syntax error, unexpected keyword_end, expecting end-of-input

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:360:in `require_or_load'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:526:in `load_missing_constant'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/app/models/issue.rb:29:in `<class:Issue>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/app/models/issue.rb:24:in `<top (required)>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:360:in `require_or_load'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:494:in `load_missing_constant'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:526:in `load_missing_constant'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:526:in `load_missing_constant'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:184:in `const_missing'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/lib/api/notes.rb:6:in `<class:Notes>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/lib/api/notes.rb:3:in `<module:API>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/lib/api/notes.rb:1:in `<top (required)>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/lib/api/api.rb:1:in `block in <top (required)>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/lib/api/api.rb:1:in `each'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/lib/api/api.rb:1:in `<top (required)>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/config/routes.rb:3:in `<top (required)>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `each'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:40:in `load_paths'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:16:in `reload!'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:26:in `block in updater'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `call'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/file_update_checker.rb:75:in `execute'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:27:in `updater'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/config/environment.rb:5:in `<top (required)>'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'

       /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'

       Tasks: TOP => environment

       (See full trace by running task with --trace)

 !

 !     Precompiling assets failed.

 !

     ! ERROR: compile failed

       ! FAILED.

         Failure during packaging

       ! Please contact support.
```

I will just mention @crohr here as he helped with the last issue about packager.io, I found in the closed issues (#7790). 

If no support will be given anymore for this platform (packager.io), then maybe delete the repository there, if possible? So that maintainers will get notified by their update proccess (apt, yum) that the software they are using is outdated and that they should search for a better/newer way of using/handing/installing Gitlab on their systems.

**Comment by Danyboy** [comment]
Workaround for this error:
```ruby
SyntaxError: /tmp/d20160112-17-1qbhftw/opt/gitlab-ce/app/models/concerns/taskable.rb:27: syntax error, unexpected ','
       def self.get_updated_tasks(old_content:, new_content:)

diff --git a/app/models/concerns/taskable.rb b/app/models/concerns/taskable.rb
-  def self.get_updated_tasks(old_content:, new_content:)
+  def self.get_updated_tasks(old_content, new_content)
```

And next error:
```ruby
I, [2016-01-20T15:58:42.350670 #2972]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': /home/git/
gitlab/app/controllers/proje
..._commit(service, success_path:, failure_view:, failure_path:)

diff --git a/app/controllers/projects/blob_controller.rb b/app/controllers/projects/blob_controller.rb
-  def create_commit(service, success_path:, failure_view:, failure_path:)
+  def create_commit(service, success_path, failure_view, failure_path)
```

Patch:
[0001-Workaround-for-gitlabhq-gitlabhq-issue-9970.patch.txt](https://github.com/gitlabhq/gitlabhq/files/97713/0001-Workaround-for-https-github.com-gitlabhq-gitlabhq-is.patch.txt)

**Comment by rymai** [comment]
@Blackskyliner @Danyboy That's because you're using Ruby 2.0. If you switch to Ruby 2.1, it will work.

The reason is that [Ruby 2.0 introduced Keyword Arguments](http://dev.af83.com/2013/02/18/ruby-2-0-keyword-arguments.html) (i.e. `def self.get_updated_tasks(old_content: 'foo', new_content: 'bar')` but [Keyword Arguments _without a default value_ (i.e. `def self.get_updated_tasks(old_content:, new_content:)` was introduced in Ruby 2.1](http://blog.rkh.im/ruby-2.1).

In addition, [GitLab officially requires Ruby 2.1.x](http://doc.gitlab.com/ce/install/requirements.html#ruby-versions).

Hope that helps.

**Comment by crohr** [comment]
Hi there, Packager.io maintainer here. Last time I checked packaging failed because Gitlab switched to using a `.secret` file generated from an ERB template in their configuration tool, instead of relying on env variables. Now there seems to be another issue with the ruby version, so I'll have a look and see if I can easily fix both and submit a PR.

**Comment by connorshea** [comment]
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.
